ID Teks
ID teks mentakrif pelbagai jenis teks yang berkaitan dengan objek teks.
Contohnya, obek "TEXT" (teks piawai) boleh mempunyai ID teks berikut:
ST untuk teks piawai khusus pengguna (teks individu)
SYST untuk teks sistem silang aplikasi
pelbagai ID untuk jabatan aplikasi tertentu.
Anda perlu mempunyai sah kuasa capaian yang sesuai bagi mencapai teks ini.
Lokasi Simpanan Pengeluaran
Gunakannya untuk mengeluarkan bahan ketika proses pengeluaran.
Lokasi simpanan pengeluaran menyokong pancur balik.
Ini bermakna bahawa keluaran barangan untuk bahan diposkan secara automatik apabila anda mengeposkan pesanan pengeluaran kepada stok.
Lokasi keluaran dalam item dipaparkan dalam pesanan pengeluaran sebagai lalai.
Apabila anda memasukkan item bil bahan, sistem menyemak sama ada bahan ditakrifkan untuk lokasi loji dan simpanan yang dipilih.
Anda hanya boleh selenggarakan lokasi simpanan pengeluaran untuk item bahan yang berkaitan dengan penyelenggaraan pengeluaran dan/atau loji.
Jika item yang berkaitan dengan pengeluaran ditakrifkan sebagai bahan pukal, anda tidak boleh membuat entri untuk lokasi simpanan pengeluaran.
Untuk tujuan pengeluaran, lokasi simpanan dalam item bil bahan menggantikan lokasi simpanan pada induk bahan.
Jika anda tidak memasukkan lokasi simpanan pengeluaran dalam item bil bahan, sistem menggunakan nilai daripada induk bahan.
Status Mesej
Sediakan maklumat lanjut mengenai himpunan untuk anda.
Ikon Maklumat muncul jika mana-mana atau semua yang berikut wujud untuk himpunan:
Bil Bahan Kejuruteraan
Bil Bahan Perkilangan
Kumpulan Produk
Himpunan dalam status diruntuhkan.
Kotak dialog Maklumat juga menyediakan pilihan untuk memuatkan bil bahan kejuruteraan, bil bahan perkilangan atau kumpulan produk dalam Panel Sumber.
Himpunan kembali kepada status hierarki dikembangkan sebaik sahaja anda memuatkan mana-mana atau semua struktur.
Swap Kadar Faedah
Swap kadar faedah ialah urus niaga yang menukar aliran pembayaran berdasarkan pada kadar faedah berbeza dalam mata wang yang sama.
Anda bersetuju dengan tempoh tertentu, kebiasaannya melebihi setahun.
Swap kadar faedah membolehkan anda melindung nilai risiko kadar faedah yang berpotensi.
Gabungan swap kadar faedah yang berpotensi ialah:
Pembayar
Penerima
Asas
Anda boleh memaparkan dua aliran tunai untuk swap kadar faedah sama ada bersama-sama atau berasingan.
Ia memberikan paparan keseluruhan bagi bayaran masuk dan keluar.
Untuk swap dengan pengiraan kadar faedah boleh ubah, pelarasan kadar faedah manual atau automatik dijalankan sepanjang tempoh dan aliran tunai diisi secara beransur dengan nilai semasa.
Syarikat membiayai pelaburan sedia ada dengan pinjaman faedah tetap pada 6.5%.
Bendahari syarikat menjangkakan penurunan dalam kadar faedah dan telah bersetuju dengan swap kadar faedah dengan bank.
Daripada swap kadar faedah ini, syarikat menerima 7.25% hasil faedah tetap dan membayar kadar boleh ubah 6-M-EURIBOR.
Oleh itu, syarikat mempunyai kos kadar faedah berikut:
6.5% perbelanjaan faedah dan 6-M-EURIBOR
Hasil faedah daripada 7.25% SWAP
Ia menyebabkan perbelanjaan faedah bagi 6M-EURIBOR - 0.75%
Kad Tempoh Beban Berkurangan
Data untuk tempoh dengan penggunaan peruntukan di bawah 20%.
Kad Tempoh Beban Berkurangan memaparkan data untuk tempoh yang asalnya kuantiti diperuntukkan untuk objek peruntukan produk telah digunakan sehingga 20%.
Data yang dipaparkan dalam kad diisih mengikut muatan, bermaksud objek peruntukan produk dengan penggunaan kuantiti yang dirancang paling rendah disenaraikan terlebih dahulu.
Anda boleh menapis data yang dipaparkan dengan peningkatan sebanyak 5% dalam juntai bawah takrifan muatan.
Dari kad Tempoh Beban Berkurangan, anda boleh menavigasikan ke aplikasi Pantau Tempoh Peruntukan Produk yang anda boleh paparkan kuantiti dan data muatan untuk tempoh peruntukan, objek peruntukan produk dan gabungan nilai ciri yang memenuhi kriteria penapis anda.
Mengklik tarikh mula tempoh atau baris dalam kad Tempoh Beban Berkurangan membawa anda secara langsung ke skrin Tempoh Peruntukan yang memperincikan data tentang tempoh dan item pesanan yang berkaitan dengan data kuantiti untuk tempoh yang dipilih.
Jenis Pool
Cara cash pooling, seperti cash pool fizikal dan cash pool nominal.
Terdapat tiga cara cash pooling:
Cash Pool Fizikal melibatkan tunai yang besar secara fizikal di antara akaun subsidiari dan akaun pengepala pada asas baki sasaran.
Cash Pool Nominal
Cash Pool Hibrid
Kini, hanya jenis cash pool fizikal tersedia.
Masukkan Data Asas dan Takrif Perulangan
Dalam kotak dialog Cipta Jalanan Pengekosan Baru, masukkan nama jalanan pengekosan, tarikh jalanan pengekosan dan parameter diperlukan lain.
Varian pengekosan menentukan cara struktur kuantiti dinilai dan cara overhed dikira.
Versi pengekosan membolehkan anda mempunyai dua atau lebih anggaran kos untuk bahan dengan varian pengekosan dan tarikh pengekosan sama.
Perulangan
Anda boleh memilih untuk menetapkan jalanan untuk ulang secara automatik pada selang yang tetap:
Di bawah Perulangan, pilih kekerapan selang (seperti Bulanan).
Pilih langkah selepas pelaksanaan jalanan seterusnya perlu berhenti seketika.
Apabila langkah Pengekosan dilaksanakan, jalanan seterusnya dijadualkan berdasarkan kekerapan.
Setelah selesai langkah yang anda tentukan, pemprosesan berhenti seketika untuk membolehkan anda menyemak hasil dan menyelesaikan sebarang ralat sebelum teruskan.
Prasyarat Langkah
Anda boleh takrifkan satu atau lebih prasyarat yang perlu dipenuhi sebelum langkah boleh diproses.
Takrifkan satu atau lebih prasyarat yang perlu dipenuhi sebelum langkah aliran kerja permintaan memo kredit boleh diproses.
Jika satu daripada prasyarat tidak dipenuhi, langkah tidak akan dimulakan.
Permintaan memo kredit disekat:
Permintaan memo kredit yang kini disekat ialah prasyarat wajib.
Nilai bersih lebih besar daripada:
Permintaan memo kredit melebihi amaun praktakrif yang boleh disediakan sebagai prasyarat tambahan.
Pusat Kerja
Anda boleh menapis hasil anda berdasarkan pusat kerja.
Anda boleh menggunakannya untuk menapis hasil anda berdasarkan pada kod abjad angka unik yang mengenal pasti pusat kerja.
Bagi pilihan pemilihan lebih terperinci, gunakan bantuan input.
Untuk Proses jenis industri:
Semua sumber dalam bahagian tanggungjawab anda akan dipaparkan.
Lajur Pusat Kerja menyenaraikan sumber pesanan yang sepadan.
Konfigurasi Struktur Organisasi
Jelajah struktur organisasi dan sesuaikannya mengikut keperluan syarikat anda.
Dengan aplikasi ini, anda boleh jelajah dan sesuaikan struktur organisasi lalai yang dihantar dengan kandungan pakej penyelesaian.
KONFIGURASI TERTENTU FASA
Dalam fasa Jelajah, jelajah struktur organisasi dan jelaskan perubahan dan ID yang perlu disesuaikan dengan keperluan syarikat anda.
Anda juga boleh mula konfigurasi struktur organisasi.
Dalam fasa Praset, muktamadkan struktur organisasi dan masukkan ID unit organisasi tertentu syarikat.
Dalam fasa Realisasi, anda boleh masukkan unit baru.
Status Penumpuan
Untuk menunjukkan sama ada penumpuan berjaya dijalankan.
Hasil jalanan penumpuan tunai.
Status boleh menjadi:
Ralat apabila terdapat ralat dalam penciptaan permintaan pembayaran dalam kelompok.
Permintaan Pembayaran Dicipta apabila semua permintaan pembayaran berjaya dicipta dalam kelompok.
Berjaya apabila semua permintaan pembayaran dilaksanakan dengan jalanan pembayaran dan penyata bank.
Kategori
Semak dan, jika diperlukan, tambah maklumat kategori untuk kandungan undang-undang anda.
Kategori ialah tag untuk mengelaskan kandungan undang-undang yang ditakrifkan dalam konteks.
Mereka diselenggarakan secara pusat dalam aplikasi Kategori dan diumpukkan ke konteks.
Semasa anda umpukan konteks ke permintaan undang-undang anda, maklumat kategori daripada konteks ditambah dan boleh dipertingkat dengan kategori tambahan.
Kategori juga mengawal individu yang dapat melihat transaksi undang-undang yang dicipta daripada permintaan kandungan undang-undang anda.
Jika sah kuasa untuk satu daripada kategori yang diumpukkan hilang, pengguna tidak boleh melihat transaksi undang-undang.
Ketahui Status Nod ICF
Ketahui status nod ICF.
Status nod ICF boleh menjadi:
Diaktifkan: pertanyaan sedia untuk digunakan oleh KPI dan laporan melalui apliaksi Report Design dan KPI Design masing-masing.
Tidak Diaktifkan: pengaktifan masih dalam proses.
Ralat Pengaktifan: ralat berlaku.
Laporkan kejadian di bawah komponen BC-SRV-APS-EXT-AQD.
Rancang Sebagai
Membenarkan anda membuat pemilihan untuk perancangan dan pemindahan komponen ke Panel Sasaran.
Panel Sumber mengandungi senarai juntai bawah Rancang Sebagai dengan pilihan berikut:
Direka
Buat salinan langsung komponen dalam Panel Sumber ke Panel Sasaran.
Dikembangkan
Buat salinan langsung komponen dikembangkan dalam Panel Sumber ke Panel Sasaran.
Dalam Kerja
Tambah bahagian atau himpunan dipilih ke Panel (Dalam Kerja) Sasaran.
Penerbitan Parameter Penilaian
Penerbitan automatik parameter penilaian.
Anda menggunakan penunjuk untuk terbitan parameter penilaian berikut daripada tetapan dalam pengurusan kedudukan:
Jenis penilaian (daripada tatacara pengurusan kedudukan berkaitan)
Jenis CVA/DVA (daripada tatacara pengurusan kedudukan berkaitan)
Jika jenis CVA/DVA tidak diselenggarakan dalam tatacara pengurusan kedudukan, CVA dan DVA tidak dikira dan oleh yang demikian kedua-dua ditetapkan ke sifar.
Jenis harga/NPV (daripada tatacara diumpukkan sebagai langkah dalam tatacara pengurusan kedudukan berkaitan)
Mata wang penilaian berkaitan untuk gabungan kod perakaunan dan bahagian penilaian
Jika urus niaga kewangan mempunyai set parameter penilaian yang berbeza dalam pelbagai bahagian penilaian, semuanya digunakan.
Semasa anda masukkan bahagian penilaian tertentu pada skrin pemilihan, anda boleh sekat pengiraan ke bahagian penilaian yang dipilih ini.
Kategori
Di sini anda boleh umpukan kategori untuk transaksi undang-undang anda.
Kategori diwakili dalam struktur pepohon sebagai hierarki bebas nilai.
Kategorisasi objek dalam Pengurusan Kandungan Undang-undang membantu untuk mencari padanan terbaik antara satu sama lain.
Anda mencipta kategori dalam aplikasi Kategori dan umpukan ia ke profil.
Profil yang anda umpukan ke konteks menentukan kategori yang boleh anda pilih dan umpukan ke konteks.
Anda pesan kategori diumpukan dalam kumpulan kategori.
Anda boleh tambah dan keluarkan kategori.
Atribut Diperlukan menunjukkan sama ada kategori ini diperlukan dalam transaksi undang-undang atau sama ada ia hanya cadangan dan m
Kontrak untuk Had
Tentukan bilangan kontrak yang anda boleh memilih item perkhidmatan.
Kontrak untuk Had menentukan bilangan kontrak yang anda memilih item perkhidmatan yang dilaksanakan dalam lembaran entri perkhidmatan.
Ia adalah sebahagian daripada senario berikut:
Dalam kontrak belian, pembeli telah mentakrifkan set perkhidmatan potensi yang mungkin diperlukan untuk projek tertentu di syarikat anda.
Dalam item pesanan belian, pembeli telah mencipta item had dengan kumpulan jenis produk Perkhidmatan.
Pembeli mengumpukkan kontrak belian pada item had ini dengan memasukkan bilangan kontrak ke dalam medan Kontrak untuk Had sebagai sumber bekalan.
Dalam lembaran entri perkhidmatan, anda menyelenggarakan bilangan pesanan belian sebagai Pesanan Belian Rujukan.
Sistem memperoleh bilangan kontrak belian secara langsung daripada item pesanan belian dan memaparkan nombor kontrak dalam medan Kontrak untuk Had.
Dengan memasukkan Item kontrak Belian, anda memilih item perkhidmatan masing-masing daripada kontrak.
Kontrak belian juga menentukan harga setiap unit bagi setiap perkhidmatan.
Semakan Pesanan yang Diserahkan
Papar senarai pesanan yang diserahkan untuk tarikh yang dipilih.
Anda boleh melihat senarai pesanan yang telah ditetapkan untuk diserahkan pada tarikh yang dipilih.
Anda juga boleh memaparkan maklumat berikut:
Kapasiti tersedia bagi pusat kerja
Kapasiti diperlukan untuk menyelesaikan operasi
Kapasiti digunakan oleh pusat kerja untuk menyerahkan pesanan
RUC_CONF_MM_PUR_CROSSCATSEARCH
Anda perlu cari item dalam pelbagai katalog dan tapis serta isihnya mengikut harga.
Untuk melakukan sedemikian, anda mesti mengaktifkan mata wang biasa.
Ini membolehkan perbualan harga dalam mata wang berbeza kepada mata wang biasa semasa import data katalog.
Kemudian anda boleh tapis dan isih item mengikut harga.
Anda tidak menggunakan carian silang katalog dan perlu menyahdayakan medan carian pada antara muka pengguna.
Untuk melakukan sedemikian, anda perlu memilih pilihan untuk menyembunyikan bar carian.
Had Item
Membolehkan anda mencipta item had untuk perkhidmatan dan bahan tidak dirancang.
Anda boleh mencipta item had untuk perkhidmatan atau bahan tidak dirancang, iaitu perkhidmatan atau bahan yang tidak boleh ditentukan dalam butiran pada masa pemesanan.
Dalam kedua-dua kes, anda mentakrifkan nilai dijangka, keseluruhan had dan tempoh masa:
Had untuk bahan:
Pilih Kumpulan Jenis Produk Bahan (1)
Dalam kes item had untuk bahan, penerimaan barangan tidak mungkin.
Invois diposkan secara langsung dengan rujukan kepada pesanan belian dengan syarat tidak melebihi had nilai ditentukan.
Had untuk perkhidmatan lean:
Pilih Kumpulan Jenis Produk Perkhidmatan (2)
Jika item had untuk perkhidmatan, lembaran entri perkhidmatan boleh dicipta jika diperlukan.
Ia juga mungkin untuk mengeposkan invois dengan serta-merta.
Hantar Semula
Hantar semula salinan dokumen surat-menyurat kepada pelanggan anda.
Pilih surat-menyurat yang anda ingin hantar semula kepada pelanggan anda dan pilih Hantar Semula.
Status surat-menyurat mesti ditetapkan kepada selesai sebelum anda boleh hantarnya semula.
Untuk menghantar semula penghubung:
Pilih item surat-menyurat untuk dihantar semula dan pilih Hantar Semula.
Item surat-menyurat baru muncul dalam senarai Butiran Output.
Pilih item surat-menyurat baru, pastikan item surat-menyurat asal tidak dipilih.
Jika anda mahu, anda boleh mengubah saluran output atau butiran output yang tersedia untuk item surat-menyurat yang dipilih.
Pilih Hantar Output untuk menghantar surat-menyurat sekali lagi.
Ciri Kumpulan
Kriteria untuk kumpulan hasil lot pemeriksaan
Menggunakan Tetapan, anda boleh tentukan ciri kumpulan mengikut sebarang hasil lot pemeriksaan yang dirumuskan.
Ciri kumpulan ditunjukkan mengikut akhiran (Characteristic) atau (Char).
Hasil lot pemeriksaaan dipilih secara individu dirumuskan sebagai satu objek diagregat sama ada mereka sepadan dengan ciri kumpulan.
Contohnya, jika anda hanya pilih ciri bahan dan pemeriksaan induk sebagai ciri kumpulan, semua hasil lot pemeriksaan untuk ciri bahan dan pemeriksaan induk telah diagregat dalam satu lajur senarai.
Contohnya, jika anda pilih ciri bahan, pembekal dan pemeriksaan induk sebagai ciri kumpulan, semua hasil lot pemeriksaan untuk ciri gabungan pembekal bahan dan pemeriksaan induk telah diagregat dalam satu lajur senarai.
Angka utama untuk hasil lot pemeriksaan dipilih dikira pada tahap pengagregatan.
Ubah Kapasiti Tersedia
Klik untuk simulasi cara perubahan kapasiti tersedia yang akan memberi kesan pada perancangan anda.
Hanya klik dan semak Penggunaan Kapasiti Dicadangkan (dalam Peratus).
Jika anda ingin menerima pakai cadangan, hanya klik Terima Pakai Cadangan, kemudian klik Guna.
Anda juga boleh memasukkan peratusan berbeza bagi penggunaan kapasiti baharu.
Perubahan ketara sahaja ditunjukkan dalam sistem.
Perubahan kecil mungkin tidak dipertimbangkan sebagai perubahan.
Ubah Dokumen
Anda boleh menjejaki perubahan dalam objek perniagaan tersuai.
Dengan pilihan ini, anda boleh menjejaki perubahan yang dilakukan pada objek perniagaan tersuai pada UI yang dijanakan pada tahap entri.
Dokumen perubahan akan merekod medan yang dicipta atau diubah.
Dokumen perubahan boleh dicapai melalui UI objek perniagaan tersuai yang dijanakan.
Oleh itu, rekod perubahan boleh dicapai dengan sah kuasa sama yang diperlukan untuk objek perniagaan tersuai.
Untuk maklumat lanjut mengenai penciptaan objek perniagaan tersuai, lihat.
Tingkah Laku Katalog Laman dalam
Pengguna luaran yang tidak disahkan yang mencapai katalog laman perlu menambah item percuma dan berbayar ke kart beli-belah mereka.
Jika anda ialah pengguna luaran yang tidak disahkan cuba untuk menambah kursus percuma melalui katalog laman, anda perlu menambah item ke kart anda dan lengkapkan proses beli-belah.
untuk menambah item percuma dan berbayar, klik "Tambah ke Kart."
Klik ikon tersebut akan membawa anda ke kart beli-belah anda.
Jika anda cipta dan log masuk dengan akaun, anda boleh memilih kursus percuma yang akan ditambah ke Tugasan Pembelajaran anda dan melancarkannya tanpa apa-apa tindakan lanjutan.
Jika pengguna luaran atau pengguna disahkan memilih kursus berbayar, anda perlu klik "Tambah ke Kart" dan lengkapkan proses melalui kart beli-belah anda.
Pemprosesan Besar-besaran
Memproses pelbagai produk aktif pada satu masa
Anda boleh memproses pelbagai produk yang aktif pada satu masa menggunakan ciri ini.
Anda perlu memilih pelbagai produk aktif daripada senarai dan kemudian klik butang Pemprosesan Besar-besaran Mula.
Aplikasi akan menavigasi ke aplikasi Pemprosesan Besar-besaran yang anda boleh menjalankan tindakan yang diperlukan.
Ambil perhatian bahawa anda hanya boleh menjalankan pemprosesan besar-besaran apabila anda memilih pelbagai rekod produk aktif.
Jika anda memilih produk aktif tunggal, anda akan melihat butang Pemprosesan Besar-besaran dilumpuhkan.
Uruskan Aset Tetap
Gantikan kad Senarai Kerja Induk Aset.
Kad Uruskan Aset Tetap baharu menggantikan kad Senarai Kerja Induk Aset daripada versi sebelumnya.
KPI menunjukkan bilangan aset yang aktif dan carta menunjukkan jumlah bagi setiap kategori.
Aset aktif ialah aset yang telah diperoleh atau dipermodalkan.
Ambil perhatian bahawa bilangan aset aktif pada kad ini tidak termasuk aset yang kini dalam mod draf.
Hal ini boleh berlaku apabila pengguna dalam proses mengubah status aset, contohnya.
Klik mana-mana pada carta untuk navigasi ke aplikasi Uruskan Aset Tetap.
Bahan dengan Sumber Tidak Sah
Tunjukkan jumlah bilangan bahan dalaman dengan sumber bekalan tidak sah.
Anda boleh melihat jika bahan mempunyai sumber bekalan tidak sah dan bilangan bahannya.
Anda boleh menyemak bahan dalaman yang tiada sumber bekalan yang sah dalam paparan Simulasi Rancangan Permintaan dan Simulasi Bahan Berbilang Tahap.
Klik isu.
Kemudian semak Isu di bawah kategori isu Tiada Sumber Sah dan lihat butiran lanjut mengenai bahan khusus yang tiada sumber bekalan yang sah.
Contohnya, anda boleh melihat minggu atau bulan yang ketiadaan sumber bekalan dan tidak berjaya menjalankan perolehan.
Simulasi Rancangan Kapasiti
Memberi paparan keseluruhan mengenai situasi kapasiti pusat kerja kepada anda.
Dalam Simulasi Rancangan Kapasiti, kapasiti pusat kerja dipaparkan dalam tempoh masa yang ditetapkan (baldi).
Anda boleh papar semua bahan tahap teratas bagi pusat kerja.
Keluaran kapasiti diserlahkan dengan warna merah.
Klik sel berwarna merah dan gunakan pemeriksa untuk memberitahu dan menyelesaikan keluaran kapasiti.
Anda boleh pilih untuk meningkatkan kapasiti tersedia dengan menyemak perkongsian dalam penggunaan bagi setiap bahan.
Rujuk kaedah tersebut dan buat perubahan kapasiti serta lihat jika situasi kapasiti bertambah baik.
Tingkah Laku Katalog Laman dalam
Pengguna luaran yang tidak disahkan yang mencapai katalog laman mesti menambah item percuma dan berbayar ke kart beli-belah mereka.
Jika anda ialah pengguna luaran yang tidak disahkan cuba untuk menambah kursus percuma melalui katalog laman, anda mesti menambah item ke kart anda dan lengkapkan proses beli-belah.
Apabila anda menambah item percuma dan berbayar, klik Tambah ke Kart untuk membawa anda ke kart beli-belah anda.
Jika anda cipta dan log masuk dengan akaun, anda boleh memilih kursus percuma yang ditambah ke Tugasan Pembelajaran anda.
Kemudian, anda boleh melancarkannya tanpa apa-apa tindakan lanjutan.
Pengguna luaran dan pengguna disahkan mesti mengklik Tambah ke Kart untuk kursus berbayar dan lengkapkan proses melalui kart beli-belah mereka.
Jam Rehat
Ini adalah ketersediaan sebenar untuk umpukan.
Medan ini memberitahu anda jumlah jam sebenar bagi sumber yang tersedia untuk umpukan dalam tempoh masa ditentukan.
Umpukan sedia ada diambil kira.
Jam rehat dikira seperti berikut:
Jam Rehat = Jam Tersedia - Jam Kakitangan
Jika bilangan jam kakitangan lebih tinggi daripada bilangan jam tersedia, maka bilangan jam rehat ialah sifar.
Jenis Dokumen Berikutan
Takrifkan jenis dokumen berikutan.
Anda boleh takrifkan jenis dokumen susulan yang akan dicipta secara automatik selepas sebut harga diberikan.
Jenis dokumen susulan tersebut adalah tersedia:
Kontrak Kuantiti
Kontrak Nilai
Pesanan Belian Piawai
Jika anda telah dipilih Permintaan Harga Luaran (RSI) sebagai jenis RFQ, anda hanya boleh pilih Pesanan Belian Piawai sebagai jenis dokumen susulan.
Jika anda telah piilih Permintaan Sumber Luaran (RE) sebagai jenis RFQ, anda boleh pilih satu daripada tiga jenis dokumen susulan yang disenaraikan di atas.
Walau bagaimanapun, jika anda kemudian pilih jenis berbeza dokumen susulan dalam SAP Ariba Sourcing, pemilihan semasa akan ditulis ganti.
Jika anda telah piilih Permintaan Sumber Dalaman (RQ) sebagai jenis RFQ, anda boleh pilih satu daripada tiga jenis dokumen susulan yang disenaraikan di atas.
Unit Organisasi
Papar dan edit butiran unit organisasi.
Anak tetingkap ini menunjukkan butiran unit organisasi dipilih dalam struktur organisasi bahagian kiri.
Data berikut dipaparkan untuk unit organisasi (jika dapat dikenakan):
Unit khusus negara tanggungan
Hubungan dengan unit lain
Struktur komponen bagi unit semasa
Dari butiran unit organisasi, anda boleh menggunakan fungsi pengeditan berikut:
Tambah unit organisasi tanggungan.
Tambah hubungan dengan unit organisasi lain.
Agihkan
Masukkan bilangan jam yang anda ingin agihkan.
Masukkan bilangan jam yang anda ingin agihkan sepanjang hari tersedia dalam tempoh masa umpukan.
Jika anda pilih peraturan Jumlah Jam, pratetapan bilangan jam adalah seperti berikut:
Jika anda ubah tetapan penapis semasa mencari sumber sesuai untuk permintaan, aplikasi mencadangkan tetapan penapis anda.
Jika anda tidak mengubah tetapan penapis semasa mencari sumber sesuai, aplikasi mencadangkan bilangan (baki) jam diperlukan mengikut perkara yang ditetapkan dalam permintaan.
Jika anda memilih peraturan Seperti Diminta, anda tidak boleh mengubah bilangan jam.
Tekan Enter untuk melihat cara umpukan yang akan menjejaskan angka utama yang ditunjukkan dalam jadual dan kalendar.
Kumpulan Pemuatan
Empat aksara abjad angka yang mewakili kumpulan bahan yang berkongsi keperluaan pemuatan sama.
Sistem menggunakan kumpulan pemuatan serta syarat penghantaran dan loji penghantaran untuk menentukan secara automatik titik penghantaran bagi item.
Contohnya, kumpulan pemuatan berbeza yang terdiri daripada bahan yang memerlukan perkara sama:
Peralatan semasa pemuatan (contohnya, forklift)
Amaun masa untuk pemuatan
Titik pemuatan (contohnya, ruang pemunggahan #6)
Jenis Padanan
Jenis peraturan pemadanan.
Peraturan pemadanan mestilah mempunyai salah satu jenis padanan berikut:
Padanan Tepat:
Apa-apa data yang melepasi peraturan mempunyai status pemprosesan Sepadan muktamad tanpa memerlukan tindakan selanjutnya.
Diumpukkan Automatik:
Apa-apa data yang melepasi peraturan mempunyai status pemprosesan Diumpukkan, yang bermaksud anda perlu menyemak data yang diumpukkan dan lengkapkan apa-apa aktiviti susulan yang diperlukan. Contohnya, memicukan aliran kerja atau mengeposkan pelarasan automatik atau mengesahkan item yang sepadan selepas komunikasi.
Kumpulan yang Sepadan:
Jenis padanan ini mengumpulkan data yang ditapis bersama-sama dan mengumpukkan kumpulan dengan status pemprosesan Sepadan, dan tiada tindakan selanjutnya diperlukan.
Contohnya, anda mungkin ingin menggunakan jenis peraturan pemadanan ini untuk catatan jurnal dibalikkan yang tidak berkaitan dengan penyelarasan antara syarikat.
Kumpulan yang Diumpukkan:
Jenis padanan ini mengumpulkan data yang ditapis bersama-sama dan mengumpukkan kumpulan dengan status pemprosesan Diumpukkan untuk tindakan pengguna yang diperlukan untuk mencapai status akhir Sepadan.
Contohnya, anda mungkin ingin menggunakan jenis peraturan pemadanan ini untuk catatan jurnal yang tidak mempunyai maklumat mengenai pekongsi perdagangan.
Tiada ungkapan pemadanan diperlukan untuk peraturan pemadanan yang diumpukkan dengan jenis padanan Kumpulan yang Sepadan atau Kumpulan yang Diumpukkan.
Umpukan Automatik sebagai Pengecualian:
Mempunyai kelakuan sistem sama seperti Umpukan Automatik.
Contohnya, anda boleh menggunakannya untuk memadankan dokumen yang mempunyai nombor invois sama dan kod mata wang berbeza.
Tambah Item Skop
Tambah item skop tersuai
Dengan fungsi ini anda boleh menambah item skop tersuai ke kumpulan item skop Penyelesaian Kandungan Pelanggan Tambahan.
Untuk menambah item skop:
Masukkan nama (ID) item skop baru dalam ruang nama pelanggan SAP (bermula dengan Z).
Masukkan perihalan.
Simpan.
Item
Tambah item dan selenggara maklumat terperinci.
Anda boleh tambah item berbilang ke RFQ anda.
Untuk lakukan sedemikian, tambah item baru dan pilih ia daripada senarai.
Dalam medan Kumpulan Jenis Produk, pilih "1" untuk jenis Bahan atau "2" untuk jenis Perkhidmatan.
Untuk setiap item, anda boleh pilih sama ada ia adalah jenis Bahan atau Perkhidmatan.
Anda boleh tambah lampiran pada aras item.
Jika kemudian anda cipta RFQ baru dengan menyalin sesuatu yang sedia ada, kedua-dua lampiran dan maklumat umum untuk item disalin secara automatik.
Destinasi Ketersambungan
Menunjukkan destinasi induk yang merupakan tempat langkah proses berlaku.
Destinasi ketersambungan digunakan untuk komunikasi keluar bagi aplikasi cloud ke sistem jauh.
Penutupan Kewangan Lanjutan menyokong takrifan, pelaksanaan dan pemantauan terpusat bagi proses yang ditakrif dalam templat tugas merentasi sistem berbilang.
Destinasi ketersambungan yang dimasukkan dalam pengepala templat tugas digunakan sebagai destinasi induk untuk langkah proses.
Sistem jauh tidak boleh disambung buat masa ini.
Tetapan lalai ialah LOCAL.
Aktiviti penutupan kewangan mesti dijalankan dalam sistem cloud SAP S/4HANA yang sama.
Nama Varian
Mengandungi nama varian yang digunakan untuk jalanan dan tambahan, maklumat berkaitan jalanan.
Lajur Nama Varian mengandungi nama varian digunakan untuk jalanan seperti tertakrif dalam aplikasi Varian BOP Konfigurasi
Jalanan pemprosesan tertangguh biasanya ditakrifkan untuk jalanan dalam bahagian belakang, bermaksud:
Dokumen perniagaan dikemas kini untuk mencerminkan pengesahan dikira semula.
Dokumen berkunci dipaparkan tetapi dikecualikan dari kemas kini.
Jika Ringkasan dipaparkan di bawah nama varian:
Pengecualian dijanakan semasa jalanan asal.
Untuk membetulkan pengecualian dengan menyediakan pengesahan, sekurang-kurangnya satu jalanan tambahan dilaksanakan pada asas varian gantian prakonfigurasi (jalanan gantian).
Hasil bagi semua jalanan diperlukan untuk menjanakan pengesahan telah digabungkan dalam ringkasan.
Jika Simulasi dipaparkan di bawah nama varian:
Jalanan telah dilaksanakan dalam mod simulasi untuk mengenal pasti jika jalanan akan meningkatkan data pengesahan yang terjana semasa jalanan berlangsung.
Dokumen berkunci tidak dikecualikan dari simulasi.
Diposkan ke Stok Pemeriksaan
Sedang atau telah berada dalam stok pemeriksaan
Membenarkan anda untuk tapis lot pemeriksaan berdasarkan sama ada kuantiti lot diposkan ke stok pemeriksaan apabila lot pemeriksaan dicipta.
Anda boleh pilih antara dua pilihan:
Tidak:
Cadangan Pengeposan Stok dan Kuantiti Dipos tidak dipaparkan dalam halaman butiran.
Ya:
Cadangan Pengeposan Stok dan Kuantiti Diposkan dipaparkan dalam halaman butiran.
Anda juga boleh picu pengeposan stok bahan bagi jenis stok Stok Lot Pemeriksaan ke jenis stok dipaparkan.
Anda juga boleh pisahkan kuantiti Stok Lot Pemeriksaan untuk diposkan di antara jenis stok dipaparkan dan pilih lokasi simpanan untuk jenis stok Penggunaan Tanpa Had dan Stok Disekat.
Sebelum Simpan
Guna corak ini untuk sahkan data sebelum simpan.
Corak ini digunakan untuk sahkan kekonsistenan tika nod dalam fasa simpanan.
Logik bagi corak ini menyemak nilai medan untuk ketepatan dan papar mesej ralat jika nilai medan tidak betul.
Selepas semakan ini, medan boleh diedit secara manual.
Jika nilai medan tidak memenuhi keperluan semakan, objek perniagaan tersuai tidak boleh disimpan.
Nilai medan perlu dibetulkan sebelum objek perniagaan tersuai boleh disimpan.
Sampel kes penggunaan:
Anda mahu semak nilai medan yang dimasukkan dalam format betul atau anda mahu semak jika semua medan wajib telah diisi dengan nilai.
Diskaun Tunai yang Diambil
[FinancialConfiguration-configurecash] Selenggara butiran untuk diskaun tunai bagi kod syarikat.
Bahagian Perniagaan
Anda mentakrif strategi untuk mengambil diskaun tunai maksimum yang tersedia semasa membuat pembayaran kepada vendor.
Strategi diskaun tunai boleh ditakrif untuk setiap kod syarikat.
Strategi pembayaran mengandungi tetapan tertentu seperti cara amaun diskaun tunai dan tarikh pembayaran ditentukan daripada syarat pembayaran.
Diskaun tunai boleh ditentukan secara automatik dan ditolak apabila invois vendor dibayar, menggunakan data yang berikut:
Syarat pembayaran untuk setiap vendor:
Syarat pembayaran telah diumpukkan dalam data induk vendor berkaitan.
Syarat pembayaran untuk setiap invois:
Syarat pembayaran telah diumpukkan apabila invois pembekal dimasukkan.
Jika syarat pembayaran wujud untuk invois pembekal, sistem membatalkan syarat ini dan tidak merujuk syarat pembayaran yang dimasukkan dalam data induk untuk vendor itu.
Jika tiada syarat pembayaran diumpukkan semasa entri invois, sistem menggunakan syarat pembayaran untuk vendor berkaitan.
Cipta Aplikasi
Cipta aplikasi untuk pertanyaan analisis
Anda guna medan ini untuk cipta dan terbitkan tile ke katalog di mana pertanyaan diterbitkan baru boleh dibuka sebagai aplikasi berasingan.
Medan ini mempunyai 2 pilihan, Laporan Pelbagai Dimensi dan Laporan Pelbagai Dimensi Menggunakan Templat Web Dynpro.
Kedua-dua pilihan membenarkan anda mencipta dan menerbitkan jubin manakala yang kedua mencipta aplikasi yang menyokong kebolehcapaian.
Ciri ini dinyahdayakan untuk pertanyaan analisis yang tidak dikeluarkan.
Dalam kata lain, anda boleh mencipta aplikasi sahaja untuk pertanyaan analisis yang dikeluarkan.
Penciptaan PIR untuk
Anda boleh mencipta PIR untuk komponen dan/atau bahan tahap teratas.
Semasa mengeluarkan simulasi anda, anda boleh menentukan penciptaan keperluan tidak bersandar terancang (PIR).
Pilih kotak semak yang sepadan untuk komponen MRP yang didorong oleh permintaan dan/atau bahan tahap teratas.
Untuk komponen didorong oleh permintaan, PIR dicipta secara automatik untuk versi PIR 00 dan versi adalah aktif.
Untuk bahan tahap teratas, anda boleh memilih versi PIR dan menentukan sama ada anda ingin terus mengaktifkannya atau tidak.
Anda juga boleh mengaktifkan versi PIR dalam aplikasi Selenggarakan PIR.
Mula Dalam Talian
Aktifkan medan ini jika anda tidak ingin menjalankan kerja ini menggunakan pemprosesan selari.
Tentukan jika anda ingin menggunakan pemprosesan selari untuk kerja ini:
Untuk muatan kerja lebih banyak:
Nyahaktif medan ini untuk menggunakan pemprosesan selari bagi kerja ini.
Anda boleh menggunakan pemprosesan selari jika anda ingin melakukan perubahan pada bilangan Pekongsi perniagaan yang besar.
Anda boleh pisahkan kerja ini kepada beberapa pakej kerja.
Untuk muatan kerja lebih sedikit:
Aktifkan medan ini untuk menjalankan kerja ini dalam mod dalam talian.
Medan Bilangan Kerja dan Saiz Pakej dinyahaktifkan dan tidak berkaitan dengan kerja ini.
Tunggakan Kos Pesanan
Tunggakan Kos Pesanan (%) pada tarikh rujukan.
KPI menunjukkan jumlah Tunggakan Kos Pesanan (%) pada tarikh rujukan untuk objek yang dipilih.
Nilai ini merupakan pembalikan nilai Kos Pesanan Terkini (%) dan menunjukkan peratus Kos Piawai Pesanan sebaik sahaja Nilai Selesai Terkini dan WIP diambil kira.
Pengiraan Tunggakan Kos Pesanan (%) adalah seperti berikut:
100 - (((Nilai Selesai + WIP) / Kos Piawai Pesanan) * 100)
Carta menunjukkan trend melebihi empat hari sebelumnya.
Butiran Kelas
Tentukan butiran kelas yang dimasukkan sebagai item kelas dalam bil bahan boleh dikonfigurasi.
Di sini, anda menyelenggarakan butiran untuk semua kelas yang anda masukkan sebagai item kelas dalam bil bahan boleh dikonfigurasi.
Bahagian Butiran Kelas mempunyai penunjuk berikut:
Komponen Diperlukan
Pilih kotak semak jika anda ingin mentakrifkan objek dari kelas yang mesti dipilih apabila anda mengkonfigurasi bil bahan.
Pelbagai Pemilihan
Pilih kotak semak jika anda ingin mentakrifkan beberapa objek dari kelas yang boleh dipilih apabila anda mengkonfigurasi bil bahan.
RUC_CONF_LOG_F1333
Anda ingin membeli barangan atau perkhidmatan daripada pembekal yang berdaftar pada Ariba Network.
Untuk melakukan sedemikian, anda mesti mendayakan penyepaduan teknikal antara dan Ariba Network.
Mengumpukkan ID Ariba Network untuk kod syarikat dalam SAP S/4HANA membolehkan Ariba Network mengenal pasti penghantar data daripada.
Anda perlu memilih yang berikut:
ID Ariba Network yang mengenal pasti syarikat anda pada Ariba Network.
Anda telah menerimanya daripada Ariba.
Kod Syarikat yang sepadan dengan ID Ariba Network.
Sebaik sahaja anda menyimpan entri ini, anda tidak lagi boleh mengeditnya.
Jika perlu, padam entri anda dan cipta yang baru.
Pembekal Perkhidmatan
Pembekal untuk perkhidmatan cash pooling.
Pembekal perkhidmatan cash pool sama ada bank atau syarikat.
Pembekal perkhidmatan ialah bank:
Cash pool dikendalikan oleh bank.
Memandangkan bank bertanggungjawab terhadap penumpuan tunai dan aktiviti pengagihan, penumpuan tunai manual tidak disokong untuk jenis cash pool ini.
Untuk cash pool bagi jenis ini, anda mesti mentakrifkan Penggunaan Pool sebagai Kedua-dua Arah.
Pembekal perkhidmatan ialah Syarikat:
Cash pool dikendalikan oleh syarikat anda.
Anda boleh menseketikakan penumpuan secara manual atau jadualkan kerja untuk penumpuan tunai bagi cash pool ini menggunakan aplikasi Uruskan Penumpuan Tunai dan Jadualkan Kerja untuk Penumpuan Tunai.
Dalam struktur cash pool berbilang aras, cash pool bagi jenis ini boleh diumpukkan sebagai cash pool aras atas sahaja.
Pesanan Lampau Tempoh
Paparkan pesanan dikeluarkan yang akhirnya belum lagi disahkan
Pada kad Pesanan Lampau Tempoh, anda boleh analisis pesanan penyelenggaraan dikeluarkan tarikh akhir dalam tempoh rujukan dan telah diluluskan.
Sekurang-kurangnya satu operasi dalam pesanan penyelenggaraan lampau tempoh yang akhirnya belum lagi disahkan.
Jika anda mahu paparkan semua operasi pesanan lampau tempoh dan pesanan dalam senarai dan sahkannya, klik pada kad.
Senarai memaparkan semua operasi yang belum lagi disahkan akhirnya dikumpukan mengikut pesanan.
Anda boleh pilih operasi pesanan individu secara langsung dalam senarai dan umpukan pusat kerja baru atau masukkan pengesahan masa.
Untuk melakukan perkara ini, pilih Ubah Umpukan atau Tambah Pengesahan Masa dalam bar alat jadual.
Dokumen
Dokumen membentuk urus niaga perniagaan yang mengubah baki akaun dalam akaun kontrak dan / atau akaun G/L.
Dokumen berfungsi sebagai baki akaun dalam Kontrak Akaun Belum Terima dan Belum Bayar dan secara tidak langsung juga sebagai data rumusan dalam Perakaunan Lejar Am, Pengawalan dan Pengurusan Tunai.
Item terbuka yang terkandung dalam dokumen membentuk asas untuk pemprosesan berikutnya seperti pembayaran, notis dunning dan pengiraan faedah.
Dokumen terdiri daripada data pengepala, item untuk akaun kontrak dan item untuk akaun G/L.
Selain nombor dokumen yang unik, data pengepala juga mengandungi jenis dokumen sebagai atribut pengelasan, kod mata wang dan pelbagai spesifikasi tarikh.
Semua item mengandungi amaun pengeposan dan maklumat yang diperlukan untuk Perakaunan Lejar Am, Pengurusan dan Pengawalan Tunai.
Item dalam akaun kontrak juga mengandungi spesifikasi mengenai tarikh akhir, diskaun tunai untuk mengawal dunning, pembayaran automatik atau memo debit serta untuk mengira faedah.
Item dalam akaun kontrak boleh menjadi statistik.
Item statistik tidak mengemas kini angka urus niaga dalam lejar am.
Item terbuka yang sepadan hanya diperlukan untuk mencipta pengeposan susulan.
Contohnya, apabila anda menjelaskan caj belum terima statistik, ia memicukan ciptaan caj belum terima tanpa statistik, penjelasan dan pengeposan hasil masing-masing.
Apabila anda menjelaskan permintaan pengebilan belanjawan, ia memicukan ciptaan pengeposan pengebilan belanjawan.
Dokumen boleh mengandungi spesifikasi ulangan.
Dalam kes ini, dokumen mewakili jujukan transaksi yang bergantung pada masa dengan struktur yang sama.
Contohnya, anda boleh mengeposkan permintaan pengebilan belanjawan untuk pembayaran pengebilan belanjawan yang diminta setiap bulan selama dua belas bulan sebagai dokumen.
Dalam kategori item tambahan, yang dikenali sebagai item ulangan, data yang berbeza mengikut masa (seperti tarikh akhir untuk diskaun tunai, tarikh akhir untuk pembayaran bersih atau tempoh pengebilan) direkodkan.
Spesifikasi ulangan hanya boleh dibuat jika dokumen hanya mengandungi item statistik.
Edit / Simpan
Edit fungsi perniagaan dan aktifkannya dengan menyimpannya.
Setelah anda membuat semua entri untuk fungsi perniagaan anda, anda akan mempunyai pilihan berikut:
Kembali ke paparan keseluruhan fungsi perniagaan tanpa menyimpan fungsi perniagaan.
Fungsi perniagaan anda disimpan sebagai draf yang tersedia pada paparan keseluruhan fungsi perniagaan.
Anda boleh mencari versi draf fungsi perniagaan dalam jadual paparan keseluruhan dan membuka fungsi untuk pengeditan selanjutnya dari sana.
Jika anda telah mengedit fungsi perniagaan aktif, versi drafnya akan dipaparkan sebagai tambahan kepada versi aktif fungsi.
Simpan fungsi perniagaan.
Ia secara automatik akan mengaktifkannya setelah fungsi perniagaan disimpan.
Ia tersedia sebagai fungsi perniagaan aktif pada paparan keseluruhan fungsi perniagaan.
Anda boleh membuka fungsi untuk pengeditan selanjutnya dari sana.
Jika anda telah mengedit fungsi perniagaan aktif, versi draf akan hilang daripada paparan keseluruhan fungsi perniagaan dan versi aktif akan dikemas kini dengan perubahan yang anda lakukan.
Strategi
Menyenaraikan strategi penggantian yang memenuhi kriteria carian tertentu.
Subskrin Strategi menyenaraikan semua strategi penggantian atau sesuatu yang memenuhi mana-mana penapis carian tertentu.
Dengan navigasikan ke skrin seterusnya, anda boleh papar maklumat am mengenai strategi penggantian, kaedah penggantian dan peraturan pembinaan.
Fungsi piawai tersedia untuk mencipta, memapar, mengubah dan memadam strategi:
Untuk papar atau ubah strategi penggantian, klik entri yang sepadan dalam senarai.
Untuk padam strategi penggantian, benderakan entri dalam senarai dan klik Padam.
Ambil perhatian bahawa strategi penggantian yang digunakan secara aktif dalam aplikasi Konfigurasikan Kawalan Alternatif tidak boleh dipadam daripada pangkalan data.
Strategi penggantian yang bukan dalam penggunaan aktif boleh dipadam daripada pangkalan data tanpa apa-apa sekatan.
Pengebilan retroaktif
Penunjuk mengawal penggunaan sebab pesanan semasa pengebilan retroaktif kerana perubahan harga retrospektif.
Pilih salah satu daripada pilihan berikut:
Permintaan atau memo kredit/debit digunakan untuk pengebilan retroaktif.
Jika anda cipta dokumen dengan merujuk kepada dokumen pengebilan, nilai diambil kira apabila sistem menentukan nilai pengebilan retroaktif terbuka untuk dokumen pengebilan.
Memo kredit/debit mestilah bil retroaktif jika terdapat perubahan dalam harga.
Jika anda menentukan sebab pesanan dalam permintaan, maka, memo kredit/debit dirujuk kepada bil retroaktif; ia bermakna permintaan dianggap seperti pulangan/pesanan biasa.
Pengemaskinian Angka Urus Niaga Akaun Lejar Am
Anda boleh mengemas kini angka urus niaga dalam akaun lejar am yang terdapat pada lejar am dalam mata wang tempatan dan transaksi.
Anda boleh mengubah akaun ketika operasi semasa.
Untuk urus niaga yang diposkan sebelum pertukaran, angka urus niaga tidak berubah; ia hanya direkod dalam mata wang tempatan.
Untuk belum terima, bayaran pendahuluan dan penjelasan cukai bagi bayaran pendahuluan, pengeposan penjelasan juga hanya dikemas kini dalam mata wang tempatan jika item terbuka diposkan sebelum pertukaran.
Dari sudut pandangan mata wang, baki akaun dianggap betul selepas pertukaran jika syarat berikut dipenuhi:
Akaun untung dan rugi:
Pertukaran berlaku sebelum pengeposan dalam tahun fiskal semasa.
Akaun belum terima (bayaran pendahuluan, penjelasan cukai):
Semua item diposkan sebelum pertukaran telah dijelaskan.
Sekatan
Apabila anda pos bayaran pendahuluan berkaitan cukai, akaun bayaran pendahuluan dan akaun penjelasan cukai mesti mempunyai tetapan yang sama iaitu Baki dalam Mata Wang Tempatan mesti aktif atau tidak aktif dalam kedua-dua akaun.
Jika terdapat balikan, pulangan atau tetapan semula penjelasan untuk pengeposan penjelasan dalam mata wang ketiga iaitu jika sebahagian daripada item yang akan dijelaskan diposkan dalam mata wang berbeza ke mata wang penjelasan, anda tidak boleh balikkan pengeposan tetapan semula ini sekali lagi.
Alat untuk Pertukaran
Selepas pertukaran akaun belum terima, angka urusniaganya adalah salah selagi masih terdapat item terbuka dalam mata wang asing yang diposkan sebelum pertukaran.
Sebagai sebahagian daripada penutupan akhir tahun, pengeposan tambahan diperlukan untuk memaparkan mata wang dengan betul menggunakan akaun pelarasan belum terima.
Dengan menggunakan aplikasi Paparkan Senarai Item Terbuka untuk Tarikh Rujukan, anda boleh menentukan nilai yang akan direkod dalam akaun belum terima jika semua pengeposan dikemas kini dalam mata wang yang betul.
Jalankan penilaian dalam varian yang telah menetapkan penunjuk Mata Wang Kemas Kini dan Bukannya Mata Wang Transaksi dan Simulasikan Mata Wang Kemas Kini pada halaman tab Kawalan Output.
Anda mengepos perbezaan antara hasil penilaian item terbuka dan baki akaun belum terima dalam mata wang yang akan dipertimbangkan untuk menggunakan akaun pelarasan.
Mata wang tempatan EUR, mata wang asing yang dipertimbangkan USD.
Akaun belum terima mempunyai baki sebanyak 400,000 USD dengan nilai semasa dalam mata wang tempatan sebanyak 320,000 EUR.
Berdasarkan senarai item terbuka, nilai yang betul adalah sebanyak 480,000 USD dengan nilai sebanyak 380,000 EUR.
Akaun pelarasan belum terima diuruskan dalam mata wang yang betul.
Anda juga memerlukan akaun interim dengan baki yang hanya diuruskan dalam mata wang tempatan.
Pengeposan pelarasan berikut adalah diperlukan:
Pelarasan belum terima ke akaun interim sebanyak 80,000 USD (60,000 EUR).
Akaun interim ke pelarasan belum terima sebanyak 60,000 USD (60,000 EUR).
Untuk pengeposan pertama, anda perlu menentukan amaun mata wang asing dan amaun mata wang tempatan secara tak tersirat.
Dalam penilaian item terbuka untuk tarikh rujukan, anda boleh memaparkan jumlah dalam mata wang transaksi atau dalam mata wang kemas kini.
Untuk penjelasan dalam mata wang alternatif, ia menyebabkan hasil yang berbeza.
Dalam mod simulasi, hasil dipaparkan seolah-olah kemas kini yang dilaraskan mata wang telah aktif dalam akaun belum terima sejak mula.
Anda juga boleh menjalankan penilaian mengikut mata wang kemas kini dan amaun kemas kini dengan menggunakan aplikasi untuk menyelaraskan lejar am.
Pengumpukan
Buat umpukan manual untuk item dipilih.
Untuk membuat umpukan manual, anda perlu memilih perkara berikut terlebih dahulu:
Satu atau beberapa item tidak diumpukkan yang mempunyai pasangan unit utama dan unit pekongsi sama atau
Satu atau beberapa item tidak diumpukkan dan satu umpukan yang mempunyai pasangan unit utama dan unit pekongsi yang sama.
Kemudian, pilih Umpukkan untuk memadankannya secara manual dan memberikan nombor umpukan serta menggabungkannya ke dalam nombor umpukan yang sedia ada.
Item diumpukkan dikeluarkan ke senarai dalam jadual Umpukan di bawah.
Ketika umpukan manual untuk item tidak diumpukkan, anda diprom untuk menentukan kod sebab yang menentukan tindakan susulan (jika ada) diperlukan untuk membuat umpukan berubah daripada status Diumpukkan kepada Sepadan.
Pengelasan Pelanggan
Takrifkan pengelasan pelanggan yang mungkin untuk pelanggan yang berkemungkinan di bawahnya.
Apabila mentakrifkan pengelasan pelanggan, tentukan dua aksara kod abjad angka dan perihalan untuk setiap pengelasan pelanggan.
Setelah dicipta, anda boleh tentukan pengelasan pelanggan dalam maklumat am rekod induk pelanggan yang sebahagiannya daripada maklumat pemasaran.
Ia bermaksud peruntukan untuk pengelasan pelanggan adalah sah bagi semua bahagian jualan.
Apabila memproses aktiviti jualan, anda boleh memaparkan pengelasan pelanggan yang diumpukkan kepada pelanggan.
Untuk melakukannya, anda boleh memanggil data induk pelanggan sebagai maklumat tambahan.
Pengelasan pelanggan tidak disalin ke dalam dokumen jualan.
Topeng Pengekodan
Digunakan untuk menentukan struktur untuk ID elemen projek.
Topeng pengekodan membolehkan struktur ditentukan bagi ID elemen projek.
Topeng pengekodan mengandungi bahagian yang dipisahkan oleh pemisah.
Ciri yang berikut tersedia:
Setiap bahagian topeng pengekodan boleh mengandungi aksara berangka (diwakili oleh ‘0’) atau aksara abjad angka (diwakili oleh ‘X’).
Pemisah digunakan untuk memisahkan topeng pengekodan daripada kod pengekodan.
Ia juga digunakan untuk mewakili tahap elemen WBS seterusnya.
Pemisah boleh terdiri daripada simbol yang berikut:
/, ., :, >,;, -, <, =.
Ruang letak
Dalam medan Subjek, HTML Kandungan dan Teks Kandungan templat e-mel, anda boleh gunakan ruang letak yang memaparkan nilai dari medan dalam paparan Core Data Services (CDS).
Ruang letak mesti menggunakan sintaks berikut:
{{<field name>}}.
Teks “Harga adalah {{Amount}} {{Currency}}" mengandungi dua ruang letak, satu untuk medan Amaun dan satu untuk medan Mata Wang.
Jika medan Amaun dalam paparan CDS sepadan mempunyai nilai 42 dan medan Mata Wang mempunyai nilai EUR, teks terhasil adalah “Harga adalah 42 EUR”.
Jika anda pilih Tunjukkan Medan Data, senarai bagi semua medan tersedia dengan perihalan dipaparkan.
Butiran Ruang Letak
Nama medan
Pastikan yang anda hanya masukkan nama medan sedia ada dalam ruang letak.
Jika ruang letak menggunakan nama medan yang tidak wujud dalam paparan CDS, tiada nilai medan yang dipaparkan.
Contohnya, teks “Ini nama medan yang tidak sah {{NonExistingField}}” dipaparkan sebagai “Ini nama medan yang tidak sah {{NonExistingField}}”
Pemformatan
Tarikh dan nombor diformatkan mengikut tetapan pengguna bagi pengguna yang melaksanakan API.
Teks "Hari ini adalah {{CurrentDate}}" merujuk kepada medan CurrentDate dengan nilai 20141130 dipaparkan sebagai "Hari ini adalah 30.11.2011" untuk pengguna Jerman.
Tindakan
Gunakan corak ini untuk laksanakan tindakan tertentu pada data.
Corak ini digunakan untuk laksanakan tindakan tertentu pada nod bagi objek perniagaan tersuai.
Anda boleh cipta tindakan dalam mod edit bagi objek perniagaan tersuai.
Anda boleh laksanakan pengekodan bagi tindakan selepas anda telah menerbitkan objek perniagaan tersuai anda.
Tindakan boleh ditakrifkan untuk satu nod bagi objek perniagaan tersuai.
Tindakan hanya boleh dilaksanakan daripada UI yang dijanakan untuk objek perniagaan tersuai.
Mengimport parameter:
Tindakan telah membaca capaian ke semua nod bagi objek perniagaan tersuai.
Mengubah parameter:
Tindakan telah menulis capaian ke nod yang tindakannya telah dicipta.
Mengeksport parameter:
Anda boleh takrifkan ralat, amaran dan mesej berjaya yang dipaparkan selepas tindakan telah dilaksanakan.
Sampel kes penggunaan:
Anda mahu tetapkan secara manual set bagi permintaan ke Diluluskan.
Aset dalam Pembinaan - Pengusiaan
Tunjukkan usia aset di bawah pembinaan.
KPI menunjukkan usia purata pada hari aset dalam pembinaan,dan item individu disenaraikan di bawah.
Anda boleh pesan senarai dengan tarikh perolehan, atau tarikh transaksi terakhir.
Kad ini tidak didayakan secara lalai.
Kad memerlukan sumber sistem yang penting, oleh itu, sila sedia maklum bahawa pendayaan kad ini mungkin memberi kesan terhadap prestasi.
Anda boleh navigasi dari sini ke aplikasi Transaksi Aset.
Hierarki Versi Penyata Kewangan
Uruskan Hierarki Perakaunan Global kini menyokong hierarki versi penyata kewangan.
Sebagai tambahan ke pusat keuntungan, pusat kos, dan hierarki bahagian kefungsian, Uruskan Hierarki Perakaunan Global kini juga menyokong hierarki versi penyata kewangan (FSV).
Anda boleh cipta dan selenggara hierarki FSV, import ia dari aplikasi Selenggara Versi Penyata Kewangan, dan boleh umpukan tag semantik dalam hierarki FSV anda.
Sila ambil perhatian bahawa dalam beberapa kes, beberapa fungsi negara tertentu tidak disokong dalam Uruskan Hierarki Perakaunan Global.
Dalam kes ini, anda harus gunakan aplikasi Selenggara Versi Penyata Kewangan.
Hal ini boleh berlaku kerana dua aplikasi ini menggunakan jadual data yang berbeza.
Jadualkan Jalanan Pemusnahan Data menggunakan Objek Pemunsahan
Anda boleh menjadualkan jalanan pemunsahan menggunakan Objek Pemusnahan.
Untuk menjadualkan jalanan pemusnahan data:
Pilih objek Pemusnahan dan lihat buntiran lanjut seperti Objek ILM Dipetakandan tarikh Jalanan Pemusnahan Terakhir.
Pilih objek pemusnahan yang anda ingin padamkan secara kekal dan klik Jadualkan.
Tetingkap timbul dipaparkan meminta pengesahan pemadaman.
Jika anda sahkan pemadaman, objek pemusnahan dijadualkan untuk jalanan pemusnahan data.
Semasa jadual seterusnya berjalan untuk 7 hari seterusnya, semua objek pemusnahan yang ditanda untuk pemadaman akan dimusnahkan secara kekal.
Penyalinan Item Output
Membolehkan anda menghantar item output yang dipilih sekali lagi.
Butang Salin membolehkan anda menghantar item output sekali lagi apabila anda mengedit pesanan belian.
Sebaik sahaja anda mengklik Salin, item output yang dipilih mendapat status Dalam persediaan dan bergantung pada tetapan anda, ia akan dihantar semula sama ada dengan serta-merta atau selepas menjalankan kerja aplikasi.
Anda tidak boleh memberhentikan output atau memadamkan item output walaupun jika anda membatalkan pemprosesan pesanan belian.
Sila ambil perhatian bahawa perubahan yang dibuat sebelum simpanan tidak diambil kira jika anda menyalin item output yang dipilih.
Sistem hanya menjanakan output untuk data yang berterusan (yang telah disimpan).
Ia bermaksud:
Sistem menghantar output yang dikemas kini kepada pembekal sebaik sahaja anda menyimpan data dengan mengklik Pesanan dan setelah pesanan belian telah diluluskan.
Anda telah memesan sebanyak 10 komputer riba dan output telah dihantar kepada pembekal.
Anda mengedit pesanan belian sekali lagi dan anda mengubah kuantiti sebanyak 12 komputer riba.
Sebelum menyimpan perubahan, anda memilih item output yang sedia ada dan mengklik butang Salin.
Output dengan 10 komputer riba disalin.
Jika anda kini klik Pesanan, sistem menghantar item output yang disalin dengan 10 komputer riba dan menjanakan item output lain dengan 12 komputer riba dan menghantarnya kepada pembekal juga.
Sila klik butang Salin jika anda hanya ingin menghantar data yang sama sekali lagi.
Tambah Lebih Banyak Pilihan Berjadual / Edit Pilihan Berjadual
Meneliti pilihan berjadual anda seperti perulangan kerja.
Dengan mengklik pautan ini, anda boleh meneliti pilihan berjadual anda seperti perulangan kerja.
Dalam dialog Maklumat berjadual yang muncul apabila anda telah mengklik pautan, anda boleh:
Takrifkan zon waktu untuk entri tarikh dan masa anda
Takrifkan corak perulangan seperti harian atau mingguan
Untuk minit, masukkan sekurang-kurangnya 30 minit.
Takrifkan jika kerja sepatutnya hanya dijalankan pada hari bekerja.
Bagi perkara ini, anda perlu pilih kalendar tertentu.
Uruskan Status Audit Berbilang
Membolehkan anda mengumpukkan rekod rawak untuk diaudit secara besar-besaran.
Jika anda ingin mengesahkan rekod diimport, anda boleh menggunakan fungsi Uruskan Status Audit untuk Umpukkan Rekod untuk Audit Secara Besar-besaran.
Ia membantu anda mengumpukkan rekod rambang dan mengesahkan sampelnya.
Selepas memilih Umpukkan Rekod untuk Audit Secara Besar-besaran, pilih kuantiti rekod untuk disahkan, contohnya, sepuluh peratus dan pilih Audit Objek.
Lajur Status Audit kemudian baca Menunggu bagi sampel rekod untuk disahkan.
Gunakan medan juntai bawah pada bahagian kiri untuk menapis rekod dengan status Audit Menunggu.
Ujian Naik Taraf Pos
Tab Ujian Naik Taraf Pos mengandungi semua pengautomatikan ujian piawai dihantar oleh SAP
SAP mencipta suite ujian regresi dan laksanakan pemprosesan ujian piawai selepas naik taraf/keluarkan dalam bentuk Rancangan Ujian Naik Taraf Pos pada permintaan pelanggan.
Hasil pelaksanaan ditunjukkan dalam bentuk status enam untuk Ujian Naik Taraf Pos seperti berikut:
Belum Diuji, Berjaya, Gagal, Dalam Proses, Batal, dan Tidak Boleh Laksana.
Status adalah Gagal semasa aplikasi S/4 HANA berhubung ke proses ujian mempunyai perubahan bawah tanah dalam keluaran semasa, dan status ialah status Tidak Boleh Laksana semasa pemetaan data gagal daripada sistem pelanggan.
Status ialah Batal jika pelanggan batalkan pelaksanaan dengan klik pada butang Henti Ujian.
Rancangan ujian Naik Taraf dicipta, diselenggara, dan dilaksanakan oleh SAP.
Pelanggan tidak dibenarkan untuk laksanakan ujian naik taraf pos.
Mereka hanya boleh salin rancangan ujian naik taraf pos dan laksanakan ia.
Ketersediaan (Jam setiap Bulan)
Nilai ini dikira berdasarkan pada pengagihan bulan jam diperlukan dan jam rehat.
Peratusan padanan ketersediaan ini dikira berdasarkan pada pengagihan bulan jam diperlukan dan jam rehat.
Jika bilangan jam rehat setiap bulan melebihi bilangan jam diperlukan, aplikasi menggunakan bilangan jam diperlukan untuk mengira padanan ketersediaan.
Jika bilangan jam rehat kurang daripada bilangan jam diperlukan, aplikasi menggunakan bilangan jam rehat.
Untuk mengira peratusan padanan, aplikasi menjumlahkan jam rehat setiap bulan bagi keseluruhan rangka masa permintaan.
Hasil daripada itu kemudiannya dibahagikan dengan jumlah bilangan jam diperlukan.
Jika permintaan belum diperuntukkan, peratusan sepadan dikira seperti berikut:
% Padanan Ketersediaan Bulanan = (Jam Rehat / Jam Diperlukan) * 100
Jika sebahagian permintaan telah diperuntukkan, peratusan padanan dikira seperti berikut:
% Padanan Ketersediaan Bulanan setiap Bulan = (Jam Rehat / Baki Jam Diperlukan) * 100
Dalam tetapan penapis, anda boleh tentukan supaya peratusan padanan ini digunakan untuk pengiraan jumlah padanan kesesuaian.
Pemetaan Konteks
Tentukan permintaan jika sasaran navigasi memerlukan sifat tertentu.
Takrifkan permintaan jika sasaran navigasi memerlukan sifat tertentu supaya ia boleh dilancarkan.
Ini memastikan sifat tersedia sebagai konteks semasa menavigasikan ke sasaran navigasi ini pada masa jalanan.
Hasil permintaan pemetaan konteks ialah senarai nilai untuk sifat tertentu.
Jika anda telah pilih lebih daripada satu sifat, hasil ialah senarai nilai tupel.
Hasil yang ditambah ke konteks sedia ada diserahkan kepada sasaran navigasi.
Padanan Kemahiran
Lihat kemahiran bagi penyediaan sumber.
Lihat kemahiran yang diperlukan bagi penyediaan sumber dan perkara yang sama serta kemahiran tambahan bagi sumber yang ditawarkan.
Perbezaan peratusan padanan kemahiran bergantung sama ada padanan adalah berdasarkan pada kemahiran sumber secara eksklusif atau kemahiran daripada umpukan lain yang diambil kira ke dalam akaun.
Bahagian
Perkara Ditunjukkan Di Sini
Kemahiran Diperlukan
Kemahiran ini ditentukan dalam permintaan sumber.
Kemahiran dengan tanda semak disediakan oleh sumber.
Kemahiran Sama
Kemahiran ini disediakan oleh sumber dan sepadan dengan kemahiran yang diperlukan.
Kemahiran Tambahan
Kemahiran ini disediakan oleh sumber tetapi tidak berkaitan dengan kemahiran yang diperlukan.
Elemen WBS
Elemen struktur pecahan kerja yang digunakan untuk pengeposan.
Elemen struktur pecahan kerja (WBS) yang untung/rugi, susut nilai dan faedah perlu diposkan.
Dalam medan ini, anda umpukkan elemen WBS ke aset.
Hal ini perlu jika anda ingin membuat umpukan akaun bagi susut nilai dan faedah serta untung/rugi, ke elemen WBS.
Objek umpukan akaun perlu diaktifkan dalam Penyesuaian dan disediakan untuk pengeposan transaksi Kos Pengeluaran dan Pengambilalihan, dan/atau susut nilai.
Untuk sistem mengeposkan susut nilai ke elemen WBS, penunjuk bagi pengeposan ini perlu ditetapkan dalam takrifan Penyesuaian jalanan pengeposan susut nilai.
Sumber Diminta
Sumber ini merupakan sumber diminta oleh pengurus projek.
Sumber ini adalah calon pilihan projek pengurus.
Pengurus projek boleh meminta sumber tertentu apabila menambah fungsi kepada pakej kerja.
Jika mereka melakukannya, organisasi penghantaran sumber yang diminta ditambah secara automatik kepada permintaan sumber.
Sebagai pengurus sumber, anda tidak semestinya perlu mengumpukkan sumber ini untuk permintaan.
Walau bagaimanapun, anda perlu pastikan bahawa anda mengumpukkan sumber daripada organisasi perkhidmatan yang sama.
Padanan Automatik
Untuk menjalankan padanan automatik berdasarkan peraturan pemadanan yang terkandung dalam kaedah pemadanan semasa.
Pilih butang untuk menjalankan padanan automatik bagi unit utama dan unit pekongsi yang ditentukan berdasarkan kaedah.
Semasa jalanan pemadanan, butang Umpukan, Komunikasi, dan Padanan Automatik berwarna kelabu.
Berikut adalah untuk mengelakkan aktiviti serentak pada set data yang sama dan untuk mengelakkan apa-apa ketakkonsistenan data.
Setelah selesai pemadanan, butang didayakan sekali lagi dan data disegar semula.
Untuk mana-mana umpukan sedia ada yang mempunyai kotak semak kod sebab Resolusi sementara dipilih, batalkan umpukan jalanan pemadanan dan mentaksahkan nombor umpukan, membaca dan memadankan semula data terkini daripada sumber data yang berkaitan, menyegarkan semula status pemprosesan dan memicukan apa-apa tindakan susulan yang diperlukan mengikut kod sebab.
Walau bagaimanapun, jika umpukan masih dalam proses pelarasan atau aliran kerja kelulusan automatik, jalanan padanan automatik melangkauinya.
Status Analytics Cloud Story
Papar status Analytics Cloud Story
Papar salah satu daripada status berikut bagi Analytics Cloud Story yang dicipta:
Diterbitkan:
Laporan diterbitkan untuk katalog yang dipilih.
Tidak Diterbitkan:
Laporan sama ada kosong atau tidak berkaitan dengan mana-mana katalog.
Sedang Berjalan:
Laporan belum diterbitkan lagi atau tidak diterbitkan untuk mana-mana katalog.
Diterbitkan Separa:
Satu atau lebih jubin dalam laporan diterbitkan atau dikeluarkan dalam beberapa katalog ketika laporan berada dalam proses penerbitan atau keluarkan pada katalog lain.
Ralat:
Berlaku apabila menerbitkan atau mengeluarkan laporan gagal dalam satu atau lebih katalog.
Paparan
Papar bilangan paparan (CDS) yang dibenarkan untuk dicapai oleh pengguna.
Medan ini memaparkan bilangan paparan Core Data Services (CDS) yang dibenarkan untuk dicapai oleh pengguna.
Hanya paparan analisis dengan anotasi vdm.viewtype =#consumption dan ANALYTICS.QUERY: true dan pertanyaan bukan analisis dengan satu daripada jenis paparan (Asas, Komposit, Penggunaan, Sambungan, dan Tak Tertakrif) dipaparkan dalam aplikasi Pelayar Paparan.
Jenis paparan Tak Tertakrif mengandungi paparan VDM.
Pada tika pertama, nombor dipaparkan ialah jumlah nombor paparan CDS yang boleh dicapai oleh pengguna.
Metrik boleh berubah bergantung kepada kriteria carian anda.
Nombor paparan yang sepadan criteria carian dipaparkan.
Tetapkan Bidang Audit Lalai
Konfigurasikan bidang audit lalai untuk penjana peraturan.
Menggunakan aplikasi ini, anda boleh selenggara tetapan penyesuaian untuk bidang audit lalai.
Anda hanya boleh selenggara satu bidang audit pada satu masa dan ia berkaitan untuk semua objek ILM.
Bidang aduti lalai ini digunakan untuk mentakrif peraturan pengekalan dalam penjana peraturan.
Bidang audit lalai hanya diselenggara untuk polisi pengekalan.
Dalam kes polisi penempatan, PENGARKIBAN digunakan sebagai bidang audit lalai.
Aktif
Menunjukkan jika model mempunyai versi model aktif.
Ramalan hanya boleh dijana apabila versi model telah diaktifkan.
Tanda rait hijau menunjukkan model yang mempunyai versi model aktif.
Hanya satu versi model boleh diaktifkan merentas semua model senario ramalan setiap pelanggan.
Versi model ini kini boleh digunakan untuk janakan ramalan dalam pelanggan semasa.
Berikut ialah versi model yang menjana ramalan secara aktif dalam aplikasi penggunaan.
Komponen Hilang
Paparkan bahan bukan stok yang telah dipesan tetapi tidak akan tersedia tepat masa
Kad ini memaparkan bahan bukan stok yang telah dipesan untuk tujuan penyelesaian kerja penyelenggaraan.
Walau bagaimanapun, ia adalah tidak mungkin untuk menyediakan item bukan stok dengan tarikh penghantaran dijanjikan dan masa pemprosesan penerimaan barangan pada masa.
Bahan yang dipesan tidak tersedia pada tarikh keperluan untuk pesanan penyelenggaraan atau tarikh mula diperlukan pesanan.
Untuk paparkan item pesanan belian dengan bahan bukan stok sepadan dalam senarai, klik pada kad.
Dalam senarai, anda boleh cabangkan ke pesanan belian, data butiran untuk bahan dan pesanan penyelenggaraan, atau paparkan data individu untuk dihubungi bagi pembekal.
Jika anda klik pada bahagian sebelah kanan kad, anda boleh melihat komponen yang hilang dengan maklumat yang lebih penting dipaparkan pada kad dalam karusel.
Di sini anda boleh melihat, contohnya, pembekal, nombor pesanan belian, tarikh keperluan dan keutamaan pesanan.
Kad dalam karusel untuk komponen yang hilang juga membenarkan anda untuk navigasi secara langsung ke pesanan penyelenggaraan yang sesuai dan pesanan belian sepadan serta paparkan ia.
Kumpulan Pemuatan
Empat aksara abjad angka yang mewakili kumpulan bahan yang berkongsi keperluaan pemuatan sama.
Sistem menggunakan kumpulan pemuatan, syarat penghantaran dan loji penghantaran untuk menentukan secara automatik titik penghantaran bagi item.
Contohnya, kumpulan pemuatan berbeza yang terdiri daripada bahan yang memerlukan perkara sama:
Peralatan semasa pemuatan (contohnya, forklift).
Amaun masa untuk pemuatan.
Titik pemuatan (ruang pemunggahan #6).
Cipta Sinonim
Masukkan semua atribut untuk sinonim baru.
Masukkan ungkapan, sinonim sepadan, padanan dan bahasa sinonim.
Kemudian pilih Tambah.
Jika, contohnya, anda ingin carian untuk istilah magician merangkumi istilah illusionist juga dan conjuror, anda cipta entri berasingan untuk setiap sinonim (illusionist dan conjuror).
Jika anda ingin sinonim illusionist diutamakan berbanding sinonim conjuror, oleh itu berikan entri tersebut nilai persamaan (padanan) lebih tinggi daripada sinonim yang lain, contohnya, 0.8 untuk illusionist dan 0.5 untuk conjuror.
Anda boleh umpukkan sinonim untuk bahasa tertentu.
Pilih bahasa yang diinginkan daripada senarai juntai bawah.
Pemberitahuan Tertunggak
Benarkan paparan keseluruhan pemberitahuan untuk mana-mana proses belum dimulakan lagi
Pada kad Pemberitahuan Tertunggak, anda boleh menganalisis dan memantau mesej untuk mana-mana tarikh mula diperlukan dalam tempoh rujukan yang telah anda takrifkan dan mana-mana yang mempunyai status sistem Tertunggak.
Pemberitahuan ini belum diproses lagi atau ia telah diumpukkan untuk pesanan.
Anda boleh gunakan senarai juntai bawah untuk memilih dimensi lanjutan untuk mana-mana nilai yang dipaparkan dalam warna yang berbeza pada carta.
Perkara ini bermaksud bahawa anda boleh paparkan pemberitahuan tertunggak dikumpulkan mengikut jenis pemberitahuan atau jenis aktiviti, contohnya jika anda ingin paparkan pemberitahuan bagi jenis pemberitahuan tertentu atau pemberitahuan proses dengan keutamaan tinggi terlebih dahulu.
Jika anda mahu paparkan semua pemberitahuan tertunggak dalam senarai dan proses lanjutannya, klik pada bahagian atas peta.
Jika anda ingin paparkan pemberitahuan dengan keutamaan tertentu, jenis pemberitahuan atau jenis aktiviti dalam senarai, klik pada bar berwarna yang sesuai dalam carta.
Dalam senarai anda boleh melihat, contohnya, butiran individu untuk dihubungi bagi pekerja yang mencipta pemberitahuan dan pekerja yang bertanggungjawab untuk pemberitahuan.
Selain itu, anda boleh paparkan seberapa banyak pemberitahuan tertunggak lanjutan yang terdapat untuk objek teknikal dalam soalan.
Anda boleh paparkan pemberitahuan individu dan cawangan untuk pemprosesan pemberitahuan.
Baki Amaun/Kuantiti
Tunjukkan amaun atau kuantiti terbuka bagi item lembaran entri perkhidmatan.
Tunjukkan baki amaun atau kuantiti bagi item lembaran entri perkhidmatan.
Sekiranya menjadi rujukan bagi item piawai pesanan belian:
Baki kuantiti (Delta) ialah kuantiti dipesan (Dijangka) tolak kuantiti Disahkan.
Kuantiti Disahkan ialah jumlah kuantiti yang dinyatakan bagi semua item lembaran entri perkhidmatan lain yang merujuk item pesanan belian yang sama.
Sekiranya menjadi rujukan bagi item had pesanan belian:
Baki amaun (Delta) ialah Nilai Dijangka (seperti yang ditakrif dalam item had pesanan belian) tolak amaun Disahkan.
Amaun Disahkan ialah jumlah amaun yang dinyatakan bagi semua item lembaran entri perkhidmatan lain yang merujuk item had pesanan belian yang sama.
Amaun atau kuantiti yang dinyatakan bagi item lembaran entri perkhidmatan semasa tidak termasuk dalam amaun atau kuantiti he Disahkan.
Item lembaran entri perkhidmatan yang lain merujuk item pesanan belian yang sama adalah termasuk amaun atau kuantiti yang Disahkan.
Jenis Mata Wang
Papar catatan jurnal dalam mata wang khusus.
Pilih mata wang untuk catatan jurnal.
Semua catatan jurnal yang anda pilih akan dipaparkan dalam mata wang yang anda pilih.
Mata wang tersedia termasuk:
Mata Wang Kod Syarikat – Mata wang yang ditakrifkan dalam tetapan kod syarikat anda.
Mata Wang Baki Transaksi – Mata wang akaun G/L bagi catatan jurnal diposkan.
Mata Wang Transaksi – Mata wang bagi transaksi perniagaan asal yang terhasil dalam catatan jurnal.
Mata Wang Global – Mata wang telah dikonfigurasikan untuk bahagian pengawalan.
Muat Turun Maklumat Paparan CDS ABAP
Muat turun metadata dan anotasi
Dengan aplikasi Replikasikan Paparan CDS, paparan CDS ABAP dalam sistem SAP S/4HANA direplikasikan sebagai paparan CDS HANA kepada sistem sasaran SAP Cloud Platform.
Oleh kerana sintaks sistem sumber dan sasaran adalah berbeza, anda boleh muat turun anotasi dan metadata bagi paparan CDS ABAP supaya anda boleh mengubah paparan yang dijanakan dalam sistem sasaran.
Pilih paparan CDS dan pilih Muat Turun Maklumat Paparan CDS ABAP untuk simpan ia dalam format JSON:
Anotasi
Metadata
Pemberitahuan
Anda boleh menghantar pemberitahuan mel pada akhir aliran kerja.
Cipta pemberitahuan menggunakan butang Tambah.
Dalam Hasil Aliran Kerja, pilih hasil untuk menghantar pemberitahuan.
Dalam Templat E-mel, pilih templat untuk digunakan.
Kemudian, isi medan Penerima dan pilih Cipta.
Hal ini hanya berkaitan jika aliran kerja anda menyokong pemberitahuan.
Selenggara Profil Entri Data
Profil entri data menentukan medan yang dibenarkan mempunyai data yang dimasukkan apabila mengisi dalam lembar masa.
Apabila seseorang perlu memasukkan masa, mereke memanggil lembar masa dengan menentukan profil entri data.
Profil akan menentukan tataletak dan proses entri data yang diperlukan untuk melengkapkan lembar masa.
Anda boleh mengkonfigurasi beberapa tetapan untuk profil entri data yang menulis ganti tetapan lalai yang dikonfigurasi Profil Entri Data (Lihat Komponen Silang Aplikasi Penyesuaian Lembar Masa Tetapan Tertentu untuk CATS classic Sediakan Profil Entri Data).
Konfigurasi ini kebayakannya digunakan dalam aplikasi Approve Timesheets.
Secara lalai, lembar masa mengambil profil entri data yang dikonfigurasi secara lalai.
Konfigurasi profil entri data lalai dibatalkan hanya jika anda telah sesuaikan profil entri data menggunakan aplikasi konfigurasi.
Kelas
Tentukan ciri bahan boleh dikonfigurasi.
Kelas digunakan untuk dikumpulkan bersama dengan bilangan objek yang sama (seperti dokumen).
Objek ini diterangkan melalui ciri yang mempunyai persamaan (contohnya, format dan saiz).
Dalam bil bahan untuk bahan yang boleh dikonfigurasi, anda boleh memasukkan kelas yang bahan atau dokumennya dikelaskan sebagai item.
Apabila anda konfigurasi bahan, kelas digantikan dengan salah satu atau beberapa bahan mengikut nilai ciri yang diumpukkan.
Item kelas hanya boleh mengandungi kelas untuk bahan atau kelas untuk dokumen.
Anda boleh menggunakan kelas dalam konfigurasi variasi jika jenis kelas menyokong konfigurasi variasi.
Penciptaan Rancangan Ansuran
Anda cipta rancangan ansuran jika terdapat satu atau beberapa item terbuka dalam akaun kontrak pekongsi perniagaan dan pekongsi perniagaan tidak boleh memenuhi kewajipan pembayaran dalam skop peraturan pembayaran biasa.
Apabila anda kira faedah, sistem mencipta dokumen faedah secara automatik.
Apabila anda masukkan amaun caj, sistem mengepos dokumen untuk caj rancangan ansuran.
Semasa pengeposan, dokumen faedah dan caj secara automatik dipindahkan ke rancangan ansuran belum terima asal (lihat Caj dan Faedah untuk Rancangan Ansuran).
Untuk mencipta rancangan ansuran, teruskan seperti berikut:
Panggil aplikasi Selenggara Rancangan Ansuran dan pilih Cipta.
Masukkan parameter pemilihan untuk item terbuka dan parameter pengeposan kemudian pilih Teruskan.
Pilih item terbuka daripada senarai yang anda ingin masukkan dalam rancangan ansuran.
Masukkan parameter rancangan ansuran.
Tarikh mula mentakrif tarikh akhir ansuran pertama.
Anda boleh memindahkan nilai lalai ke skrin awal menggunakan Jenis Rancangan Ansuran atau memasukkan parameter rancangan ansuran secara langsung.
Anda mesti memasukkan selang ansuran dan jenis selang; Anda juga mempunyai pilih untuk memasukkan amaun bagi caj rancangan ansuran serta kategori rancangan ansuran dan nilai untuk medan Amaun Baki.
Sistem mencipta cadangan rancangan ansuran berdasarkan set parameter.
Terdapat dua cara untuk mencipta cadangan rancangan ansuran.
Masukkan amaun dalam medan Amaun Ansuran.
Sistem menentukan bilangan ansuran melalui amaun ansuran dan jumlah item sumber.
Anda juga boleh menambah amaun separa ke rancangan ansuran.
Masukkan nilai dalam medan Amaun Pembundaran dan Bilangan Ansuran.
Amaun ansuran dikira daripada jumlah belum terima asal, amaun pembundaran dan bilangan ansuran.
Jika anda masukkan amaun pembundaran, sistem secara automatik menyemak sama ada amaun ini mematuhi peraturan pembundaran yang ditakrifkan dalam tetapan konfigurasi.
Tanpa mengira sama ada sistem telah mencipta cadangan rancangan ansuran untuk anda dengan memasukkan amaun ansuran atau bilangan ansuran, amaun baki mungkin ada apabila ansuran individu dikira.
Hal ini kerana jumlah ansuran individu perlu sama dengan jumlah belum terima asal (amaun ansuran + bilangan ansuran + amaun baki = jumlah belum terima asal).
Dalam medan Amaun Baki, tentukan sama ada amaun baki ini akan dimasukkan dalam ansuran pertama atau terakhir atau dalam ansuran baharu.
Jika anda tetapkan penunjuk Pengagihan Caj dan Faedah, faedah dan caj diagihkan ke semua tarikh akhir.
Pilih Cadang.
Cadangan Rancangan Ansuran muncul yang membolehkan anda membuat perubahan berikut:
Tambah atau padam ansuran
Kira atau padam faedah
Ubah rancangan ansuran
Agihkan amaun perbezaan
Pada bahagian sudut bawah kanan skrin, sistem memaparkan baki akaun paling penting seperti terbuka dan amaun perlu dibayar.
Jika anda pilih baki, paparan baki akaun muncul dan anda boleh melihat item berkaitan.
Simpan rancangan ansuran.
Jenis RFQ
Bergantung kepada tujuan RFQ anda, anda pilih salah satu daripada jenis RFQ berikut.
Permintaan Harga Luaran (RSI):
Jika anda hanya mahu meminta maklumat harga dan kuantiti atau kos penghantaran, permintaan dihantar ke Ariba Network.
Pembekal boleh cipta bida secara langsung ke Ariba Network dan hantarkan ia semula ke SAP S/4HANA, di mana anda akan diberikan satu daripadanya.
Permintaan Sumber Luaran (RE):
RFQ dihantar ke SAP Ariba Sourcing melalui Ariba Network, di mana pembekal boleh tempatkan bida mereka.
Anda diberi bida dalam SAP Ariba Sourcing dan hantarkan ia semula ke SAP S/4HANA.
Dalam SAP Ariba Sourcing, anda boleh pilih sama ada kontrak atau pesanan belian perlu dicipta untuk sebut harga dipilih.
Permintaan Sumber Dalaman (RQ):
Anda cipta permintaan harga dalam SAP S/4HANA dan hantar ia secara langsung ke pembekal anda melalui e-mel atau sebagai versi bercetak oleh mel.
Apabila anda terima sebut harga pembekal, anda boleh cipta ia secara manual dalam SAP S/4HANA.
Langkau Perubahan Tahap Pemeriksaan
Tunjukkan bahawa sistem tidak mencipta tahap kualiti
Jika penunjuk ditetapkan, sistem tidak mencipta tahap kualiti untuk ciri pemeriksaan yang diumpukkan dengan tatacara pensampelan, dan tiada perubahan tahap pemeriksaan dilaksanakan.
Jika penunjuk ditetapkan, keterukan pemeriksaan untuk penentuan sampel ciri ini diambil daripada tatacara pensampelannya sendiri.
Anda boleh mengelakkan langkauan ciri pemeriksaan dengan:
Berikan ciri pemeriksaan pemberatan ciri yang sepadan
Tidak membenarkan langkauan dalam data persediaan pemeriksaan untuk bahan
Edit, Simpan dan Aktifkan
Edit sistem komunikasi dan aktifkannya dengan menyimpannya.
Setelah anda membuat semua entri untuk sistem komunikasi, anda akan mempunyai pilihan berikut:
Kembali ke paparan keseluruhan sistem komunikasi dengan menyimpan sistem komunikasi.
Sistem komunikasi anda disimpan sebagai draf yang tersedia pada paparan keseluruhan sistem komunikasi.
Anda boleh mencari versi draf sistem komunikasi dalam jadual paparan keseluruhan dan membuka sistem untuk pengeditan selanjutnya dari sana.
Jika anda telah mengedit sistem komunikasi aktif, versi drafnya akan dipaparkan sebagai tambahan kepada versi aktif sistem.
Simpan sistem komunikasi.
Ia secara automatik akan mengaktifkannya setelah sistem komunikasi disimpan.
Ia tersedia sebagai sistem komunikasi aktif pada paparan keseluruhan sistem komunikasi.
Anda boleh membuka sistem untuk pengeditan selanjutnya dari sana.
Jika anda telah mengedit sistem komunikasi aktif, versi draf akan hilang daripada paparan keseluruhan sistem komunikasi dan versi aktif akan dikemas kini dengan perubahan yang anda lakukan.
Penggunaan dalam Kumpulan Tetapan yang Serasi
Membenarkan anda untuk gunakan hierarki baharu atau disemak dalam kumpulan.
Apabila mencipta dan mengedit hierarki, anda boleh pilih Gunakan dalam Kumpulan Tetapan yang Serasi.
Penggunaan hierarki pusat kos dalam kumpulan tetapan yang serasi memudahkan anda memperuntukkan dengan mengagregat ia ke dalam peruntukan pusat berdasarkan pada jurnal sejagat.
Sila ambil perhatian bahawa anda boleh pilih untuk menggunakan atau tidak hierarki dalam kumpulan tetapan yang serasi semasa mencipta dan mengedit.
Pilihan ini tidak tersedia semasa anda menyalin hierarki.
Setelah anda menyalin hierarki, anda kemudian boleh masukkan mod edit untuk memilih sama ada anda ingin menggunakan hierarki dalam kumpulan tetapan yang serasi.
Sila ambil perhatian bahawa semasa anda menyimpan hierarki diedit, sistem menyemak sama ada perihalan hierarki melebihi 15 aksara.
Jika demikian, ia mendorong anda untuk edit perihalan hierarki untuk padankan dengan had 15 aksara untuk perihalan.
Sila ambil perhatian juga bahawa tetapan lalai untuk hierarki baharu adalah untuk digunakan dalam kumpulan tetapan yang serasi.
Jika anda tidak ingin lakukan demikian, anda harus nyahpilih pilihan ini.
Pindahan Umpukan Peruntukan
Jadikan umpukan sedia ada tersedia dalam pengurusan sumber.
Pindahkan umpukan sedia ada mengikut kriteria pemilihan anda.
Anda hanya boleh memindahkan umpukan peruntukan untuk penggunaan berikut:
Projek berkaitan tidak diedit apabila jalanan kerja dimulakan.
Maklumat ketersediaan harian wujud untuk sumber diperuntukkan.
Maklumat ini mestilah tersedia untuk keseluruhan tempoh umpukan (iaitu, tempoh masa di antara mula pakej kerja dan akhir pakej kerja).
Pekerjaan sumber mestilah aktif untuk keseluruhan tempoh umpukan.
Tetapan Semula Data Ketersediaan
Tetapkan semula komitmen kuantiti bahan tersedia untuk keperluan bersandar.
Pilih pilihan ini, jika anda mahu menetapkan semula komitmen jumlah bahan yang tersedia untuk keperluan bersandar sebelum semakan.
Tetapan semula data ketersediaan mempunyai kesan bahawa data berikut dipadam:
Kuantiti disahkan dalam komponen bahan
Penunjuk bahagian hilang (hanya pesanan pengeluaran)
Tarikh pengesahan keseluruhan dalam pengepala pesanan
Kuantiti disahkan dalam pengepala pesanan
Tetapan semula data ketersediaan juga menetapkan semula status sistem "FMAT" (ketersediaan bahan hilang) dalam pesanan pengeluaran.
Bidang Kerja Permintaan Luaran
Bidang kerja permintaan luaran bidang kerja adalah untuk organisasi yang memerlukan anda melengkapkan borang elektronik sebagai sebahagian daripada proses kelulusan untuk latihan luaran: latihan di luar organisasi anda.
Sebagai contoh, pelanggan Persekutuan Amerika Syarikat menggunakan borang yang dipanggil "SF-182" untuk meminta latihan luaran.
memberikan bidang kerja untuk permintaan luaran diHalaman Utama Pautan Permintaan Luaran..
Dalam bidang kerja, anda boleh:
Lengkapkan dan serahkan borang dalam talian yang meminta kursus luaran.
Papar borang yang telah dihantar kepada anda untuk kelulusan dan kemudian luluskan atau nafikan permintaan dengan sebab
Aliran Kerja Permintaan Luaran (SF-182)
Frasa "Permintaan Luaran" boleh mengelirukan.
Aliran kerja menggunakan frasa walaupun selepas permintaan diluluskan.
Permintaan boleh mempunyai berbilang frasa, termasuk diluluskan.
Melengkapkan Borang Permintaan Luaran
Pergi ke Halaman Utama Pautan Permintaan Luaran.
Untuk membuka borang kosong, klik Permintaan Baru.
Untuk menggunakan semula borang, ubah medan borang yang perlu diubah sahaja, klik Salin Permintaan bersebelahan borang yang anda ingin salin.
Selepas anda melengkapkan borang, ikuti bestari aliran kerja bagi menghantar borang untuk kelulusan.
Jika anda perlukan bantuan untuk melengkapkan borang, klik pautan Arahan untuk membuka arahan pada borang tertentu.
Meluluskan atau Menafikan Permintaan
Apabila anda mempunyai permintaan menunggu kelulusan, anda melihat amaran:
Halaman Utama Tugasan Pembelajaran Saya Anda mempunyai permintaan menunggu kelulusan
Anda boleh sama ada klik amaran atau klik Halaman Utama Pautan Kelulusan untuk membuka bidang kerja kelulusan.
Anda menggunakan bidang kerja kelulusan yang sama sama ada anda meluluskan permintaan luaran, meluluskan pengesahan permintaan luaran, atau meluluskan beberapa jenis permintaan lain, seperti latihan dalaman.
Dalam bidang kerja kelulusan, pergi ke Latihan Latihan Luaran dan ikuti bestari aliran kerja untuk meluluskan atau menafikan permintaan.
Organisasi anda mungkin mempunyai berbilang langkah dalam aliran kerja, tetapi pada akhir proses, permintaan muncul dalam senarai tugasan pengguna dan bidang kerja permintaan luaran pengguna.
Mengenal Pasti Latihan Luaran Akan Datang
Untuk kenal pasti acara latihan luaran akan datang, pergi ke Halaman Utama Tugasan Saya Tapis, dan kemudian pilih Permintaan Luaran daripada senarai jenis kursus.
Mengesahkan Permintaan Luaran
Selepas anda menghadiri acara, anda mengesahkan bahawa anda telah menghadirinya.
Untuk mengesahkan kehadiran anda, pergi ke Halaman Utama Pautan Permintaan Luaran.
Cari permintaan yang sepadan dengan acara anda dan klik Sahkan.
Ikuti bestari aliran kerja untuk menyelesaikan pengesahan.
Selepas anda sahkan kehadiran anda, acara muncul dalam sejarah anda.
Dalam banyak kes, anda boleh sahkan kehadiran anda sendiri.
Dalam sesetengah kes, pentadbir mesti sahkan kehadiran anda.
Kod Pengeposan
Kod yang menerangkan cara transaksi diposkan.
Tentukan kod pengeposan yang menerangkan jenis transaksi yang dimasukkan dalam item baris.
Untuk setiap kod pengeposan, anda menentukan sifat yang mengawal entri item baris dan tercatat dalam item baris itu sendiri.
Sifat utama berikut diterbitkan daripada kod pengeposan:
Jenis akaun
Peruntukan ke debit atau kredit
Spesifikasi mungkin atau perlu yang akan dimasukkan dalam item baris
Permintaan Belian Tidak Diluluskan
Paparkan permintaan belian yang belum lagi diluluskan untuk bahan bukan stok
Kad paparkan bilangan permintaan belian yang belum lagi dikeluarkan untuk bahan bukan stok yang diperlukan sebagai alat ganti dalam pesanan penyelenggaraan.
Bahan bukan stok diperlukan untuk kerja penyelenggaraan dalam tempoh rujukan yang telah anda pilih.
Permintaan belian yang belum lagi dikeluarkan dipilih sama ada dengan menggunakan tarikh keperluan atau tarikh mula diperlukan.
Jika bahan bukan stok diminta semasa pesanan penyelenggaraan diproses dan permintaan belian dijana secara automatik, tarikh keperluan bahan yang telah dimasukkan dalam simpanan akan digunakan sebagai pemilihan.
Jika bahan diminta secara langsung dan diumpukkan kepada pesanan penyelenggaraan, tarikh mula pesanan yang diperlukan akan digunakan sebagai pemilihan.
Jika anda ingin paparkan semua permintaan belian yang belum lagi dikeluarkan dengan itemnya dalam senarai, klik pada kad.
Daripada senarai, anda boleh cabangkan ke permintaan belian dan pesanan penyelenggaraan.
Jika anda klik pada bahagian sebelah kanan kad, anda boleh melihat item permintaan belian terbuka dengan maklumat yang lebih penting dipaparkan pada kad dalam karusel.
Pada kad untuk item permintaan belian individu dalam karusel, anda juga boleh cabangkan ke pesanan penyelenggaraan atau pesanan belian dan paparkannya.
Cipta Jujukan
Cipta jujukan baru.
Anda boleh gunakan butang Cipta Jujukan untuk picu penciptaan jujukan baru.
Medan Nama Jujukan adalah wajib dan diserlahkan dengan sewajarnya.
Asas jujukan anda adalah atribut isihan.
Atribut isihan ditakrifkan pada Pilih:
Bantuan nilai Atribut Isihan yang anda boleh capai daripada medan Atribut Isihan dengan mengklik ikon atau F4.
Memilih Pergi pada Pilih:
Bantuan nilai Atribut Isihan menyenaraikan semua atribut isihan yang mungkin.
Jika anda ingin senaraikan dan mengutamakan keperluan oleh pengguna, pilih item PIHAK PEMBELI.
Butiran
Anda boleh melihat butiran medan.
Bergantung pada jenis medan, anda juga boleh melihat butiran komponen medan sepadan.
Jika boleh digunakan, paparan butiran bagi jenis medan amaun dengan mata wang, kuantiti dengan unit, perkaitan dengan objek perniagaan dan senarai kod memaparkan maklumat teknikal tentang medan dan juga komponen medan sepadan seperti perihalan, kod atau medan kod.
Maklumat untuk amaun dengan mata wang, kuantiti dengan unit, perkaitan dengan objek perniagaan dan senarai kod dan komponen medan dipaparkan dalam urutan berikut:
Amun dengan Mata Wang:
Amaun, Kod, Perihalan
Kuantiti dengan Unit:
Kuantiti, Kod, Perihalan
Perkaitan dengan Objek Perniagaan:
Medan Kod, Perihalan
Senarai Kod:
Kod, Perihalan
Butiran Penghantaran
Membolehkan anda untuk tentukan butiran lanjutan yang berkaitan untuk penghantaran.
Pada masa itu anda mungkin terima toleransi tertentu untuk penghantaran anda.
Ini bermakna bahawa anda boleh tentukan jumlah lebih banyak atau kurang yang anda akan terima dalam peratus.
Jika anda pilih kotak semak Unltd Overdelivery, sebarang kuantiti yang melebihi kuantiti dipesan boleh diterima.
Medan Commodity Code dan Intrastat Srvc.
Code adalah berkaitan untuk pelaporan Intrastat, medan Intrastat Srvc.
Code adalah berkaitan untuk pelanggan Itali sahaja.
Aktiviti Pengguna
Pilih jika ingin jejaki aktiviti dan aplikasi terbaru yang digunakan atau kosongkan sejarah anda.
Tentukan sama ada anda ingin menjejaki aktiviti pengguna anda.
Tetapkan Jejak aktiviti terbaru saya dan aplikasi yang kerap digunakan kepada TIDAK untuk memberhentikan penjejakan aktiviti pengguna.
Kemudian, entri Aktiviti Terbaru dan Kerap Digunakan dikeluarkan daripada Menu Tindakan Pengguna.
Klik Kosongkan untuk memadam aktiviti pengguna anda.
Jika Jejak aktiviti terbaru saya dan aplikasi yang kerap digunakan ditetapkan kepada YA, senarai Aktiviti Terbaru dan Kerap Digunakan dikosongkan tetapi sistem terus menjejaki aktiviti anda dan memaparkan item baharu dalam senarai aktiviti pengguna.
Untuk maklumat lanjut, lihat dan
Nilai Lalai
Pratetapan tempoh masa dan bilangan jam kini adalah berdasarkan tetapan penapis anda.
Jika anda ubah tempoh masa dan bilangan jam diperlukan semasa mencari sumber yang sesuai, aplikasi mencadangkan tetapan penapis anda sebagai lalai.
Untuk peraturan pengagihan Jumlah Jam, kedua-dua tempoh masa dan bilangan jam diperlukan adalah pratetap.
Untuk peraturan Jam Harian, pratetapan tempoh masa adalah berdasarkan tetapan penapis anda.
Jika anda tidak mengubah tetapan penapis lalai semasa mencari sumber sesuai, pratetapan tempoh masa umpukan adalah pada tarikh mula dan akhir permintaan sumber.
Untuk peraturan pengagihan Jumlah Jam, pratetapan bilangan jam untuk diagihkan adalah berdasarkan (baki) jam diminta.
Jenis CVA/DVA
Jenis pelarasan nilai kredit dan debit
Takrifkan tetapan yang diperlukan untuk pengiraan pelarasan nilai kredit dan debit.
Dengan templat Kira NPV dengan CVA dan DVA, anda boleh lakukan perkara berikut:
Tentukan jenis pelarasan nilai kredit dan debit yang anda mahu gunakan untuk pengiraan bawah Parameter Penilaian.
Peroleh jenis CVA/DVA daripada tetapan dalam Pengurusan Kedudukan dengan tetapan penunjuk Penerbitan Automatik Parameter Penilaian.
Setelah menetapkan penunjuk ini, anda tidak perlu lagi tentukan Jenis CVA/DVA, Jenis Penilaian, atau Mata Wang bawah Parameter Penilaian.
Jalankan fungsi ini tanpa pengiraan CAV/DVA
Dalam kes ini, anda tidak tentukan penunjuk Jenis CVA/DVA dan penunjuk Penerbitan Automatik Parameter Penilaian.
Sistem melaksanakan pengiraan tanpa CVA dan CVA, dan menetapkan sistem kepada sifar.
Perbezaan daripada yang Diumpukkan
Menunjukkan sama ada item kecairan yang dicadangkan sistem adalah berbeza daripada item kecairan yang diumpukkan secara manual.
Anda mempunyai dua pilihan untuk medan ini.
Jika anda memilih ya, item kecairan yang berbeza akan dipaparkan.
Jika anda memilih tidak, item kecairan yang sama akan dipaparkan.
Jika tiada pilihan, semua item kecairan dipaparkan tanpa mengira perbezaan.
Secara lalai, Ya dipilih untuk medan ini, iaitu aliran tunai bagi item kecairan sebenar yang berbeza daripada dicadangkan oleh perkhidmatan pembelajaran mesin dipaparkan.
Individu untuk Dihubungi
Anda kini boleh selenggara atau papar data bagi individu untuk dihubungi pada pembekal.
Anda boleh selenggara atau papar data bagi individu untuk dihubungi pada pembekal, pengenal pasti atau nama Jurujual, nombor Telefon jurujual, dan data rujukan bagi individu untuk dihubungi.
Dalam medan Jurujual, anda boleh memasukkan teks bebas sehingga 30 aksara.
Sebagai rujukan, anda boleh memasukkan akronim sehingga 12 aksara bagi mengenal pasti individu bertanggungjawab untuk pesanan belian dalam syarikat pembekal anda (Rujukan Anda) dan syarikat anda sendiri (Rujukan Kami).
Anda boleh gunakan data yang diselenggara bagi individu untuk dihubungi sebagai penapis untuk senarai pesanan belian yang dipaparkan dalam senarai objek aplikasi Uruskan Pesanan Belian.
Data bagi individu untuk dihubungi disimpan dengan pesanan belian, bukan data induk pembekal.
Tika
Papar kiraan untuk aktiviti terakhir yang berkaitan dengan tika situasi.
Anda boleh menggunakan kiraan untuk mengenal pasti aktiviti terakhir untuk tika situasi (nilai:
1).
Pada bahagian bawah lajur, anda juga boleh melihat jumlah bilangan tika yang telah berlaku.
ID jenis situasi digunakan dengan lalai untuk kumpulan tika situasi dalam jadual ini.
Untuk melihat jumlah bilangan tika, keluarkan kumpulan ini di bawah Tetapan Kumpulan Keluar Penciptaan Kumpulan.
Penetapan Strategi
Anda boleh mengawal cara pesanan boleh dijadualkan.
Anda boleh memilih salah satu daripada Mod Perancangan berikut:
Baldi- Paparkan paparan harian jangka masa kapasiti dalam format jadual.
Berikut ialah jumlah bagi semua syif tidak termasuk rehat.
Jujukan- Paparkan paparan harian jangka masa kapasiti dalam format masa berterusan.
Arah merujuk kepada arah penjadualan yang menentukan tarikh yang anda pilih dalam penapis Horizon:
Ke Hadapan:
Pertimbangkan tarikh mula pesanan semasa penjadualannya.
Ke Belakang:
Pertimbangkan tarikh akhir pesanan semasa penjadualannya.
Anda juga boleh mengawal Strategi Penjadualan (terhingga atau tidak terhingga) bagi pesanan dan operasi.
Kad Tempoh Beban Berkurangan
Paparkan data untuk tempoh peruntukan yang penggunaan peruntukan adalah di bawah 20%.
Kad Tempoh Beban Berkurangan memaparkan data untuk tempoh yang asalnya kuantiti diperuntukkan untuk objek peruntukan produk telah digunakan sehingga 20%.
Data yang dipaparkan dalam kad diisih mengikut muatan, bermaksud objek peruntukan produk dengan penggunaan kuantiti yang dirancang paling rendah disenaraikan terlebih dahulu.
Anda boleh menapis data yang dipaparkan dengan peningkatan sebanyak 5% dalam juntai bawah takrifan muatan.
Dari kad Tempoh Beban Berkurangan, anda boleh menavigasikan ke aplikasi Pantau Tempoh Peruntukan Produk yang anda boleh paparkan kuantiti dan data muatan untuk tempoh peruntukan, objek peruntukan produk dan gabungan nilai ciri yang memenuhi kriteria penapis anda.
Mengklik tarikh mula tempoh atau baris dalam kad Tempoh Beban Berkurangan membawa anda secara langsung ke skrin Tempoh Peruntukan yang memperincikan data tentang tempoh dan item pesanan yang berkaitan dengan data kuantiti untuk tempoh yang dipilih.
Status Kos
Tunjukkan sama ada kos piawai pesanan atau kos rancangan tersedia.
Lajur ini menunjukkan anda secepat mungkin benar atau tidak kos piawai pesanan atau kos rancangan tersedia untuk pesanan.
Anda akan melihat sama ada Status Kos Piawai atau Status Kos Rancangan, bergantung pada Kategori Rancangan yang anda pilih.
Kos piawai pesanan berdasarkan pada kos piawai bahan.
Jika kos piawai bahan tidak tersedia atas alasan tertentu, kos piawai pesanan dan kos sasaran akan menunjukkan nilai sifar dalam jadual.
Persamaan adalah betul untuk kos rancangan, dan anda juga akan melihat nilai sifar jika kos rancangan tidak tersedia.
Anda boleh menggunakan penapis Status Anggaran Kos untuk mengenal pasti pesanan yang memerlukan perhatian dan mengelakkan masa terluang pada pesanan perbandingan kos yang tidak tersedia.
Makluman Bayaran
Anda boleh menyenaraikan bayaran daripada pelanggan atau vendor.
Makluman bayaran membenarkan pelanggan atau vendor untuk menyenaraikan bayaran mereka dan menunjukkan invois yang telah dibayar penuh, sebahagiannya dibayar dan yang masih belum dibayar oleh mereka.
Perkara ini sangat berguna apabila berhadapan dengan pelbagai transaksi berbeza dengan pelanggan atau vendor yang sama.
Antara sebab untuk bayaran separa atau tiada bayaran termasuk kerosakan, pertikaian terhadap rebat atau diskaun, kelewatan penghantaran atau isu penghantaran lain atau isu lain yang mungkin memerlukan hubungan antara pelanggan dan vendor.
Jika makluman bayaran tidak dimasukkan terlebih dahulu ke dalam sistem, tapi sebaliknya digunakan untuk penjelasan item penyata bank semasa, ia akan dimuat naik sebagai lampiran untuk penyimpanan rekod yang lebih lengkap.
Contohnya, pelanggan menyerahkan bayaran sebanyak $14,400 untuk lima invois, $3,000 setiap satu.
Maklumat bayaran yang disertakan menjelaskan bahawa telah menyerahkan bayaran penuh untuk empat invois (berjumlah $12,000) tetapi dipotong 20% daripada invois akhir (membayar $2,400) kerana barangan tertunda dan rosak semasa penghantaran.
Makluman bayaran membolehkan anda untuk menutup empat transaksi yang dibayar penuh semasa merekod invois akhir dan terus menjelaskannya sekiranya perlu.
Kumpulan Peraturan
Kumpulan peraturan mengandungi set peraturan berkaitan.
Hasil pengesahan yang dipaparkan dalam aplikai Uruskan Tugas Pengesahan Data mengikuti hierarki kumpulan sama yang ditakrifkan di sini.
Dalam bahagian ini, anda boleh:
Cipta kumpulan peraturan
Umpukkan peraturan berbilang ke setiap kumpulan
Seret dan lepas peraturan untuk mengubah jujukan atau umpukan kumpulannya
Bawah baris pengepala Jumlah Pengesahan, anda hanya boleh tambah satu aras hierarki kemudian masukkan peraturan dalam setiap kumpulan, anda tidak boleh tambah kumpulan bawah kumpulan lain.
Lihat gambar GIF bergerak untuk panduan langkah demi langkah:
Pemilihan Berbilang Sumber
Anda kini boleh mencipta umpukan berbilang secara serentak.
Anda kini boleh memilih sumber berbilang dan umpukannya ke permintaan secara serentak.
Ini merupakan prasyarat:
Sumber dipilih merupakan organisasi yang sama.
Sumber dipilih belum lagi diumpukkan ke permintaan.
Bar menegak biru menunjukkan individu yang telah diumpukkan ke permintaan.
Permintaan Belian Tidak Ditukarkan kepada Pesanan Belian
Paparkan permintaan belian diluluskan yang belum lagi ditukarkan ke pesanan belian
Kad memaparkan semua permintaan belian yang telah diluluskan untuk pesanan penyelenggaraan tetapi untuk mana-mana pesanan bukan belian telah dijanakan.
Sistem memilih permintaan belian dengan mana-mana bahan bukan stok yang telah anda minta sebagai alat ganti untuk penyelenggaraan loji.
Komponen diminta diperlukan untuk kerja penyelenggaraan dalam tempoh rujukan yang telah anda pilih.
Jika bahan bukan stok diminta semasa pesanan penyelenggaraan diproses dan permintaan belian dijana secara automatik, tarikh keperluan bahan yang telah dimasukkan dalam simpanan akan digunakan sebagai pemilihan.
Jika bahan diminta secara langsung dan diumpukkan kepada pesanan penyelenggaraan, tarikh mula pesanan yang diperlukan akan digunakan sebagai pemilihan.
Jika anda ingin paparkan semua permintaan belian yang belum lagi ditukarkan ke pesanan belian dengan itemnya dalam senarai, klik pada kad.
Daripada senarai, anda boleh cabangkan ke permintaan belian dan pesanan penyelenggaraan.
Jika anda klik pada bahagian sebelah kanan kad, anda boleh melihat item permintaan belian tidak ditukarkan dengan maklumat yang lebih penting dipaparkan pada kad dalam karusel.
Pada kad untuk item permintaan belian individu dalam karusel, anda juga boleh cabangkan ke pesanan penyelenggaraan atau pesanan belian dan paparkannya.
Had Item
Membolehkan anda mencipta item had untuk perkhidmatan atau bahan tidak dirancang.
Anda boleh mencipta item had untuk perkhidmatan atau bahan tidak dirancang, iaitu perkhidmatan atau bahan yang tidak boleh ditentukan dalam butiran pada masa pemesanan.
Dalam kedua-dua kes, anda mentakrifkan nilai dijangka, keseluruhan had dan tempoh masa:
Had untuk bahan:
Pilih Kumpulan Jenis Produk Bahan (1)
Dalam kes item had untuk bahan, penerimaan barangan tidak mungkin.
Invois diposkan secara langsung dengan rujukan kepada pesanan belian dengan syarat tidak melebihi had nilai ditentukan.
Had untuk perkhidmatan lean:
Pilih Kumpulan Jenis Produk Perkhidmatan (2)
Jika item had untuk perkhidmatan, lembaran entri perkhidmatan boleh dicipta jika diperlukan.
Ia juga mungkin untuk mengeposkan invois dengan serta-merta.
Jika anda merekodkan perkhidmatan yang dijalankan, harga serta kuantitinya menggunakan aplikasi Uruskan Lembaran Entri Perkhidmatan - Perkhidmatan Lean, sistem memaparkan Nilai Dijangka bagi item had dalam lembaran entri perkhidmatan dan melaporkan ralat jika amaun yang dinyatakan melebihi Had Keseluruhan.
Status Pengusiaan
Papar status objek pengusiaan data dipilih.
Objek pengusiaan data boleh mempunyai status berikut:
Didayakan- Pengusiaan Dimulakan:
Status ini menunjukkan bahawa objek adalah aktif dan jalanan pengusiaan berjadual untuk objek pengusiaan data yang dipilih.
Didayakan - Pengusiaan Tidak Dimulakan:
Status ini menunjukkan bahawa objek akan diaktifkan secara automatik ketika jalanan pengusiaan data berjadual seterusnya untuk objek ini dan jalanan pengusiaan tidak berjadual bagi objek pengusiaan data yang dipilih.
Tidak Didayakan:
Menunjukkan bahawa objek pengusiaan data dipilih adalah tidak aktif dan tidak boleh digunakan dalam jalanan pengusiaan.
Pemeriksa
Tunjukkan isu untuk bahan tahap teratas.
Pemeriksa mengesan isu untuk setiap bahan tahap teratas setiap tempoh masa.
Dalam jadual, ia dipaparkan dalam sel berwarna.
Klik sel berwarna untuk melihat butiran lanjut mengenai isu dan kategorinya dalam panel Isu.
Dari bahan tahap teratas, anda boleh klik Simulasi Bahan Berbilang Tahap untuk navigasi ke paparan bil bahan berstruktur dan buat simulasi pada tahap komponen.
Contohnya, anda boleh mengubah sumber bekalan atau menghasilkan komponen terlebih dahulu.
Pengeditan Prom
Ubah nilai pemboleh ubah untuk keseluruhan tab atau kumpulan carta.
Untuk mendapatkan data pada tab, anda perlu mentakrifkan pemboleh ubah bagi tab.
Mengikut tetapan bagi pemboleh ubah, data yang sepadan dikira dan dipaparkan.
Aplikasi dihantar dengan tetapan lalai bagi pemboleh ubah.
Pemboleh ubah berbeza bagi sumber data berbeza yang dipanggil untuk carta tab.
Tab dan Parameter Input untuk Sumber Data
Tab
Parameter Input untuk Sumber Data
Kecairan
Pengurusan Tunai
Keberhutangan
Jaminan Bank
Risiko Kontraktor
Paparan Keseluruhan Pasaran
Anda juga boleh memilih Edit Prom Carta, jika anda hanya ingin mengubah pemboleh ubah bagi carta tertentu.
Pada tab tertentu, pilih Edit Prom pada sudut kanan.
Pilih Parameter Input untuk Sumber Data yang berkaitan bagi tab (kumpulan carta).
Pada timbul Tetapkan Pemboleh Ubah untuk …., anda boleh memadam ahli pratakrif dan memasukkan nilai pilihan anda menggunakan bantuan nilai.
Jika anda telah membuat semua perubahan yang diperlukan terhadap nilai pemboleh ubah, pilih Tetapkan.
Salin Ciri Model/Rujukan
Tentukan cara ciri pemeriksaan induk boleh digunakan.
Anda boleh gunakan ciri pemeriksaan induk dalam senarai tugas atau spesifikasi bahan.
Jika ciri pemeriksaan induk dikenal pasti sebagai Model Salinan Lengkap atau Model Salinan Rujukan, sistem semak sama ada ciri pemeriksaan induk, bersandar penunjuk kawalan, diselenggara sepenuhnya.
Pilihan berikut tersedia:
Ciri Rujukan
Jika anda guna ciri pemeriksaan induk dalam senarai tugas atau spesifikasi bahan, rujukan yang pertama dicipta untuk ciri ini.
Walau bagaimanapun, anda boleh batalkan rujukan ini atau ubah data secara individu (contohnya, toleransi).
Model Salinan Lengkap
Jika anda guna ciri pemeriksaan induk dalam senarai tugas atau spesifikasi bahan, rujukan untuk ciri ini dibatalkan.
Oleh itu, anda boleh mengubah data dengan segera (contohnya, toleransi)
Anda kemudian boleh menggunakan ciri pemeriksaan induk ini sebagai model salinan.
Model Salinan Tidak Lengkap
Jika anda menggunakan ciri pemeriksaan dalam senarai tugas, ini hanya boleh digunakan sebagai model salinan.
Jenis ciri pemeriksaan induk ini tidak boleh digunakan dalam spesifikasi bahan.
Takrifkan Corak Perulangan
Takrifkan corak perulangan kerja.
Dengan mengklik pautan ini, anda boleh meneliti pilihan penjadualan anda seperti perulangan kerja.
Dalam dialog Maklumat berjadual yang muncul apabila anda telah mengklik pautan, anda boleh:
Takrifkan zon waktu untuk entri tarikh dan masa anda
Takrifkan corak perulangan seperti harian atau mingguan
Untuk minit, masukkan sekurang-kurangnya 30 minit.
Takrifkan jika kerja sepatutnya hanya dijalankan pada hari bekerja.
Bagi perkara ini, anda perlu pilih kalendar tertentu.
Templat Kerja
Pilih templat kerja untuk mencipta data rujukan untuk simulasi pMRP.
Pilih salah satu templat berikut:
Ciptaan Data pMRP melalui Bahan Tahap Atas
Gunakan templat ini untuk menjanakan data rujukan sahaja berdasarkan data bahan yang dimasukkan di sini.
Ciptaan Data pMRP melalui Pusat Kerja
Gunakan templat ini untuk menjanakan data rujukan berdasarkan data pusat kerja.
Dalam kes semua bahan ini, yang berkaitan dengan pusat kerja ini dipertimbangkan.
Status Sistem 1
Status pesanan yang anda ingin jadualkan kerja.
Tentukan status pesanan yang anda ingin jadualkan kerja.
Pilih salah satu daripada
I0002 Dikeluarkan ()
I0045 Selesai secara Teknikal()
I0009 Disahkan ()
I0012 Dihantar ()
I0042 Dikeluarkan secara Separa ()
Anda boleh menentukan status kedua dalam medan Status Sistem 2.
Anda juga boleh kecualikan pesanan dengan status tertentu dalam medan ini dengan memilih kotak semak Pengecualian Status 1.
Dialog Pengeditan Diubah
Dialog untuk mengedit fungsi perniagaan telah diubah.
Apabila anda mengedit fungsi perniagaan, anda akan menyedari perubahan berikut:
Data pentadbiran sistem telah dialihkan ke bahagian atas dialog.
ID fungsi perniagaan telah dialihkan ke atas perihalan.
Jika anda membuka fungsi perniagaan aktif, anda akan menyedari perubahan berikut:
Sekatan:
Sekatan boleh dipaparkan pada skrin berbeza.
Anda boleh melihat medan bagi sekatan yang telah ditetapkan.
Katalog Perniagaan Diumpukkan:
Butiran sekatan dipaparkan pada skrin berasingan.
Pengeditan fungsi perniagaan:
Jika fungsi perniagaan aktif perlu diedit, fungsi perniagaan perlu dibuka terlebih dahulu dan mod edit perlu dimasuki secara manual dengan mengklik Edit.
Versi draf fungsi perniagaan dicipta bagi pengeditan yang berlaku.
Fungsi perniagaan aktif kekal.
Setelah perubahan disimpan, ia akan ditulis dalam fungsi perniagaan aktif dan versi draf akan hilang.
Jika dialog untuk pengeditan fungsi perniagaan dibiarkan tanpa menyimpan fungsi perniagaan, fungsi perniagaan aktif serta versi draf fungsi perniagaan akan tersedia dalam paparan keseluruhan fungsi perniagaan.
Dalam mod edit, anda akan menyedari perubahan berikut:
Butang Selenggara Sekatan telah dialihkan ke bahagian atas dialog.
Anda boleh selenggara sekatan untuk jenis capaian berikut:
Tulis, Baca, Bantuan Nilai
Baca, Bantuan Nilai
Bantuan Nilai
Maklumat Pentadbir
Bahagian pengepala bagi jenis situasi.
Masukkan ID dan nama untuk jenis situasi baharu.
Anda boleh mengubah nama templat situasi disalin yang dicadangkan dalam medan nama mengikut lalai.
Mulakan ID jenis situasi anda dengan Y atau Z dan pastikan ia tidak mengandungi aksara khas.
Dalam Jujukan Paparan, anda boleh mentakrifkan jujukan dalam situasi dipaparkan:
Jika tika situasi berbilang wujud untuk objek perniagaan, ia dipaparkan pada halaman objek mengikut nilai untuk jujukan paparan.
Nombor Akaun Bank
Menggunakan medan aras perancangan dalam rekod induk, sistem menguntukkan akaun G/L kepada Pengurusan Tunai dan Ramalan.
Hanya bayaran yang berkaitan akaun G/L penting untuk Pengurusan Tunai dan Ramalan (kedudukan tunai).
Perkara ini biasanya adalah yang berikut:
Akaun bank
Akaun penjelasan bank (contohnya, semakan keluar dan pindahan keluar)
Akaun tunai
Makluman Bayaran
Membenarkan penyenaraian bayaran dan berguna apabila berhadapan dengan pelbagai transaksi berbeza dengan pelanggan atau vendor yang sama.
Makluman bayaran membenarkan pelanggan atau vendor untuk menyenaraikan bayaran mereka dan menunjukkan invois yang telah dibayar penuh, sebahagiannya dibayar dan yang masih belum dibayar oleh mereka.
Perkara ini sangat berguna apabila berhadapan dengan pelbagai transaksi berbeza dengan pelanggan atau vendor yang sama.
Antara sebab untuk bayaran separa atau tiada bayaran termasuk kerosakan, pertikaian terhadap rebat atau diskaun, kelewatan penghantaran atau isu penghantaran lain atau isu lain yang mungkin memerlukan hubungan antara pelanggan dan vendor.
Jika makluman bayaran tidak dimasukkan terlebih dahulu ke dalam sistem, tapi sebaliknya digunakan untuk penjelasan item penyata bank semasa, ia akan dimuat naik sebagai lampiran untuk penyimpanan rekod yang lebih lengkap.
Contohnya, pelanggan menyerahkan bayaran sebanyak $14,400 untuk lima invois, $3,000 setiap satu.
Maklumat bayaran yang disertakan menjelaskan bahawa telah menyerahkan bayaran penuh untuk empat invois (berjumlah $12,000) tetapi dipotong 20% daripada invois akhir (membayar $2,400) kerana barangan tertunda dan rosak semasa penghantaran.
Makluman bayaran membolehkan anda untuk menutup empat transaksi yang dibayar penuh semasa merekod invois akhir dan terus menjelaskannya sekiranya perlu.
Pemberitahuan
Terangkan situasi perniagaan yang telah berlaku pada launchpad SAP Fiori.
Anda boleh memasukkan teks pemberitahuan yang menerangkan situasi perniagaan kepada pengguna akhir.
Apabila tika situasi berdasarkan jenis situasi berlaku, sistem memaparkan pemberitahuan ini pada launchpad SAP Fiori.
Teks Selamat hanya dihantar melalui saluran komunikasi yang selamat seperti launchpad SAP Fiori.
Untuk menyampaikan maklumat sensitif seperti ID, nilai objek perniagaan dan sebagainya, gunakan pemboleh ubah yang tersedia.
Anda boleh memilihnya daripada senarai sebaik sahaja anda memasukkan tanda kurungan dakap ({).
Satu atau beberapa invois belum bayar untuk amaun yang sepadan mungkin telah dilangkau dalam makluman bayaran {PAYMENTADVICE}.
{PAYMENTADVICE} = Nombor Makluman Bayaran
Pratonton Pemberitahuan menunjukkan semua perubahan yang anda lakukan pada teks selamat dalam masa nyata.
Teks Umum dihantar melalui saluran komunikasi am seperti telefon mudah alih atau tablet.
Satu atau beberapa invois belum bayar untuk amaun yang sepadan mungkin telah dilangkau dalam makluman bayaran.
Perihalan Pendek yang dipaparkan dalam teks selamat atau umum untuk pemberitahuan digunakan daripada mesej situasi in-app dan tidak boleh diedit secara berasingan untuk pemberitahuan.
Pemberitahuan Agregat:
Di sini anda boleh takrifkan sama ada pemberitahuan yang akan dihantar diagregatkan atau dipisahkan untuk setiap tika situasi.
Hantar Semula Pemberitahuan:
Di sini anda boleh takrifkan sama ada pemberitahuan dihantar semula apabila tika situasi terbuka dikemas kini.
Penggantian Ahli Pasukan
Cari dan gantikan ahli
Anda kini boleh mencari dan menggantikan ahli (ID Pekongsi Perniagaan) dan fungsi yang berkaitan dengan ahli lain dalam pasukan.
Contohnya, John merupakan ahli bagi beberapa pasukan dan dia mengendalikan beberapa fungsi dalam pasukan.
Anda boleh menggantikan John dengan Jim dalam setiap pasukan.
Jim kemudiannya akan mempunyai fungsi yang sama dalam pasukan seperti John.
Jika perlu, anda boleh mengumpukkan satu sahaja fungsi ahli dipilih kepada ahli lain dalam pasukan.
Tindakan ini akan mengeluarkan fungsi daripada ahli dipilih.
Anda perlu memilih kategori dan jenis untuk melihat senarai fungsi.
Contohnya, John menjalankan tiga fungsi - pembeli operasi, pentadbir aliran kerja dan pengurusan katalog.
Anda boleh menggantikan John dengan Jim sebagai pentadbir aliran kerja dalam pasukan.
Resolusi Konteks
Tentukan permintaan penyelesaian penapis.
Tentukan permintaan penyelesaian konteks.
Permintaan penyelesaian konteks adalah diperlukan jika konteks diserahkan daripada aplikasi lain, contohnya, konteks Perniagaan Pintar, tidak hanya mengandungi nilai tunggal, tetapi juga pengendali lain.
Permintaan penyelesaian konteks kemudian menyelesaikan konteks ke dalam senarai nilai tunggal.
Ini adalah perlu kerana penapis hanya boleh paparkan nilai tunggal.
Jika anda tidak tentukan permintaan penyelesaian konteks sedangkan ianya merupakan keperluan untuk membolehkan paparan nilai dalam bantuan nilai maka penapis untuk sifat sepadan tidak dipaparkan pada UI.
Sebaliknya, konteks digunakan ke laluan analisis pada latar belakang.
Varian Berkaitan
Senarai varian dalam segmen yang digunakan.
Lajur Varian Berkaitan menyenaraikan varian dalam segmen digunakan.
Dengan mengklik pada nombor dalam lajur Varian Berkaitan, anda boleh:
Papar varian dalam segmen yang digunakan.
Papar strategi pengesahan untuk segmen diumpukkan.
Navigasikan pada aplikasi Konfigurasikan Varian BOP yang membolehkan anda memaparkan dan mengedit tetapan varian.
Ambil perhatian bahawa maklumat yang sama dipaparkan semasa anda menekan butang Tunjukkan Varian Berkaitan pada skrin Perihalan Segmen BOP.
Edit Pengepala
Anda boleh mengubah ID dan nama unit organisasi sedia ada yang sesuai dengan keperluan perniagaan anda.
Untuk mengubah ID dan nama unit organisasi, pilih Edit Pengepala.
Masukkan ID dan nama baharu seperti yang anda perlukan dalam tetingkap timbul.
Perubahan nama akan digunakan dengan serta-merta.
Jika anda ubah ID, kerja latar belakang akan dicipta.
Anda boleh edit pengepala untuk unit Tidak Aktif sahaja.
Pesanan untuk Perancangan
Benarkan paparan keseluruhan bagi pesanan penyelenggaraan yang belum lagi dikeluarkan
Pada kad Pesanan untuk Perancangan, anda boleh analisis dan memantau pesanan penyelenggaraan untuk mana-mana tarikh mula diperlukan dengan tempoh rujukan yang anda takrifkan tetapi ia masih dalam perancangan dan belum lagi dikeluarkan untuk pemprosesan.
Anda boleh gunakan senarai juntai bawah untuk memilih dimensi lanjutan untuk mana-mana nilai yang dipaparkan dalam warna yang berbeza pada carta.
Perkara ini bermaksud bahawa anda boleh paparkan pesanan yang belum lagi dikeluarkan dikumpulkan mengikut jenis pesanan, keutamaan atau jenis aktiviti, contohnya jika anda ingin paparkan pesanan bagi jenis pesanan tertentu atau pesanan proses dengan keutamaan tinggi terlebih dahulu.
Jika anda mahu paparkan semua pesanan yang belum lagi dikeluarkan dalam senarai dan proses selanjutnya, klik pada bahagian atas kad.
Jika anda ingin paparkan pesanan dengan keutamaan tertentu, jenis pesanan atau jenis aktiviti dalam senarai, klik pada bahagian berwarna yang sesuai dalam carta.
Dalam senarai anda boleh melihat, contohnya, butiran individu untuk dihubungi bagi pekerja yang mencipta pesanan dan pekerja yang bertanggungjawab untuk pesanan.
Selain itu, anda boleh navigasikan ke objek pemberitahuan atau teknikal yang telah diumpukkan sebagai objek rujukan, paparkan pesanan individu dan cabangkan ke pemprosesan pesanan.
Anda juga boleh pilih pesanan secara langsung dalam senarai dan keluarkanya atau umpukan status Jangan Laksanakan dengan memilih status yang sesuai dalam bar alat butang tekan bagi jadual.
Ciri Baharu
Aplikasi Uruskan Invois Pembekal mempunyai ciri baharu.
Ciri baharu berikut yang tersedia:
Anda kini boleh mengepos invois transit secara langsung tanpa menukarnya kepada mod edit.
Jika senario aliran kerja untuk Invois Transit sebagai Lengkap dan Invois Disekat diaktifkan serta anda menyimpan invois dengan sebab sekatan sebagai lengkap, anda kini boleh menyemak data butiran untuk kedua-dua senario aliran kerja.
Untuk langkah ini, anda perlu navigasi ke Butiran Kelulusan yang membolehkan anda menukar antara data untuk kedua-dua senario aliran kerja.
Dalam bahagian Pembayaran, medan Sekatan Pembayaran Item telah dinamakan semula kepada Sekatan Pembayaran (JE).
Medan ini menentukan secara langsung sebab sekatan daripada catatan jurnal.
Cukai Bersandar Masa
Beberapa tempoh dengan kadar cukai individu kini tersedia untuk satu kod cukai.
Jika anda telah mengaktifkan cukai bersandar masa, anda boleh mentakrif beberapa tempoh dengan kadar cukai individu untuk satu kod cukai.
Hasilnya, anda boleh menggunakan satu kod cukai untuk kadar cukai yang berbeza.
Papara Cipta Invois Pembekal (daripada aplikasi Uruskan Invois Pembekal) telah disesuaikan, bermaksud, fungsi yang berkaitan telah dipertingkatkan, contohnya:
Item invois (medan Kadar Cukai)
Item akaun G/L (medan Kadar Cukai)
Maklumat cukai (medan Tarikh cukai, Kadar Cukai, Kadar Cukai Sah dari)
Kos penghantaran tidak terancang yang diposkan sebagai baris akaun G/L yang berasingan (medan Kadar Cukai)
Butiran untuk item invois, contohnya, umpukan akaun (medan Kadar Cukai)
Kod syarikat bagi invois yang diumpukkan mentakrif sistem menggunakan tarikh pengeposan atau tarikh dokumen sebagai tarikh cukai lalai.
Anda boleh mengubah tarikh lalai dalam medan Tarikh cukai secara manual jika perlu.
Medan Tarikh cukai digunakan dalam pengepala invois supaya semua item invois mempunyai kadar cukai yang sama.
Jika terdapat apa-apa perbezaan, anda mesti membetulkannya dengan membuat pengeposan manual dalam Perakaunan.
Subnod Baru
Cipta subnod untuk objek perniagaan tersuai.
Semasa anda cipta objek perniagaan tersuai, anda secara automatik mencipta nod puncanya.
Contohnya, anda boleh tambah subnod yang boleh digunakan dalam aplikasi pada objek perniagaan tersuai.
Semasa anda cipta subnod, anda tentukan nama tunggalnya, nama majmuknya dan IDnya.
ID kemudiannya diperlukan jika anda ingin tambah logik tersuai ke subnodnya.
Pastikan subnod anda mempunyai makna dan ID yang boleh difahami.
Semasa anda cipta aplikasi berdasarkan pada objek perniagaan tersuai, anda boleh tambah subnod untuk menyediakan maklumat tambahan pada skrin butiran bagi item senarai dalam aplikasi.
Nama subnod digunakan sebagai tajuk tab pada skrin butiran item senarai dalam aplikasi dijanakan.
Medan subnod dipaparkan sebagai medan, contohnya medan entri atau kotak semak, dikumpulkan di bawah tajuk tab pada skrin butiran item senarai.
Mula
Buka aplikasi Konfigurasi
Klik butang Mula untuk membuka aplikasi Konfigurasi.
Anda boleh mencipta dan mengubah entri konfigurasi.
Anda tidak boleh memadam mana-mana entri konfigurasi
Beberapa Aplikasi Konfigurasi mempunyai sekatan dalam entri ruang nama.Untuk aplikasi tersebut anda tidak dibenarkan mencipta ID untuk medan kod bermula dengan aksara dan nombor seperti berikut:
S, Q, R, X, P, Y untuk medan aksara
5, 6, 7, 8, 9, 0 untuk medan berangka
Fungsi Perniagaan
Ubah Fungsi Perniagaan untuk langkah proses tersuai yang diperlukan
Anda boleh ubah Fungsi Perniagaan untuk langkah proses tersuai yang diperlukan.
Satu atau lebih langkah proses dalam proses ujian mungkin memerlukan fungsi perniagaan khusus untuk pelaksanaan.
Untuk melaksanakan proses ujian dalam rancangan dalam aplikasi Uji Proses Anda, fungsi pengguna ujian yang diperlukan mestilah diselenggara dalam langkah proses.
Contohnya, jika proses ujian mengandungi dua langkah ujian: satu langkah memerlukan fungsi SAP_BR_PURCHASING_MANAGER manakala langkah ujian yang lain memerlukan fungsi SAP_BR_WAREHOUSE_CLE.
Selepas itu, anda perlu mengubah fungsi perniagaan kepada fungsi diperlukan.
Anda boleh lihat keseluruhan senarai fungsi perniagaan dalam Panduan Pentadbir Pelanggan yang dilampirkan dalam SAP Note 2129147.
Semua destinasi fungsi perniagaan mestilah diselenggara dalam SAP Cloud Platform (SCP).
Jika anda menggunakan fungsi perniagaan baru, anda perlu mencipta destinasi dalam SCP.
Sila rujuk Panduan Pentadbir Pelanggan yang dilampirkan dalam SAP Note 2129147 untuk maklumat lanjut.
Versi
Tentukan versi konteks
Beberapa perubahan yang anda lakukan semasa anda edit prom konteks penciptaan versi baru:
Semasa anda edit kategori sedia ada, ini adalah, jika anda keluarkan atau tambah kategori daripada konteks, sistem menyimpan perubahan ini secara automatik dalam versi baru.
Untuk semua perubahan lain ke atribut atau item konteks anda kecuali kategori, anda boleh cadangkan sama ada anda mahu simpan perubahan ini dalam versi baru, atau teruskan bekerja dengan versi konteks sedia ada dengan mengesah atau menolak dialog pengesahan.
Jika anda simpan versi baru dan tetapkan status versi baru ini ke aktif, sistem tetapkan versi lama ke status Digantikan dan versi lama hanya tersedia dalam mod baca sahaja.
Atribut Digantikan Oleh menunjukkan hubungan antara versi lama dan versi baru.
Profil Kematangan
Profil amaun dan kematangan hutang dan pelaburan tertunggak.
Profil kematangan menunjukkan senarai urus niaga hutang dan pelaburan tertunggak syarikat anda dengan butiran item baris seperti amaun nominal.
Anda boleh memaparkan profil dalam paparan carta, paparan jadual atau paparan jadual carta.
Anda juga boleh memilih jenis carta yang berbeza, seperti Carta Garisan dan Carta Pai.
Dalam paparan carta, anda boleh menggunakan Piawai Paparan atau takrifkan paparan anda sendiri dalam kawasan Paparan Saya.
Dalam paparan jadual, anda boleh menggunakan paparan Tataletak Teroptimum atau takrifkan paparan anda sendiri dalam kawasan Paparan Saya.
Komunikasi
Tambah mesej komunikasi.
Untuk memadankan item dengan mana-mana status pemprosesan, anda sentiasa boleh menambah mesej komunikasi seperti berikut:
Tambah Nota:
Tambah ulasan umum dan juga boleh tambah tarikh akhir.
Hantar Pemberitahuan:
Hantar pemberitahuan kepada penerima dipilih dan juga boleh tambah tarikh akhir.
Penerima boleh ditentukan secara automatik jika disediakan dengan betul mengikut struktur organisasi anda.
Tetapkan kepada Selesai:
Apabila ulasan atau pemberitahuan tertentu ditangani, anda boleh menetapkan item untuk dibuat supaya penggera tarikh akhir dan lampau tempoh dijelaskan.
Ciri Baharu
Aplikasi Muat Naik Invois Pembekal mempunyai ciri baharu.
Ciri yang berikut kini tersedia:
Anda boleh navigasi dari item senarai bagi aplikasi Muat Naik Invois Pembekal ke aplikasi Uruskan Invois Pembekal.
Anda boleh masukkan Muat Naik Perihalan.
Parameter carian baharu Invois Pembekal dan Tahun Fiskal tersedia.
Untuk Akauntan Akaun Belum Bayar, aplikasi Muat Naik Invois Pembekal kini turut tersedia.
Senarai Kerja Induk Aset
Tunjukan jumlah bilangan aset, setakat hari ini.
KPI menunjukkan bilangan aset yang aktif dan carta menunjukkan jumlah bagi setiap kategori.
Aset aktif termasuk aset yang tidak lengkap, dalam proses dan dipermodalkan.
Aset aktif tidak termasuk aset yang telah dijual, sekerap atau dinyahaktifkan.
Pilih item dalam carta untuk navigasikan ke aplikasi Papar Senarai Kerja Induk Aset.
Dalam Proses - ialah aset dalam pangkalan data untuk semua data induk yang perlu diselenggarakan.
Aset belum dipermodalkan atau dihentikan.
Dipermodalkan - menunjukkan aset aktifyang telah berjaya dipermodalkan atau pascapermodalan.
Dihentikan - Aset dihentikan dan tarikh pemberhentian disimpan apabila aset dikeluarkan dari portfolio aset syarikat anda.
Pengeposan dan Dokumen
Anda boleh memasukkan, mengepos dan mengedit dokumen secara manual.
Kontrak Akaun Belum Terima dan Belum Bayar direka untuk mengepos dan memproses jumlah dokumen yang besar dan automasi secara meluas tatakerja perniagaan secara manual sebagai sebahagian daripada perakaunan sublejar.
Anda memindahkan jumlah data dokumen yang besar daripada sistem suapan atau luaran secara automatik melalui aplikasi Pindahkan Dokumen.
Melalui aplikasi Pindahan dokumen:
Proses Ralat anda boleh membetulkan ralat yang berlaku semasa pindahan.
Prasyarat untuk antara muka aplikasi adalah item baris yang terdiri daripada pengepala dan item.
Di samping itu, terdapat beberapa cara untuk memindahkan data dokumen ke sistem anda:
Dengan SOAP API Perakaunan Kontrak - Uruskan Dokumen (lihat API untuk SAP S/4HANA dalam )
Melalui aplikasi Import Dokumen
Anda menggunakan aplikasi untuk tujuan ujian atau jika anda ingin mencipta dokumen secara manual dan memeriksanya sebelum pindahan.
Untuk melakukannya, masukkan item baris individu dalam fail CSV.
Semasa pindahan, dokumen dicipta daripada aplikasi.
Sistem menyimpan pengeposan sebagai dokumen dalam sistem (prinsip dokumen); dokumen berfungsi sebagai bukti urus niaga perniagaan dalam sistem (lihat Dokumen).
Setiap dokumen mengandungi nombor dokumen yang unik (yang tidak bersandar tahun fiskal) dengan maksimum dua belas aksara.
Sama ada sistem mengumpukkan nombor dokumen secara automatik atau anda yang memasukkan nombor dokumen.
Umpukan nombor automatik dikawal oleh jenis dokumen.
Apabila anda memasukkan dokumen, anda juga boleh menjelaskan item terbuka yang telah diposkan.
Anda boleh memaparkan dokumen, dan apabila keperluan tertentu dipenuhi, anda boleh mengubah, membalikkan dan mengarkibkannya.
Selain item baris yang mengemas kini angka urus niaga dalam lejar am seperti invois, pembayaran, atau memo kredit, anda juga boleh mengeposkan item baris statistik.
Kemudian, sistem membuat nota bagi item baris ini pada akaun kontrak sahaja.
Ia tidak berkaitan dengan lejar am tetapi ia diproses oleh kedua-dua atur cara dunning dan atur cara bayaran.
Anda menggunakan item baris statistik, contohnya, untuk mengeposkan permintaan pengebilan belanjawan atau caj belum terima.
Item baris statistik tidak diambil kira semasa semakan baki.
Anda boleh mengeposkan dokumen di seluruh kod syarikat.
Baki semua item baris dalam kod syarikat sentiasa sifar (lihat Dokumen Kod Merentasi Syarikat).
Bergantung pada urus niaga perniagaan, sistem mencipta pengeposan automatik.
Urus niaga perniagaan yang berada dalam kategori ini termasuk cukai, diskaun dan nilai tukaran yang berbeza.
Sistem mengira jumlah yang berkaitan dan secara automatik menentukan akaun G/L yang akan diposkan.
Selain daripada akaun G/L untuk pengeposan automatik, anda boleh mentakrifkan umpukan akaun selanjutnya bergantung pada urus niaga perniagaan.
Ini memudahkan untuk memasukkan dan memproses dokumen.
Penggunaan Senarai Tugas
Klik untuk memilih penggunaan senarai tugas.
Jenis penggunaan senarai tugas merupakan kod untuk mengawal jenis senarai tugas yang anda boleh gunakan sumber seperti pusat kerja atau sumber/alat pengeluaran.
Anda boleh memilih jenis penggunaan senarai tugas berikut yang ingin dipertimbangkan sebagai sebahagian daripada data rujukan untuk simulasi anda:
004 Hanya senarai tugas penyelenggaraan
008 Resipi induk + pesanan proses
009 Semua jenis senarai tugas
Sekat dan Padam Data Peribadi dalam Pengurusan Belum Terima dan Pengendalian Bayaran
Proses dan fungsi Kontrak Akaun Belum Terima dan Belum Bayar menggunakan data peribadi pekongsi perniagaan SAP.
Jika, dari sudut pandangan bagi proses dan fungsi ini, tidak terdapat lagi mana-mana sebab untuk menyimpan data (contohnya, audit cukai yang mungkin), anda boleh menyekat data ini daripada perspektif Kontrak Akaun Belum Terima dan Belum Bayar dan akhirnya memusnahkannya.
Untuk memusnahkan data peribadi, guna fungsi Pengurusan Kitaran Hayat Maklumat (ILM).
Apabila menggunakan fungsi ILM, anda perlu menyekat data peribadi pekongsi perniagaan, untuk mereka yang tiada urusan selanjutnya.
Kemudian anda padam data ini sebaik sahaja ia tidak lagi diperlukan.
Untuk maklumat lanjut, lihat pembantu produk bagi SAP S/4HANA cloud di bawah Maklumat Umum Aspek Keselamatan.
Muat turun
Dengan memilih Muat turun, anda boleh muat tuurn fail arkib zip yang mengandungi fail yang anda perlukan untuk edit borang dalam Adobe® LiveCycle® Designer.
Arkib zip mengandungi fail yang berikut:
Templat borangnya sendiri (*.xdp).
Fail ini mengandungi tataletak borang dan ialah asas pengeditan dalam Adobe® LiveCycle® Designer.
Maklumat pembekla data (*.xsd).
Fail ini mengandungi struktur (medan) pembekal data dalam format xsd dan boleh digunakan sebagai sambungan data dalam Adobe® LiveCycle® Designer.
Induk templat borang (master_fragment.xdp) yang mengandungi bahagian pengepala dan pengaki tataletak (pilihan).
Jika perlu, anda juga boleh masukkan induk templat dalam arkib zip.
Penunjuk Peruntukan Bahan
Masukkan item bil bahan yang disediakan oleh pelanggan atau vendor.
Dalam ledakan bil bahan, anda menggunakan penunjuk ini untuk mengehadkan item dipilih.
Terdapat dua jenis peruntukan bahan:
Bahan yang disediakan oleh vendor
Bahan yang disediakan oleh pelanggan
Anda menggunakan penunjuk peruntukan bahan (MPI) untuk mengenal pasti jenis subkontrak bahagian.
Penunjuk berikut disediakan:
Bahan kerja semula untuk subkontraktor (nilai S dalam sistem SAP piawai)
Bahan kerja semula daripada subkontraktor (nilai X dalam sistem SAP piawai)
Penghantaran seterusnya (nilai F dalam sistem SAP piawai)
Jika anda tidak memasukkan maklumat dalam medan ini, komponen disediakan kepada subkontraktor sebagai bahan boleh digunakan (nilai asal dalam sistem SAP piawai).
Tarikh Pertama
Tarikh pertama dalam julat atau tarikh rujukan untuk surat-menyurat.
Bergantung pada jenis surat-menyurat, medan ini mungkin merujuk:
Hari pertama dalam julat masa termaktub dalam dokumen surat-menyurat.
Tarikh dokumen surat-menyurat dikeluarkan.
Contohnya, tarikh rujukan atau tarikh penyelesaian.
Jika julat tarikh termaktub dalam surat-menyurat, anda boleh gunakan medan Tarikh Kedua untuk menapis hasil mengikut hari terakhir dalam julat ini.
Medan Tersedia
Papar medan yang tersedia untuk perihalan pelaksanaan anda.
Medan tersedia bagi perihalan pelaksanaan anda diterangkan melalui parameter yang anda boleh lihat dalam mod ujian.
Prameter ini dipratakrifkan mengikut perihalan takrifan sepadan.
Jika anda telah mencipta medan untuk antara muka yang sama dengan perihalan pelaksanaan anda, anda juga boleh melaksanakan medan ini dalam perihalan pelaksanaan.
Dalam mod draf, anda boleh menguji perihalan pelaksanaan mengikut senario perniagaan anda dengan medan tersedia.
Masukkan nilai ujian untuk medan dan jalankan perihalan pelaksanaan anda.
Aplikasi menyediakan anda dengan hasil ujian.
Ubah lebar lalai lajur dalam jadual
Anda boleh mengubah lebar lalai lajur dalam jadual.
Anda boleh mengubah lebar lajur dalam jadual dan membuat perubahan anda sebagai pilihan lalai.
Hal ini mungkin berguna jika anda ingin memaparkan data dalam mod skrin penuh.
Untuk mengubah lebar lalai lajur:
Buka Paparan Nilai dalam mod skrin penuh menggunakan ikon.
Seret lajur ke lebar yang sesuai.
Klik pada Piawai dan kemudian pilih Simpan sebagai.
Anda kini boleh menetapkan varian baharu anda sebagai Lalai dalam Simpan Paparan.
Dokumen
Bahagian ini menunjukkan dokumen yang diumpukkan atau berpaut ke transaksi undang-undang.
Dokumen merupakan fail statik yang dimuat naik dan diumpukkan ke transaksi undang-undang sebagai lampiran.
Jenis kandungan menentikan tujuan dokumen, contohnya, pindaan, kontrak induk, atau perjanjian bukan pendedahan.
Dalam subseksyen Dokumen, senarai dokumen diumpukkan ke transaksi undang-undang dipaparkan.
Anda boleh Edit, Muat Turun atau Tambah dokumen.
Dalam subseksyen Dokumen Berpaut, senarai dokumen yang berpaut daripada transaksi undang-undang lain dipaparkan.
Dokumen ini merujuk pada dokumen yang telah dimuat naik ke transaksi undang-undang lain.
Carian dan Import
Cari sebelum mencipta dan import data dari pembekal luaran
Sebelum mencipta rekod data induk baru, anda boleh cari data organisasi luaran yang sedia ada dan importnya dengan menggunakan butang Import.
Untuk mendapatkan rekod luaran, kriteria carian adalah seperti berikut:
Negara dan medan carian teks bebas adalah wajib.
Carian nilai berbilang untuk medan Negara, Bandar, Jalan, dan Poskod tidak disokong.
Hanya gunakan operasi SAMA DENGAN dan MENGANDUNGI untuk medan Negara, Bandar, Jalan, dan Poskod dalam penapis carian.
Baki Amaun/Kuantiti
Tunjukkan amaun atau kuantiti terbuka bagi item lembaran entri perkhidmatan.
Tunjukkan baki amaun atau kuantiti bagi item lembaran entri perkhidmatan.
Sekiranya menjadi rujukan bagi item piawai pesanan belian:
Baki kuantiti (Delta) ialah kuantiti dipesan (Dijangka) tolak kuantiti Dinyatakan.
Kuantiti Dinyatakan ialah jumlah kuantiti yang dinyatakan bagi semua item lembaran entri perkhidmatan lain yang merujuk item pesanan belian yang sama.
Sekiranya menjadi rujukan bagi item had pesanan belian:
Baki amaun (Delta) ialah Nilai Dijangka (seperti yang ditakrif dalam item had pesanan belian) tolak amaun Dinyatakan.
Amaun Dinyatakan ialah jumlah amaun yang dinyatakan bagi semua item lembaran entri perkhidmatan lain yang merujuk item had pesanan belian yang sama.
Amaun atau kuantiti yang dinyatakan bagi item lembaran entri perkhidmatan semasa tidak termasuk dalam amaun atau kuantiti Dinyatakan.
Item lembaran entri perkhidmatan yang lain merujuk pada item pesanan belian yang sama adalah termasuk amaun atau kuantiti yang Dinyatakan.
Amaun
Bahagian ini menunjukkan angka utama pada tarikh rujukan pelaporan.
Bahagian ini menunjukkan angka utama berikut pada tarikh rujukan pelaporan.
Kos perolehan dan pengeluaran (APC)
Amaun susut nilai dipos.
Amaun susut nilai dirancang
Untuk tujuan perbandingan, amaun susut nilai dirancang pada permulaan tahun fiskal ditunjukkan seperti berikut.
Butiran Output
Semak butiran output.
Dalam bahagian ini, maklumat dibutirkan mengenai status output bagi RFQ dipaparkan.
Semua maklumat berkaitan mengenai output seperti saluran output, templat borang dan tarikh diubah terakhir juga tersedia dalam bahagian ini.
Sistem mengisinya dengan data selepas anda simpan dan terbitkan RFQ.
Anda boleh paparkan output RFQ dengan memilih ikon pratonton dalam baris sepadan.
Jika ralat berlaku, anda boleh paparkan maklumat terperinci dengan memilih Tunjukkan Log Aplikasi.
Penggunaan Mandat SEPA oleh Aplikasi Berbilang
Oleh sebab SEPA boleh digunakan oleh pelbagai aplikasi (FI-CA, FI-AR, Perbankan) — dalam sistem dan pelanggan yang sama — sistem menyimpan aplikasi dalam mandat.
Jika anda menggunakan hanya satu daripada aplikasi ini, sistem menganggapnya sebagai aplikasi lalai.
Jika anda menggunakan aplikasi berbilang, anda boleh menukar aplikasi.
Jika lebih daripada satu aplikasi yang aktif dalam sistem, pada skrin awal, pilih aplikasi Cipta Mandat SEPA apabila mencipta mandat dalam mod dialog Tukar Aplikasi.
Sistem kemudian memaparkan senarai semua aplikasi yang aktif.
Pilih aplikasi yang anda inginkan.
Jika anda memapar atau mengubah mandat, sistem menentukan aplikasi lalai pada asas aplikasi yang disimpan dalam mandat.
Takrifkan Tujuan
Takrifkan tujuan boleh digunakan semasa mentakrif peraturan pengekalan dalam SAP ILM atau semasa memberikan maklumat tentang data peribadi.
Tujuan mewakili proses perniagaan yang mengumpulkan objek ILM yang berkaitan dengan proses.
Objek ILM ini mempunyai peraturan keberadaan dan pengekalan yang sama.
Menggunakan aplikasi ini, anda boleh:
Takrifkan tujuan
Umpukan objek ILM ke tujuan
Selenggara medan syarat
Organisasi Perkhidmatan
Berikut ialah organisasi perkhidmatan bagi sebarang permintaan sumber diumpukkan.
Medan ini menunjukkan organisasi perkhidmatan bagi sebarang permintaan sumber diumpukkan.
Apabila mencipta dan merancang projek, pengurus projek boleh tentukan organisasi perkhidmatan pada aras projek dan pada aras fungsi.
Organisasi perkhidmatan yang diumpukkan pada aras fungsi dirujuk sebagai organisasi penghantaran.
Ditunjukkan di sini jika pengurus projek menetapkan organisasi penyampaian untuk fungsi.
Jika pengurus projek tidak menentukan organisasi penghantaran untuk fungsi, organisasi perkhidmatan projek ditunjukkan.
Tempoh Tarikh Pengeposan
Bilangan hari untuk tarikh pengeposan
Bilangan hari untuk tarikh pengeposan.
Urus niaga kemudian ditapis semasa tempoh antara Masa Mula dan Tempoh Tarikh Pengeposan.
Bergantung pada nilai yang anda masuk, kini boleh menjadi lewat atau awal daripada Masa Mula.
Anda masukkan 3 untuk Tempoh Tarikh Pengeposan, dan urus niaga yang akan diposkan 3 hari selepas masa mula dipaparkan.
Anda masukkan -3 untuk Tempoh Tarikh Pengeposan, dan urus niaga yang telah diposkan 3 hari sebelum masa mula dipaparkan.
Pilih Berkas Skop
Pilih set praditakrif item skop untuk skop awal.
Anda boleh pilih set praditakrif item skop untuk skop awal yang boleh diaktifkan secara konsisten.
Dalam kes anda mahu pilih item skop secara individu untuk skop, anda boleh pilih Skop Individu.
Dalam kes ini, anda perlu hubungi SAP berdasarkan pada langkah peta laluan SAP Activate untuk takrifkan skop.
Pilih Teruskan untuk memulakan proses skop.
Pusat Perkhidmatan SAP akan menyemak permintaan anda dan memulakan pengaktifan awal.
Umpuk Kod Penyelarasan Baharu
Jika lot pulangan atau pembayaran yang diposkan di bawah kod penyelarasan masih mengandungi kes penjelasan terbuka, kod penyelarasan juga kekal terbuka dan anda tidak boleh memindahkannya ke lejar am.
Bagi memindahkan pengeposan yang telah dibuat pada pindahan lejar am, anda perlu mengumpukkan kod penyelarasan baharu untuk pengeposan penjelasan yang tertunggak pada lot.
Ini membolehkan anda menutup kod penyelarasan asal dan memindahkannya ke lejar am.
Ini merupakan satu-satunya cara untuk menyelaraskan akaun penjelasan tunai anda pada tarikh yang tepat, jika kes penjelasan masih wujud.
Jika pengeposan penjelasan kekal, anda sentiasa dapat mengumpukkan kod penyelarasan baharu apabila lot anda diproses.
Jika anda mempunyai sistem yang mengumpukkan kod penyelarasan baharu secara automatik untuk semua lot yang masih mengandungi kes penjelasan, sistem hanya mengumpukkan kod baharu jika pengeposan telah dibuat untuk kod yang sedang digunakan pada masa ini.
Aplikasi Umpukkan Kod Penyelarasan Baharu (Lot Pembayaran) dan Umpukkan Kod Penyelarasan Baharu (Lot Pulangan) menutup kod penyelarasan untuk lot yang terlibat dan mengumpukkan kod penyelarasan baharu secara automatik pada pengeposan yang akan dijelaskan.
Untuk mengumpukkan kod penyelarasan baharu:
Pilih aplikasi yang diperlukan.
Tentukan lot dan kod syarikat yang diperlukan.
Jika anda tidak menentukan lot dan kod syarikat, sistem memilih semua lot terbuka dan tertutup yang mengandungi kes penjelasan.
Jalankan atur cara.
Dalam paparan, anda melihat
Lot yang mengandungi kes penjelasan (Lot)
Bilangan lot yang atur cara ditutup (tertutup)
Bilangan lot yang atur cara dicipta (terbuka)
Jika atur cara tidak dapat menentukan kod penyelarasan baharu, medan Ulasan mengandungi butiran sebab percubaan tersebut gagal.
Anda menjalankan laporan sebagai jalanan ujian.
Dengan cara lain, anda boleh membuat umpukan apabila memproses lot pembayaran atau pulangan.
Had Hari
Hari dalam bulan sehingga syarat yang berkaitan sah.
Untuk syarat bayaran yang bergantung pada tarikh asas selepas atau sebelum 15hb, anda boleh mentakrif syarat bayaran dua bahagian di bawah kod syarat bayaran yang sama.
Kod syarat bayaran dikembangkan mengikut had hari yang dimasukkan di sini.
Oleh itu terdapat dua entri dalam syarat yang berbeza boleh ditentukan.
Contohnya, anda perlu masukkan had hari untuk syarat bayaran yang berikut:
Dokumen dengan tarikh invois pada atau sebelum 15hb belum dibayar pada hari terakhir bulan seterusnya
Dokumen dengan tarikh invois selepas 15hb belum dibayar pada 15hb pada bulan tersebut selepas bulan seterusnya.
Cipta Jujukan
Picu penciptaan jujukan baru.
Anda boleh gunakan butang Cipta Jujukan untuk picu penciptaan jujukan baru.
Medan Nama Jujukan adalah wajib dan diserlahkan dengan sewajarnya.
Asas jujukan anda adalah atribut isihan.
Atribut isihan ditakrifkan pada Pilih:
Bantuan nilai Atribut Isihan yang anda boleh capai daripada medan Atribut Isihan wajib dengan mengklik ikon atau F4.
Memilih Pergi pada Pilih:
Bantuan nilai Atribut Isihan menyenaraikan semua atribut isihan yang mungkin.
Jika anda ingin senaraikan dan mengutamakan keperluan oleh pengguna, pilih item PIHAK PEMBELI.
Pengeditan Prom
Ubah tetapan untuk pemboleh ubah bagi keseluruhan tab atau kumpulan carta.
Untuk mendapatkan data pada tab, anda perlu mentakrifkan pemboleh ubah bagi tab.
Mengikut tetapan bagi pemboleh ubah, data yang sepadan dikira dan dipaparkan.
Aplikasi dihantar dengan tetapan lalai bagi pemboleh ubah.
Pemboleh ubah berbeza bagi sumber data berbeza yang dipanggil untuk carta tab.
Tab dan Sumber Data
Tab
Sumber Data
Kecairan
Pengurusan Tunai
Keberhutangan
Jaminan Bank
Risiko Kontraktor
Paparan Keseluruhan Pasaran
Anda juga boleh memilih Edit Prom Carta, jika anda hanya ingin mengubah pemboleh ubah bagi carta tertentu.
Pada tab tertentu, pilih Edit Prom pada sudut kanan, dan.
Pilih ??? Yang berkaitan untuk tab.
Pada timbul Tetapkan Pemboleh Ubah untuk …., anda boleh memadam ahli pratakrif dan memasukkan nilai pilihan anda menggunakan bantuan nilai.
Jika anda telah membuat semua perubahan yang diperlukan terhadap nilai pemboleh ubah, pilih Tetapkan.
Edit Halaman Utama
Dayakan anda untuk mencapai halaman utama dalam mod edit
Halaman utama merupakan bahagian kerja utama anda.
Jubin atau pautan yang mewakili aplikasi yang anda gunakan dikumpulkan ke dalam kumpulan pada halaman utama anda.
Dengan fungsi "Edit Halaman Utama", anda memperibadikan halaman utama untuk sesuaikannya dengan persekitaran kerja anda.
Keupayaan untuk memperibadikan halaman utama didayakan oleh pentadbir anda.
Anda boleh membuat perubahan berikut pada halaman utama anda:
Mengatur semula atau alihkan jubin
Anda boleh seret jubin ke lokasi yang baru dalam kumpulan semasa atau kumpulan lain.
Anda juga boleh klik atau ketik jubin dan gunakan butang Alih untuk memilih kumpulan yang anda ingin alihkan jubin.
Cara ini sangat berguna jika kumpulan sasaran tidak berdekatan dengan kumpulan asal pada halaman utama.
Tambah kumpulan
Pilih "Tambah Kumpulan" dan masukkan nama untuk kumpulan baru.
Tambah aplikasi untuk kumpulan
Klik "Tambah" pada ruang letak jubin.
Pencari aplikasi dibuka apabila anda boleh mencari semua aplikasi yang tersedia untuk anda.
Padam kumpulan
Klik atau ketik "Padam" pada pengepala kumpulan.
Kumpulan dipadam dan jubin dan pautannya dikeluarkan daripada halaman rumah.
Ambil perhatian bahawa anda hanya boleh memadam kumpulan yang telah anda cipta.
Sembunyikan kumpulan
Klik atau ketik "Sembunyikan".
Untuk nyahsembunyi kumpulan, klik atau ketik "Tunjukkan".
Ambil perhatian bahawa pilihan ini boleh dinyahdayakan oleh pentadbir anda.
Tetapkan semula kumpulan
Klik atau ketik "Tetapkan semula" dalam pengepala kumpulan.
Namakan semula kumpulan
Klik atau ketik dua kali nama kumpulan.
Alihkan kumpulan
Seret tajuk kumpulan ke lokasi baru pada halaman utama.
Namakan semula jubin
Klik atau ketik jubin dan pilih "Tetapan".
Anda juga boleh menyediakan subtajuk dan maklumat tambahan dalam dialog "Tetapan".
Keluarkan jubin
Klik atau ketik butang "Keluarkan" pada sudut atas kanan jubin.l
Untuk menyimpan perubahan anda dan keluar daripada mod edit, klik "Tutup" pada bahagian bawah halaman utama atau klik "Keluar Mod Edit" dalam Kawasan Me.
Penyelarasan
Jumlah Kawalan, Kod Penyelarasan, Jumlah Penyelarasan
Jumlah kawalan merupakan jumlah yang anda boleh gunakan untuk menentukan sama ada amaun dokumen yang diposkan dimasukkan dengan betul.
Dalam FI-CA, tiada struktur jumlah kawalan digunakan sejak fungsi ini dilindungi oleh kod penyelarasan.
Pengeposan manual
Jika seorang kerani dalam FI-CA terpaksa mengepos kuantiti dokumen secara manual, dia perlu mencipta kod penyelarasan baharu terlebih dahulu dan kemudian mengeposkan semua dokumen menggunakan kod penyelarasan ini.
Kemudian, dia perlu menutup kod penyelarasan.
Dengan menggunakan fungsi untuk memaparkan kod penyelarasan, dia boleh menyemak jumlah rekod. Oleh itu, akaun diposkan.
Kerani boleh mencipta kod penyelarasan secara manual.
Pengeposan Automatik
Untuk pengeposan automatik, sistem menyimpan kod penyelarasan pada permulaan jalanan atur cara.
Sebaik sahaja jalanan lengkap, sistem menutup kod penyelarasan ini secara automatik supaya tiada pengeposan lanjutan dalam kod penyelarasan ini yang dapat memalsukan penyelarasan.
Sebaik sahaja jalanan besar-besaran telah lengkap, anda boleh menggunakan fungsi untuk memaparkan kod penyelarasan bagi menentukan kuantiti kod penyelarasan yang diposkan dan menyenaraikan jumlah rekod yang berkaitan.
Pemprosesan Senarai Kerja Penjelasan
Akaun penjelasan merupakan akaun G/L yang pembayarannya diposkan (pemprosesan lot pembayaran) jika penyertaan yang dipilih tidak cukup lengkap untuk memilih item terbuka bagi pembayaran atau untuk menentukan akaun kontrak bagi mengeposkan pembayaran pada akaun.
Anda boleh menggunakan pengeposan untuk akaun penjelasan bagi menyelaraskan akaun penjelasan tunai sepenuhnya.
Akaun penjelasan tidak diselenggarakan oleh item baris atau item terbuka dalam lejar am.
Pastikan bahawa hanya pengeposan yang dibuat adalah kes penjelasan daripada lot pembayaran.
Anda memproses senarai kerja penjelasan dalam pemprosesan penjelasan dalam FI-CA.
Penyelarasan Harian bagi Akaun Penjelasan Tunai
Anda menyelaraskan akaun penjelasan tunai seperti yang diterangkan dalam bahagian Selaraskan Data Pengeposan berikut.
Anda boleh menjalankan penyelarasan dalam kes yang berbeza jika anda membuat pindahan harian dengan menggunakan tarikh ciptaan sebagai kriteria pemilihan dalam laporan untuk menyelaraskan lejar am dan tarikh pindahan terakhir dalam jumlah rekod (parameter Pindahan sejak dalam atur cara untuk menyemak jumlah pengeposan).
Semasa jalanan pembayaran dalam FI-CA, sistem memindahkan jumlah rekod yang dicipta dengan ID jalanan pembayaran dalam medan Nombor Umpukan (BSEG-ZUONR) ke lejar am.
Oleh itu, anda boleh membuat pengeposan gantian dan menyelaraskan penyata akaun elektronik dalam lejar am dan baki bank FI-CA.
Penyelarasan Akaun Belum Terima dan Belum Bayar - Penyelarasan Bulanan
Teruskan seperti yang diterangkan dalam bahagian Selaraskan Data Pengeposan.
Cipta Peraturan Perniagaan ILM
Peraturan perniagaan mendayakan anda untuk janakan peraturan pengekalan dan keberadaan ILM dengan menetapkan pengawal dan tujuan data tertentu aplikasi.
Prasyarat:
Ciptaan pengawal data - Menggunakan aplikasi konfigurasi layan diri - konfigurasikan Perihalan Pengawal Data.
Ciptaan tujuan - Menggunakan aplikasi konfigurasi layan diri - konfigurasi Perihalan Tujuan
Selenggarakan rujukan masa lalai dan masa ofset - Menggunakan aplikasi konfigurasi layan diri Perihalan Rujukan Masa - konfigurasi
Selenggarakan bahagian audit lalai - Menggunakan aplikasi konfigurasi layan diri dengan konfigurasikan Bahagian Audit
Klik Cipta Objek untuk mencipta peraturan perniagaan ILM anda ID Peraturan Perniagaan dan Perihalan Peraturan.
ID Peraturan Perniagaan mestilah unik.
RUC_CONF_TOLERANCESCUSTSUPPL
Anda boleh mentakrif toleransi untuk mengendalikan situasi yang amaun yang dinyatakan dalam invois berbeza daripada amaun yang anda terima daripada pelanggan atau amaun yang anda bayar kepada pembekal
Anda boleh tentukan toleransi untuk pelanggan dan pembekal dengan mentakrif satu atau lebih kumpulan toleransi.
Kemudian anda umpukkan kumpulan toleransi kepada setiap pelanggan dan setiap pembekal dalam rekod data induk.
Jika anda tidak mengumpukkan kumpulan toleransi dalam data induk, kumpulan toleransi lalai digunakan.
Untuk setiap kumpulan toleransi, anda tentukan yang berikut:
Perbezaan dalam amaun pembayaran bagi pengeposan untuk perbelanjaan atau akaun hasil dibenarkan oleh sistem semasa menjelaskan item terbuka
Terma pembayaran yang digunakan untuk items isa jika ia dipos semasa penjelasan
Anda juga boleh mentakrif had amaun untuk pengguna Perakaunan Kewangan anda.
Untuk penjelasan, had yang lebih rendah ditakrif untuk pengguna anda dan had ditakrif untuk pekongsi perniagaan anda digunakan.
Jenis Bank dalam Rantaian Bank
Jenis bank yang manakah yang diumpukkan ke bank perantara?
Terdapat beberapa jenis bank yang anda boleh umpukkan ke bank perantara anda apabila mencipta rantaian bank.
Setiap bank diumpukkan dengan nombor:
Bank surat-menyurat penghantar
Bank perantara
Bank surat-menyurat penerima
Bank syarikat luaran (digunakan untuk pembayaran tunai dalaman sahaja)
Persetujuan untuk Ujian PascanaikTaraf
Anda mesti memberikan persetujuan kepada SAP untuk mengendalikan Ujian Pascanaik Taraf.
Dengan memilih pilihan Sahkan, anda bersetuju bahawa SAP akan menjalankan pelaksanaan ujian pascanaik taraf dalam sistem kualiti anda untuk keluaran berikut.
Sebagai sebahagian daripada ujian pascanaik taraf, SAP akan mencipta dan melaksanakan rancangan ujian.
Hasil ujian akan tersedia dalam aplikasi dashboard pelanggan.
Semasa proses ini, data transaksi akan dicipta daripada Penyesuaian dan data Induk sedia ada dalam sistem kualiti.
Setelah persetujuan diberikan, ia akan terus berkuat kuasa sehingga anda memutuskan untuk menarik balik persetujuan.
Penyelenggaraan Spesifikasi untuk Dokumen Pengeposan
Transaksi Luaran
Anda boleh mengumpukkan transaksi – sendiri - luaran ke utama dan subtransaksi yang dihantar oleh SAP.
Anda mengumpukkan parameter ansuran tertentu anda sendiri untuk mengeposkan dokumen kepada transaksi sendiri.
Transaksi dalaman merupakan semua proses yang dihantarkan oleh SAP seperti mengepos bayaran, mengira faedah atau mencipta rancangan ansuran.
Anda boleh melihat paparan keseluruhan proses ini apabila anda mengumpukkan transaksi luaran kepada transaksi dalaman.
Sistem menentukan transaksi luaran dan dalaman secara automatik untuk pengeposan yang berkaitan.
Dalam aplikasi Uruskan Penyelesaian Anda di bawah Konfigurasikan Penyelesaian Anda, buat tetapan di bawah Kewangan Perakaunan Kontrak Pengeposan dan Dokumen Takrifkan dan Buat Parameter Transaksi Luaran.
Kemudian, umpukkan transaksi luaran kepada transaksi dalaman dalam langkah Umpukkan Transaksi Luaran.
Bahagian perniagaan
Anda boleh mentakrifkan bahagian perniagaan dalam akaun kontrak atau dalam data umpukan akaun transaksi yang berkaitan.
Sistem menentukan bahagian perniagaan secara automatik untuk semua pengeposan mengikut spesifikasi yang diterangkan di bawah.
Jika anda memasukkan pekongsi perniagaan dalam item pekongsi perniagaan secara langsung, contohnya, semasa pengeposan manual, entri ini membatalkan penentuan automatik.
Penentuan bahagian perniagaan adalah berdasarkan perkara berikut:
Dalam langkah pertama, sistem membaca bahagian perniagaan dari akaun kontrak yang item pekongsi perniagaannya diumpukkan.
Jika tiada nilai ditentukan dalam item pekongsi perniagaan, sistem menerbitkan bahagian perniagaan dari akaun kontrak.
Jika tiada bahagian perniagaan yang boleh ditentukan untuk item yang diposkan melalui cara ini, sistem menerbitkan bahagian perniagaan daripada data umpukan akaun transaksi berkaitan yang ditakrifkan dalam Penyesuaian.
Jika sistem tidak dapat menentukan bahagian perniagaan untuk item pekongsi perniagaan dan penyata kewangan bahagian perniagaan aktif untuk Perakaunan Kewangan (FI), ralat berlaku apabila anda mengeposkan dokumen.
Dalam aplikasi Uruskan Penyelesaian Anda di bawah Konfigurasikan Penyelesaian Anda, buat tetapan sistem di bawah Kewangan Perakaunan Kontrak Pengeposan dan Dokumen Takrifkan Data Umpukan Akaun yang Berkaitan dengan Transaksi.
Anda memasukkan bahagian perniagaan dalam Data Umum bagi akaun kontrak dalam aplikasi Selenggarakan Akaun Kontrak.
ID penentuan akaun
ID penetapan akaun digunakan untuk menentukan transaksi dan data umpukan akaun transaksi berkaitan yang utama dan ditentukan daripada data induk kontrak yang item pekongsi perniagaannya diposkan bagi setiap pengeposan.
ID Penentuan Akaun ditakrifkan dalam akaun kontrak.
Kemudian, konfigurasikan data umpukan akaun transaksi berkaitan dan data umpukan akaun transaksi berkaitan yang utama dengan ID penetapan akaun yang telah ditakrifkan.
Terma bayaran
Bagi setiap pengeposan dalam Kontrak Akaun Belum Terima dan Belum Bayar, terma bayaran menentukan tarikh akhir item.
Syarat pembayaran ditakrifkan dalam akaun kontrak pekongsi perniagaan.
Pembayaran melalui pembekal perkhidmatan pembayaran
Untuk memproses pembayaran melalui Add-On pembayaran Digital SAP, anda harus memastikan bahawa sistem suapan (API) atau Invois Tertumpu menyediakan pembekal perkhidmatan pembayaran dan rujukan pembayaran versi pembekal perkhidmatan pembayaran.
Sistem menyimpan maklumat ini dalam data pembayaran dokumen penjelasan.
Add-On pembayaran Digital SAP memproses pembayaran dan ianya tersedia untuk nota makluman bayaran.
Untuk memproses pembayaran dalam aplikasi Pemprosesan Kad Pembayaran, teruskan seperti berikut:
Pindahan nota makluman bayaran
Menggunakan templat kerja Import Data Nota Makluman Bayaran dari Add-On Pembayaran Digital, anda bertanya secara berkala mengenai nota makluman bayaran dari Add-On Pembayaran Digital SAP.
Penyelesaian
Dengan menggunakan templat kerja Penyelesaian Pembekal Perkhidmatan Bayaran, anda kemudiannya memproses nota makluman bayaran yang diterima.
Dengan templat kerja Meminta Bayaran Memo Kredit, anda meminta kembali memo kredit yang diberikan.
Pelanggan memulangkan produk.
Anda membayar balik amaun belian dan menghantar memo kredit dengan merujuk kepada pembayaran iaitu rujukan kandungan pembekal perkhidmatan pembayaran.
Anda meminta pembekal perkhidmatan pembayaran memulangkan semula kepada pelanggan (jenis pemprosesanitem untuk dilaporkan).
Anda menerima maklum balas melalui import dan pemprosesan nota makluman bayaran daripada Add-On Pembayaran Digital SAP.
Memo kredit untuk pembayaran yang telah diminta dalam Add-On Pembayaran Digital SAP memperoleh status add-on pembayaran digital SAP dimaklumkan.
Jika memo kredit berjaya diproses, sistem mengepos dokumen semasa pemprosesan nota makluman pembayaran melalui amaun yang dikreditkan dan, jika perlu, caj diposkan.
Item mempunyai status diselesaikan.
Jika penyelesaian gagal, sistem menetapkan status Penyelesaian Gagal.
Konfigurasi
Tetapan sistem untuk memproses bayaran menggunakan pembekal perkhidmatan pembayaran dalam aplikasi Uruskan Penyelesaian Anda di bawah Konfigurasikan Penyelesaian Anda dalam elemen konfigurasi Pembekal Perkhidmatan Pembayaran.
Produk Gandingan
Tentukan bahan yang diperoleh semasa proses yang sama seperti bahan asas lain.
Anda hanya boleh memilih item sebagai produk gandingan jika memenuhi keperluan berikut:
Rekod induk bahan
Dalam data MRP, anda telah menetapkan bahan sebagai produk gandingan.
Bil bahan
Bahan mestilah item stok dan tidak perlu diperuntukkan kepada kumpulan item alternatif.
Kategori Item
Kategori item mengkategorikan item bagi dokumen perakaunan.
Ia diterbitkan daripada jenis akaun (seperti aset dan pelanggan).
Dalam bahagian akaun G/L, terdapat lebih daripada satu kategori item yang mungkin.
Umpukan perlu ditakrif mengikut nombor akaun G/L bagi kategori item boleh terbit yang tidak ditakrif secara automatik.
Kategori item dipratakrif dalam Sistem SAP piawai.
Anda tidak boleh mentakrif sebarang kategori item tambahan.
Pilihan Simulasi Carian
Ubah pilihan carian untuk simulasi.
Anda boleh ubah pilihan yang berikut:
Picu Simulasi Carian secara Automatik: aktif/nyahaktif
Cadangan untuk Input Carian: aktif/nyahaktif
Muatkan Faset: aktif/nyahaktif
Sentiasa Gunakan Pengguna Log Masuk untuk Simulasi: aktif/nyahaktif Pilihan ini mesti nyahaktif jika anda ingin jalankan simulasi daripada perspektif pengguna lain.
Papar Butiran Teknikal: katif/nyahaktif Pilihan ini berguna semasa menggunakan perkhidmatan Sokongan SAP.
Jenis RFQ
Pilih jenis RFQ diperlukan untuk tujuan anda.
Bergantung kepada tujuan RFQ anda, anda pilih salah satu daripada jenis RFQ berikut:
Permintaan Harga Luaran (RSI)
Jika anda hanya mahu meminta maklumat harga dan kuantiti atau kos penghantaran, permintaan dihantar ke Ariba Network.
Pembekal boleh cipta bida secara langsung ke Ariba Network dan hantarkan ia semula ke SAP S/4HANA, di mana anda akan diberikan satu daripadanya.
Permintaan Sumber Luaran (RE)
RFQ dihantar ke SAP Ariba Sourcing melalui Ariba Network, di mana pembekal boleh tempatkan bida mereka.
Anda diberi bida dalam SAP Ariba Sourcing dan hantarkan ia semula ke SAP S/4HANA.
Dalam SAP Ariba Sourcing, anda boleh pilih sama ada kontrak atau pesanan belian perlu dicipta untuk sebut harga dipilih.
Permintaan Sumber Dalaman (RQ)
Anda cipta permintaan harga dalam SAP S/4HANA dan hantar ia secara langsung ke pembekal anda melalui e-mel atau sebagai versi bercetak oleh mel.
Apabila anda terima sebut harga pembekal, anda boleh cipta ia secara manual dalam SAP S/4HANA.
Anda hanya boleh pilih jenis RFQ sekali.
Sebaik sahaja anda memilih jenis RFQ, medan ini tidak lagi boleh diedit.
Jika anda mengubah pandapat dan mahu mencipta RFQ bagi jenis lain, anda boleh batalkan RFQ dicipta yang baru dan cipta RFQ lain.
Isihan mengikut Tarikh Permulaan
Pilihan dipilih menentukan sama ada pesanan untuk diproses diisih mengikut tarikh permulaan asas atau tarikh permulaan berjadual.
Tentukan cara pesanan untuk diproses:
Isihan mengikut Tarikh Permulaan Asas:
Pesanan untuk diproses diisih mengikut tarikh permulaan asas
Isihan mengikut Tarikh Permulaan Berjadual:
Pesanan untuk diproses diisih mengikut tarikh permulaan berjadual
Paparan Sejarah Perubahan
Papar semua perubahan digunakan kepada penyelesaian cloud anda yang sedang berjalan.
Aplikasi ini menyenaraikan semua projek perubahan yang diselesaikan dalam sistem ujian dan dikerahkan kepada penyelesaian berjalan.
PEMBUKAAN PROTOKOL PERUBAHAN
Untuk buka protokol projek perubahan yang lengkap pilih >.
Protokol memaklumkan anda mengenai projek perubahan, pasukan projek, hasil ujian dan aktiviti konfigurasi.
Anda boleh muat turun protokol perubahan dalam format PDF.
Umpukkan Sebab Sekatan untuk Jenis Pengebilan
Takrif penunjuk sekatan yang mungkin dan peruntukkannya untuk jenis pengebilan yang dikehendaki.
Sekatan yang berikut adalah berkemungkinan:
Anda boleh sekat pelanggan untuk pengebilan.
Jika pelanggan akan disekat untuk pengebilan, masukkan penunjuk dalam data sekatan rekod induk pelanggan.
Spesifikasi dalam rekod induk pelanggan dan oleh itu sekatan untuk dokumen pengebilan juga digunakan sama ada untuk semua atau kawasan jualan individu.
Sistem SAP menyalin spesifikasi dari rekod induk pelanggan ke dalam dokumen jualan.
Untuk pelanggan dalam kawasan jualan yang terlibat, anda tidak boleh mencipta dokumen pengebilan jika sekatan digunakan untuk jenis pengebilan pelanggan.
Anda boleh menyekat dokumen jualan individu untuk pengebilan secara manual.
Dokumen jualan juga boleh disekat untuk pengebilan secara automatik melalui sistem SAP.
Dalam permintaan memo kredit dan permintaan memo debit sistem SAP, contohnya, diberikan sekatan pengebilan secara automatik.
Untuk menetapkan sekatan penegbilan secara automatik apabila mencipta dokumen jualan tertentu, anda perlu mentakrif sekatan pengebilan untuk jenis dokumen jualan.
Untuk melakukan ini, anda tentukan sekatan pengebilan bagi jenis dokumen jualan ini.
Anda akan menjumpai penunjuk sekatan pengebilan dalam data perniagaan umum dalam pengepala pesanan.
Jika dokumen jualan disekat untuk pengebilan, anda tidak boleh mencipta dokumen pengebilan jika sekatan digunakan untuk jenis pengebilan dokumen ini.
Anda hanya boleh mencipta dokumen pengebilan, jika anda telah buang penunjuk sekatan secara manual.
Anda boleh sekat item individu dokumen jualan untuk pengebilan secara manual.
Item juga boleh disekat untuk pengebilan secara automatik melalui sistem SAP.
Untuk perkara ini berlaku, anda perlu mentakrif sekatan pengebilan bagi kategori item yang sepadan yang kemudiannya ditetapkan secara automatik apabila dokumen jualan dicipta.
Untuk lakukan ini, tentukan sekatan pengebilan bagi kategori item (lihat bahagian Takrif kategori item untuk dokumen jualan).
Penunjuk hanya digunakan untuk item dan tidak disalin ke dalam pengepala dokumen jualan.
Anda akan menjumpainya dalam data perniagaan umum bagi item.
Anda perlu padam sekatan secara manual bagi mengeluarkan item untuk pengebilan.
Zon Waktu untuk Permulaan Kerja
Pilih zon waktu.
Jika anda menetapkan zon waktu yang berbeza daripada zon waktu pelayan anda, sistem mungkin membuat pelarasan untuk kerja penjadualan.
Zon waktu anda ialah CEST (UTC + 2:00) dan zon waktu yang digunakan oleh pelayan anda ialah UTC.
Tarikh Tamat Asas Berkaitan ditetapkan kepada -30.
Status untuk Status Sistem 1 ditetapkan kepada Dikeluarkan.
Anda menjadualkan kerja untuk tarikh 31 Julai 2019 pada pukul 1 pagi.
Sistem akan menutup semua pesanan yang telah dikeluarkan pada 30 hari lalu mengikut waktu pelayan.
Maksudnya, pesanan yang dikeluarkan pada 30 Jun 2019.
Pilih Medan Pertanyaan
Pilihan ini membenarkan anda memilih medan pertanyaan yang diperlukan daripada Paparan Data.
Medan dalam jadual “Medan Tersedia” mewakili medan “Paparan Data”.
Dalam jadual “Medan Tersedia”, pilih “Pilih” untuk menambah medan dalam “Medan Dipilih”.
Medan dalam jadual “Medan Dipilih” mewakili medan pertanyaan.
Penapis input pengguna yang merupakan sebahagian daripada Paparan Data juga muncul dalam jadual “Medan Dipilih”.
Anda tidak boleh keluarkan medan penapis input pengguna daripada pertanyaan.
Dalam lajur "Jenis", mewakili dimensi dan mewakili ukuran.
Kawalan Julat Tarikh - Bahagian Kebersandaran
Untuk Kadar Tarikh Berdasarkan Pada Kalendar Fiskal
Kalendar fiskal diumpukkan ke kod syarikat.
Contohnya, jika anda masukkan F001 sebagai kod syarikat dan klik senarai juntai bawah untuk kod syarikat, anda boleh lihat sebarang varian tahun fiskal, contohnya K4 yang diumpukkan ke kod syarikat tersebut.
Aplikasi mengira tempoh daripada varin tahun fiskal yang sah untuk gabungan lejar dan kod syarikat yang anda masukkan.
Berdasarkan pada maklumat ini, senarai juntai bawah untuk julat tarikh menunjukkan entri tambahan seperti tahun fiskal ke tarikh, tempoh fiskal ini, tempoh fiskal terakhir, suku fiskal atau tahun fiskal.
Jika anda memilih kod syarikat yang mempunyai perbezaan varian tahun fiskal, senarai juntai bawah untuk tawaran julat tarikh hanya julat tarikh berdasarkan kalendar biasa.
Log Ralat
Semak mesej ralat.
Bekas yang tidak diketahui oleh sistem atau tidak boleh diproses atau disimpan bertanda merah dalam senarai Dimasukkan.
Dalam senarai Disimpan, ralat dalam proses penambahan semula pendasar boleh berlaku.
Perkara ini boleh berlaku contohnya berpunca daripada kekurangan bahan pada sumber penambahan semula.
Umumnya, selepas ralat semasa Simpan, status bekas ditetapkan kepada "RALAT" dan mesti dikendalikan dalam aplikasi Pembetulan Kanban.
Mesej ralat yang sepadan ditunjukkan dalam bahagian butiran bagi bekas terjejas dan dalam log ralat.
Kawalan Julat Tarikh - Bahagian Penggunaan
Untuk pilih julat tarikh bagi item baris, anda boleh gunakan dua medan:
Medan pertama menunjukkan jenis unit masa, seperti julat tarikh, dari, hingga, hari ini atau minggu ini, bulan ini, tahun ini.
Anda juga boleh pilih julat tarikh yang berdasarkan kalendar fiskal, seperti tempoh fiskal ini, tempoh fiskal lepas, suku fiskal atau tahun fiskal.
Anda boleh klik senarai juntai bawah untuk lihat, pilihan yang tersedia.
Jika anda tidak ingin membuka senarai juntai bawah, hanya taip teks ke dalam medan untuk melihat entri yang ditawarkan.
Bergantung pada jenis unit masa yang anda pilih, anda boleh masukkan tarikh atau julat tarikh dalam medan kedua atau anda boleh klik simbol kalendar dan pilih tarikh daripada kalendar.
Tag
Guna medan ini untuk mencipta atau peribadikan tag anda sendiri kepada paparan CDS.
Anda guna medan ini untuk mencipta atau peribadikan tag anda sendiri kepada paparan CDS.
Pilih paparan, kemudian klik butang Tambah Tag.
Paparan berbilang boleh ditambah kepada tag yang sama.
Bilangan tag bagi paparan yang berkaitan dipaparkan sebagai pautan.
Klik pautan untuk urus tag.
Set Templat Tugas
Pilih set templat tugas.
Untuk setiap jenis hierarki, anda boleh umpukkan set templat tugas.
Set templat tugas digunakan sebagai model rujukan untuk proses penutupan entiti yang lengkap.
Ia menangkap tanggungjawab atau bahagian bagi organisasi atau tatacara dengan merujuk folder.
Folder ini mewakili langkah dan aktiviti oleh tugas pratakrif serta jujukan dan kebersandarannya.
Folder ini ialah nod hierarki tugas.
Sejarah Rancangan Ansuran
Sejarah rancangan ansuran menunjukkan item asal yang terdiri daripada rancangan ansuran.
Dalam sejarah rancangan ansuran, sistem merekod tempoh yang item sumbernya adalah sebahagian daripada rancangan ansuran.
Jika anda ingin sistem menjalankan kemas kini sejarah, kategori rancangan ansuran dan sebab penyahaktifan mestilah dikonfigurasikan (lihat Kewangan Perakaunan KontrakRancangan Ansuran Takrifkan kategori untuk Rancangan Ansuran atau Takrifkan Sebab Penyahaktifan untuk Rancangan Ansuran).
Untuk setiap rancangan ansuran, sistem mengemas kini secara automatik sejarah rancangan ansuran.
Kemudian, sistem juga mengemas kini sejarah apabila anda menyahaktifkan rancangan ansuran.
Sejarah rancangan ansuran merujuk kepada akaun belum terima asal dan menyimpan data berikut:
Kategori rancangan ansuran
Sebab penyahaktifan
Tarikh penyahaktifan (untuk dimasukkan apabila dinyahaktifkan)
Tarikh dan masa penyahaktifan (cap waktu)
Amaun baki terbuka apabila dinyahaktifkan
Anda mencapai sejarah rancangan ansuran seperti berikut:
Pilih aplikasi Papar Sejarah Rancangan Ansuran.
Jika anda mencipta rancangan ansuran dengan menggunakan aplikasi Selenggarakan Rancangan Ansuran, sistem dengan ikon memilih semua item terbuka yang sekali dalam rancangan ansuran.
Dengan klik dua kali pada ikon ini, anda boleh terus ke sejarah rancangan ansuran yang sepadan dengan item.
Ia memaparkan semua rancangan ansuran yang mengandungi item ini.
Jika anda memaparkan atau mengubah rancangan ansuran dengan menggunakan aplikasi Selenggarakan Rancangan Ansuran, pilih Selanjutnya Pergi ke Sejarah Rancangan Ansuran.
Jika anda memaparkan baki akaun pekongsi perniagaan dengan menggunakan aplikasi Papar Baki Akaun, pilih Selanjutnya Persekitaran Akaun Sejarah Rancangan Ansuran.
Varians
Maksud medan varians boleh dilihat dalam senarai hasil anda yang digariskan dalam senarai berikut:
Varians Harga Input
Perbezaan antara kos sasaran dan kos sebenar disebabkan oleh perbezaan antara harga terancang dan harga sebenar bagi barangan yang digunakan, atau perbezaan antara harga aktiviti terancang dan harga aktiviti sebenar.
Biasanya, varians harga input dikira dengan menambah perbezaan antara nilai terancang dan nilai sebenar melalui kuantiti yang digunakan.
Varians harga input ialah kategori varians yang dikemas kini ketika proses pengiraan varians.
Varians Kuantiti Input
Perbezaan antara kos sasaran (terancang atau belanjawan) dan kos sebenar yang terhasil daripada perbezaan antara kuantiti bahan terancang dan sebenar.
Varians Harga Output
Perbezaan antara kredit sebenar dan kredit sasaran.
Varians harga output muncul disebabkan syarat-syarat berikut:
Dalam Pengawalan Kos Overhed (CO-OM), varians harga output muncul apabila harga aktiviti digunakan adalah tidak sama seperti harga lelaran bulanan pada asas aktiviti terancang (contohnya, harga aktiviti dimasukkan secara manual)
Dalam Pengawalan Objek Kos (CO-PC-OBJ), varians harga output muncul apabila bahan yang dihasilkan dipindahkan ke inventori pada harga lebih daripada harga piawai (contohnya, pergerakan harga purata)
Varians Kuantiti Output
Perbezaan antara kredit sebenar dan kredit sasaran disebabkan oleh perbezaan antara kuantiti sebenar yang diperuntukkan dan diposkan secara manual.
Pengiraan varians mengira varians kuantiti output dengan tempoh dan elemen kos menggunakan formula berikut:
Varians kuantiti output = (Kuantiti sebenar - Kuantiti sebenar manual) x Harga aktiviti sebenar
Varians kuantiti output tetap= (Kuantiti sebenar - Kuantiti sebenar manual) x Harga aktiviti sebenar tetap
Perbezaan yang disebabkan oleh kedua-dua perbezaan harga output dan perbezaan kuantiti output tidak diumpukkan kepada varians kuantiti output tetapi dilaporkan sebagai varians harga output.
Jika aktiviti mengambil bahagian dalam prapengagihan kos tetap, kredit sasaran tetap tidak berkadar dengan kadar operasi.
Baki Varians Input
Varians pada bahagian input yang tidak boleh diumpukkan kepada mana-mana kategori varians berikut:
Varians harga input
Varians kuantiti input
Varians penggunaan sumber
Sekerap
Varians Penggunaan Sumber
Perbezaan antara kos sasaran dan kos sebenar disebabkan oleh perbezaan komponen input (seperti bahan mentah) sedang digunakan daripada yang dirancang.
Varian Harga Bercampur
Kategori varians pada bahagian output yang menunjukkan varians antara harga piawai yang dikira dalam anggaran kos bercampur bagi pelbagai alternatif perolehan (versi perolehan) dan anggaran kos bagi alternatif perolehan tunggal.
Varians Sekerap
Peratusan bahan yang tidak memenuhi keperluan kualiti.
Baki Varians
Perbezaan antara kos sasaran dan kos yang tidak boleh diatribut ke kategori varians tunggal.
Yang terakhir boleh berlaku jika tiada kategori varians ditentukan dalam varian varians.
Varians Saiz Lot
Perbezaan antara kos tetap terancang dan kos tetap sebenar diperuntukkan.
Varians saiz lot muncul apabila sebahagian daripada jumlah kos pesanan atau hierarki objek kos kekal sama dengan perubahan kuantiti yang dikilangkan.
Kunci Perancangan Kos Sekunder
Kunci pusat kos untuk perancangan kos sekunder.
Apabila pilihan ini didayakan, tiada kos sekunder boleh dirancang untuk pusat kos.
Pilihan ini mengunci pusat kos terhadap debit dengan kos sekunder terancang.
Walau bagaimanapun, pusat kos masih boleh dikreditkan dengan kos sekunder terancang.
Tetapan lalai untuk pilihan ini adalah berdasarkan pada tetapan Kategori Pusat Kos.
Kos sekunder digunakan untuk peruntukan kos dalaman dalam Pengawalan.
Berikut tidak menjejaskan data dalam Perakaunan Kewangan.
Status Kelengkapan
Tapis mengikut status kelengkapan.
Anda boleh menapis mengikut status kelengkapan.
Nilai berikut adalah mungkin:
Aset Lengkap, iaitu semua entri rekod yang diperlukan telah dibuat.
Aset Boleh Diposkan Tidak Lengkap, iaitu aset tidak lengkap tetapi entri yang diperlukan untuk pengeposan telah dibuat.
Aset Tidak Lengkap, dan ia tidak boleh diposkan.
Hal ini bermaksud ciri penting hilang, seperti peruntukan bagi bahagian perniagaan.
Hal ini boleh berlaku disebabkan oleh ralat teknikal atau jika aset ialah aset dalam pembinaan yang dicipta secara automatik untuk ukuran pelaburan dan sistem tidak dapat melengkapkan semua medan menggunakan ukuran pelaburan.
Aset tidak lengkap tidak boleh dinyahaktifkan atau dipindahkan.
Selain itu, ia dikenal pasti sebagai mempunyai ralat semasa penutupan akhir tahun.
Kemasukan Cukai
Jika anda ingin mengambil cukai semasa entri dokumen, anda boleh memasukkan cukai secara manual atau mempunyai sistem yang mengiranya secara automatik dengan menggunakan aplikasi Poskan Dokumen.
Dalam skrin asal entri dokumen di bawah Cukai, anda boleh menentukan sama ada anda ingin memasukkan cukai secara manual atau menentukannya secara automatik.
Untuk melakukannya, pilih butang radio yang sepadan.
Untuk masukkan data cukai secara manual, masukkan data berikut yang diperlukan untuk pengiraan cukai dalam item pekongsi perniagaan atau item G/L:
Kod Cukai
Asas Cukai
Untuk pengeposan dengan kod bidang kuasa cukai, tetapkan penunjuk Bidang Kuasa Cukai pada skrin asal dalam kotak kumpulan Cukai.
Kemudian, masukkan Kod Bidang Kuasa Cukai dan tarikh cukai dalam item pekongsi perniagaan atau item G/L.
Sistem mencadangkan tarikh pengeposan sebagai tarikh cukai.
Sistem mengira amaun cukai secara automatik.
Untuk tentukan data cukai secara automatik, masukkan kod cukai dalam item pekongsi perniagaan.
Jika perlu, sistem secara automatik menentukan tarikh cukai dari tarikh pengeposan dan kod bidang kuasa cukai daripada butiran pekongsi perniagaan tertentu dalam akaun kontrak.
Sistem menjumlahkan amaun daripada item pekongsi perniagaan untuk setiap kod cukai atau untuk setiap gabungan kod cukai, tarikh cukai dan kod bidang kuasa cukai.
Daripada jumlah tersebut, sistem menentukan amaun bersih (amaun asas cukai) dan amaun cukai.
Apabila anda mengeposkan dokumen, sistem mencipta item baris untuk cukai secara automatik.
Item yang menghasilkan cukai dipaparkan di bahagian bawah semua skrin senarai.
Item cukai sendiri dipaparkan pada skrin senarai berasingan; pilih fungsi Cukai.
Dalam paparan dokumen, item cukai muncul pada skrin paparan keseluruhan di bahagian item G/L.
Ia menyumbang pada baki dokumen.
Anda perlu membezakan antara item cukai dan item baris yang menghasilkan cukai.
Item Baris yang Menghasilkan Cukai
Di sini, anda memasukkan kod cukai, bidang kuasa cukai dan tarikh cukai.
Item baris yang menghasilkan cukai boleh menjanakan beberapa item cukai.
Anda memasukkan item baris ini yang menghasilkan cukai di bahagian bawah skrin senarai (untuk item pekongsi perniagaan atau item G/L).
Item Cukai
Anda tidak boleh memasukkan item cukai.
Dengan menggunakan fungsi Cukai, anda boleh memaparkan item cukai.
Apabila anda memadamkan item baris yang menghasilkan cukai, maka semua item cukai yang dijanakan juga dipadam dari sistem.
Penapis Status Pengusiaan
Tapis objek pengusiaan data berdasarkan status pengusiaan.
Anda boleh tapis mengikut status berikut:
Semua:
Tapis untuk semua status pengusiaan.
Semua status merupakan nilai lalai untuk penapis ini.
Didayakan - Pengusiaan Dimulakan:
Status ini menunjukkan bahawa objek adalah aktif dan jalanan pengusiaan berjadual untuk objek pengusiaan data yang dipilih.
Didayakan - Pengusiaan Tidak Dimulakan:
Status ini menunjukkan bahawa objek akan diaktifkan secara automatik ketika jalanan pengusiaan data berjadual seterusnya untuk objek ini.
Tidak Didayakan:
Menunjukkan bahawa objek pengusiaan data dipilih adalah tidak aktif dan tidak boleh digunakan dalam jalanan pengusiaan.
Hantar Notis Dunning
Hantar semua notis dunning yang tidak disekat.
Apabila anda menghantar notis dunning, mereka terus kepada pelanggan untuk meminta pembayaran.
Sistem akan prom anda untuk memilih kaedah output keutamaan anda.
Semua notis yang tidak disekat dalam proposal dihantar dan anda harus sedar bahawa ia boleh termasuk notis yang tidak dapat dilihat pada masa itu disebabkan tetapan penapis anda.
E-mel dihantar kepada kerani syarikat pekongsi sekiranya alamat ditentukan dalam data induk pelanggan.
Jika tiada alamat kerani ditentukan, e-mel akan masuk ke alamat e-mel piawai syarikat pekongsi dan sekiranya ia tidak tersedia, maka alamat e-mel disenaraikan di bawah Komunikasi Tidak Bersandar Alamat.
Jika tiada e-mel pelanggan tersedia, mel akan dihantar kepada pengguna untuk dikirim semula secara manual.
Ambil perhatian bahawa notis tidak boleh diproses sekiranya cadangan dicipta dengan item yang diumpukkan lebih daripada seorang pengguna.
Isu ini perlu diselesaikan semula oleh pentadbir sistem.
Susut Nilai Berubah
Bahagian
Peratusan bahagian susut nilai berubah dalam susut nilai berkala.
Kadar peratusan yang menentukan bahagian susut nilai berubah bagi susut nilai berkala.
Sistem menggunakan bahagian susut nilai berubah dengan cara berikut:
Apabila anda menggunakan susut nilai dengan faktor berbilang syif, sistem mendarabkan bahagian susut nilai berubah dengan faktor berbilang syif.
Apabila anda memindahkan susut nilai terancang ke perancangan kos, bahagian susut nilai berubah dan bahagian tetap bagi susut nilai dikendalikan secara berasingan.
Strategi
Menyenaraikan strategi penggantian yang memenuhi kriteria carian tertentu.
Subskrin Strategi menyenaraikan semua strategi penggantian atau sesuatu yang memenuhi mana-mana penapis carian tertentu.
Dengan navigasikan ke skrin seterusnya, anda boleh papar maklumat am mengenai strategi penggantian, kaedah penggantian dan peraturan pembinaan.
Fungsi piawai tersedia untuk mencipta, memapar, mengubah dan memadam strategi:
Untuk papar atau ubah strategi penggantian, klik pada entri yang sepadan dalam senarai.
Untuk padam strategi penggantian, benderakan entri dalam senarai dan pilih Padam.
Ambil perhatian bahawa strategi penggantian yang digunakan secara aktif dalam aplikasi Konfigurasikan Kawalan Alternatif tidak boleh dipadam daripada pangkalan data.
Strategi penggantian yang bukan dalam penggunaan aktif boleh dipadam daripada pangkalan data tanpa apa-apa sekatan.
Kitaran Hayat
Pratakrif klausa pembaharuan dan penamatan untuk transaksi undang-undang.
Aspek ini mempunyai dua subaspek:
Pembaharuan dan Penamatan:
Anda boleh pratakrif klausa pembaharuan dan penamatan untuk transaksi undang-undang pada tahap konteks.
Semua Tarikh:
Anda boleh lihat semua tarikh yang dijanakan secara automatik apabila klausa pembaharuan dan penamatan adalah pratakrif.
Tambah Folder Baru
Tambah folder baru dalam blok binaan
Anda boleh menstrukturkan aktiviti blok binaan dengan mencipta folder.
Gunakan fungsi ini dalam butiran blok binaan atau dalam subfolder blok binaan.
Untuk menambah folder:
Masukkan nama dan perihalan folder baru.
Simpan.
