Disalin
Senarai item yang dimuat naik bagi ID yang telah wujud dalam sistem sasaran.
Senaraikan peraturan, kaedah dan pemilihan yang dimuat naik dari hamparan dan mempunyai ID yang sama dengan yang sedia ada dalam sistem semasa anda.
Item sedia ada mungkin mempunyai status Aktif, Draf atau Tidak Aktif.
Oleh itu, anda perlu membandingkan pendua dan menentukan sama ada anda ingin langkau item dimuat naik atau importnya supaya item sedia ada ditulis ganti.
Jika anda pilih untuk mengimport juga item pendua, hanya versi draf bagi item sedia ada ditulis ganti kerana semua item yang diimport mempunyai status awalan Draf.
Walau bagaimanapun, tindakan Pengaktifan Besar-besaran berikutan boleh mengaktifkan item diimport ini dan menulis ganti peraturan, kaedah atau pemilihan sedia ada.
Konteks
Gunakan medan ini untuk mencari transaksi undang-undang dengan konteks ini.
Anda menggunakan medan ini untuk mencari transaksi undang-undang yang mempunyai konteks masing-masing yang diumpukkan.
Syarat rangka set konteks untuk pemetaan senario perniagaan tertentu atau status untuk kandungan undang-undang yang anda minta.
Konteks menentukan maklumat yang perlu disediakan dalam permintaan kandungan undang-undang dan proses yang digunakan.
Konteks dikenal pasti oleh nama pengguna takrifan dan ID konteks yang diumpukkan oleh sistem.
Julat nombor digunakan untuk ID ialah pratakrifan dalam Penyesuaian.
Anda boleh panggil bantuan nilai untuk medan carian Konteks.
Konteks
Guna medan ini untuk mencari konteks khas.
Syarat rangka set konteks untuk pemetaan senario perniagaan tertentu atau status untuk kandungan undang-undang yang anda minta.
Konteks menentukan maklumat yang perlu disediakan dalam permintaan kandungan undang-undang dan proses yang digunakan.
Konteks dikenal pasti oleh nama pengguna takrifan dan ID konteks yang diumpukkan oleh sistem.
Julat nombor digunakan untuk ID ialah pratakrifan dalam Penyesuaian.
Anda boleh panggil bantuan nilai untuk medan carian Konteks.
Tetapkan Sekatan Pengebilan
Anda boleh sekat pesanan jualan untuk pengebilan.
Anda boleh tetapkan sekatan pengebilan untuk pesanan jualan pada aras pengepala.
Pilih satu atau lebih pesanan jualan dan prosesnya sekaligus.
Semasa anda tetapkan sekatan pengebilan, anda perlu memberikan sebab.
Anda tidak boleh tetapkan sekatan pengebilan untuk pesanan jualan dalam status Dilengkapkan.
Anda ingin gunakan sekatan pengebilan untuk dokumen tertentu supaya harga boleh disemak sebelum pemprosesan tertentu.
Syarat Pembayaran
Dalam langkah ini, anda mentakrif peraturan yang sistem boleh tentukan syarat pembayaran yang diperlukan secara automatik.
Anda umpukkan syarat pembayaran yang ditentukan untuk pembekal dan pelanggan dalam rekod induk melalui kod untuk syarat pembayaran.
Syarat yang ditentukan dengannya dicadangkan apabila semasa memasukkan invois pembekal atau invois pelanggan.
Anda boleh gunakan kod sama untuk syarat pembayaran bagi kedua-dua pelanggan dan vendor yang mempunyai syarat pembayaran yang sama.
Anda juga boleh menggunakan kod syarat pembayaran berbeza untuk pembekal dan pelanggan serta hadkan jenis akaun yang dibenarkan sewajarnya dalam syarat pembayaran.
Dengan melakukan sedemikian anda boleh contohnya menyesuaikan syarat sampingan untuk pelanggan sahaja tanpa menjejaskan pembekal dengan syarat pembayaran yang sama.
Kedudukan
Menandakan kedudukan keperluan dalam jujukan.
Kedudukan nilai dalam jujukan menandakan kedudukan nilai.
Contohnya, jika anda mentakrifkan jujukan yang berdasarkan atribut pihak pembeli, keperluan untuk pihak pembeli dengan kedudukan 1 adalah keutamaan yang diberikan ke atas keperluan daripada pihak pembeli dengan kedudukan 2.
Jika jujukan mengandungi nilai yang berbilang dengan keutamaan yang sama (contohnya, pengguna berbilang bagi kepentingan sama), anda boleh mengumpukkan semuanya pada kedudukan yang sama.
Jika anda melakukannya, segmen yang sepadan mesti mengandungi atribut isihan yang menjamin keutamaan yang jelas bagi semua keperluan dalam jalanan pemprosesan tertangguh selanjutnya.
Apabila mengedit jujukan, anda boleh menggunakan butang Tetapkan Kedudukan atau butang piawai untuk alihkan nilai (contohnya, pelanggan) antara kedudukan dalam jujukan.
Gunakan Baki Pembukaan
Takrifkan sama ada baki pembukaan perlu digunakan.
Baki pembukaan ialah baki semua entri akaun sebelum pengeposan dokumen yang dipilih.
Baki pembukaan sama dengan baki penutupan yang dibawa ke hadapan daripada pengeposan dokumen sebelumnya.
Baki pembukaan dikira berdasarkan pada tempoh perakaunan yang ditentukan dalam penapis Julat Dokumen.
Apabila Gunakan Baki Pembukaan ditetapkan kepada Ya, baki pembukaan teragregat dipaparkan untuk semua entri yang diposkan ke akaun sebelum pengeposan dokumen yang dipilih.
Apabila Gunakan Baki Pembukaan ditetapkan kepada Tidak, baki pembukaan tidak dipaparkan.
Anda hanya boleh melihat entri individu yang diposkan ke akaun dari permulaan tempoh perakaunan yang ditentukan dalam penapis Julat Dokumen.
Guna dalam Kumpulan yang Serasi
Benarkan anda menggunakan hierarki baharu atau disemak dalam kumpulan yang serasi.
Semasa mencipta dan mengedit hierarki, anda boleh pilih Gunakan dalam Kumpulan yang Serasi.
Penggunaan hierarki pusat kos dalam kumpulan yang serasi memudahkan peruntukan anda dengan mengagregatkannya ke dalam peruntukan pusat berdasarkan pada jurnal sejagat.
Sila ambil perhatian bahawa anda boleh pilih untuk menggunakan hierarki atau tidak dalam kumpulan tetapan yang serasi semasa mencipta dan mengedit.
Pilihan ini tidak tersedia semasa anda menyalin hierarki.
Setelah anda menyalin hierarki, anda kemudiannya boleh masuk ke dalam mod edit untuk memilih sama ada anda ingin menggunakan hierarki dalam kumpulan tetapan yang serasi.
Sila ambil perhatian bahawa semasa anda menyimpan hierarki diedit, sistem menyemak sama ada perihalan hierarki melebihi 15 aksara.
Jika demikian, ia mendorong anda untuk edit perihalan hierarki untuk padankan dengan had 15 aksara untuk perihalan.
Sila ambil perhatian juga bahawa tetapan lalai untuk hierarki baharu adalah untuk digunakan dalam kumpulan tetapan yang serasi.
Jika anda tidak ingin lakukan demikian, anda harus nyahpilih pilihan ini.
Pengeditan Draf
Edit draf
Anda hanya boleh edit objek jenis Paparan CDS Tersuai.
Jika ia belum wujud lagi, draf baru paparan CDS dicipta.
Jika paparan telah diterbitkan, draf wujud dalam selari.
Anda edit draf objek sehingga anda terbitkan paparan.
Paparan CDS sebelum dihantar tidak boleh diedit.
Item Konfigurasi
Kumpulan langkah konfigurasi
Kumpulan langkah konfigurasi.
Pilih baris untuk melihat langkah konfigurasi dibutirkan.
Item konfigurasi (atau pelaksanaan) mungkin mengandungi langkah konfigurasi yang dilaksanakan dalam aplikasi pengguna akhir.
Untuk langkah konfigurasi, anda akan melihat butang Pergi ke Aplikasi bukannya butang Konfigurasi.
Pilih butang Pergi ke Aplikasi untuk membuka aplikasi pengguna akhir.
Disebabkan langkah konfigurasi dilaksanakan dalam aplikasi pengguna akhir, perubahan tidak boleh dipindahkan dari sistem Q ke sistem P.
Buat Semula dalam Sistem P ditetapkan kepada Ya.
Unjuran Stok
Aras penimbal dan stok diunjurkan melebihi tempoh masa.
Di sini, anda boleh melihat aras penimbal dan stok diunjurkan melebihi tempoh masa.
Dengan menggunakan graf ini, anda boleh menilai secara visual stok diunjurkan yang berada pada zon merah, kuning, dan hijau.
Berdasarkan perkara ini, anda boleh menggunakan ciri lain bagi aplikasi, seperti mencipta, mengedit, atau memadam pesanan dan elemen MRP lain untuk melaraskan stok anda mengikut keperluan anda.
Menggunakan petunjuk, anda boleh melihat warna dan bentuk yang dipaparkan pada graf.
Tambahan pula, anda boleh melihat perkara yang ditunjukkan oleh zon, dan maksudnya untuk stok anda yang diunjurkan muncul dalam salah satu daripada zon ini di sini:
Zon merah
Zon penimbal menandakan keterukan paling tinggi dalam penimbal stok, menunjukkan aras stok rendah dan segera diperlukan untuk penambahan semula.
Zon kuning
Zon penimbal menandakan keterukan sederhana dalam penimbal stok, menunjukkan keperluan untuk penambahan semula/
Zon hijau
Zon penimbal menandakan keterukan paling rendah dalam penimbal stok.
Jika stok tersedia berada dalam zon ini, terdapat stok mencukupi tersedia untuk memenuhi permintaan semasa dan tiada pesanan bekalan lanjutan perlu dicipta.
Status Pemenuhan
Tunjukkan status pemenuhan paling relevan bagi proses pemenuhan atau dokumen perniagaan.
Tunjukkan status pemenuhan paling relevan bagi proses pemenuhan atau dokumen perniagaan:
• Proses pemenuhan (nod teratas)
Tunjukkan status pemenuhan digabungkan untuk penghantaran dan invois:
• Status Penghantaran
Pengagregatan bagi semua penghantaran status penghantaran dan jumlah status penghantaran bagi pesanan jualan, contohnya, Dalam Pesanan, Tidak Dihantar, Dihantar Separa, Dihantar Sepenuhnya.
• Status Invois
Pengagregatan semua penghantaran status invois dan status invois bagi pesanan jualan semasa, contohnya, Tidak Diinvoiskan, Diinvoiskan Separa, Diinvoiskan Sepenuhnya.
Contoh bagi status pemenuhan diagregat untuk status di atas ialah Dihantarkan Separa / Diinvoiskan Separa.
Objek perniagaan yang sepadan di bawah nod teratas termasuk:
• Pesanan Jualan
Tunjukkan status penghantaran jika relevan, contohnya, Dihantarkan Separa.
• Penghantaran
Tunjukkan status penghantaran, contohnya, Dihantarkan Separa.
• Invois
Tunjukkan status perakaunan, contohnya, Dokumen pengeposan telah dicipta.
Muat Turun Maklumat Paparan CDS ABAP
Muat turun metadata dan anotasi untuk paparan CDS ABAP
Dengan aplikasi Papar Replikasi, paparan CDS ABAP dalam sistem SAP S/4HANA direplikasikan sebagai paparan CDS HANA kepada sistem sasaran SAP Cloud Platform (SCP).
Oleh kerana sintaks sistem sumber dan sasaran adalah berbeza, anda boleh muat turun anotasi dan metadata untuk paparan CDS ABAP supaya anda boleh mengubah paparan yang dijanakan dalam sistem sasaran.
Pilih paparan CDS dan pilih Muat Turun Maklumat Paparan CDS ABAP untuk simpan ia dalam format JSON:
Anotasi
Metadata
Kumpulan Pengguna
Kumpulan pengguna mengumpulkan pengguna teknikal mengikut ciri biasa.
Di sini anda boleh takrifkan kumpulan pengguna yang diperlukan bagi pengguna teknikal anda.
Terdapat beberapa jenis pengguna teknikal yang menjalankan tugas teknikal dalam sistem anda:
Pengguna Teknikal SAP
Pengguna ini pratakrif oleh SAP untuk menjalankan tugas operasi dalam sistem.
Pengguna teknikal SAP juga diperlukan untuk tugas tertentu pelanggan, seperti kerja berjalan dan penjadualan.
Templat kerja diperlukan mengandungi pengguna teknikal SAP yang diperlukan untuk menjalankan kerja mengikut lalai.
Pengguna Komunikasi
Pengguna komunikasi ialah pengguna teknikal yang diperlukan untuk komunikasi antara sistem anda dan mana-mana sistem bersepadu.
Jenis pengguna komunikasi berikut adalah tersedia:
Pengguna komunikasi SAP:
Pratakrif oleh SAP
Pengguna komunikasi:
Dicipta oleh pelanggan
Pengguna komunikasi tersuai dicipta dalam aplikasi Selenggara Pengguna Komunikasi dan diumpukkan ke sistem untuk komunikasi masuk dan keluar.
Pengguna teknikal ini menggunakan sama ada pengesahan atau perakuan asas untuk berkomunikasi antara sistem anda dan sistem bersepadu.
Sistem komunikasi, bersama dengan senario komunikasi, diumpukkan ke aturan komunikasi.
Oleh itu, semua fungsi senario komunikasi diumpukkan kepada pengguna komunikasi yang menyediakan pengguna ini dengan semua kebenaran yang diperlukan untuk sambungan antara sistem anda dan sistem bersepadu.
Pengguna Cetakan
Pengguna cetakan ialah pengguna teknikal yang digunakan oleh SAP Cloud Print Manager untuk log masuk ke sistem.
SAP Cloud Print Manager menerbitkan sambungan antara baris gilir cetakan dan pencetak tempatan.
Pengguna ini boleh dicipta dalam aplikasi Selenggara Baris Gilir Cetakan.
Pengguna Sokongan
SAP menggunakan pengguna sokongan untuk menyediakan pelanggan dengan sokongan jika isu berlaku dalam sistem.
Pengguna ini hanya wujud sementara dan dipadam oleh SAP selepas proses sokongan selesai.
Masukkan Akruan Kontrak Manual
Laraskan akruan
Membolehkan anda laraskan akruan.
Akruan manual adalah tulis ganti oleh penilaian semula, ini ialah, dengan sama ada berikut:
Fungsi Penilaian Semula dalam aplikasi ini
Jalanan pengecaman penilaian semula berkala dilaksanakan dengan aplikasi Jalankan Pengecaman Penilaian Semula - Dokumen Perkhidmatan
Fungsi akruan kontrak manual menjanakan dokumen sumber.
Tugas
Senaraikan semua tugas berkaitan kejadian dalam sistem Persekitaran, Kesihatan dan Keselamatan.
Anda boleh pratonton semua takrifan tugas dan tika tugas yang ditambah ke kejadian rekod.
Aplikasi memaparkan jumlah bilangan tugas dan memuatkannya dalam kelompok untuk menyokong prestasi aplikasi.
Aplikasi memaparkan semua tugas (termasuk atributnya seperti tajuk, jenis, status, tarikh akhir, pemproses dll.) dan mengisihnya mengikut tarikh akhir supaya semua tugas akhir lampau tempoh dan tamat tempoh dipaparkan terlebih dahulu.
Untuk membuka tugas diberikan bagi semakan atau pemprosesan, anda pilihnya daripada jadual.
Kemudian anda diubah salah ke takrifan tugas atau tika tugas sepadan untuk anda teruskan pemprosesan tugas.
Simulasi
Uji kesan pelarasan kedudukan menggunakan simulasi.
Anda boleh gunakan simulasi carian untuk menguji kesan pelarasan kedudukan anda dengan contoh carian.
Pilih entri daripada senarai objek perniagaan sebagai contoh carian.
Masukkan istilah carian di bahagian simulasi.
Gerakkan penggelongsor faktor kedudukan individu ke kiri (pengaruh kecil) atau kanan (pengaruh besar), dan anda boleh lihat cara urutan entri berubah dalam hasil carian simulasi.
Ubah penggelongsor sehingga anda mendapat urutan yang diinginkan.
Kemudian pilih Simpan.
Ambil perhatian bahawa simulasi tidak boleh meramal hasil carian dalam sistem pengeluaran dengan ketepatan yang lengkap kerana sistem pengeluaran mempunya lebih banyak lagi faktor penyumbang dan tetapan yang diperibadikan boleh mempengaruhi hasil.
Jika anda ingin jalankan simulasi daripada perspektif pengguna lain, masukkan pengguna dalam medan perspektif.
Anda juga boleh gunakan fungsi carian untuk memilih pengguna.
Ambil perhatian bahawa dalam hal ini, anda mesti nyahaktifkan tetapan sentiasa gunakan pengguna log masuk dalam simulasi dahulu dalam pilihan carian.
Kod Syarikat Global
Medan ini digunakan untuk:
Kod syarikat yang terlibat dalam entri dokumen untuk sistem SAP luaran (ICT) sebagai penghantar atau penerima.
Jenis kod syarikat ini mesti mempunyai ID kod syarikat merentasi sistem (seperti EUROPA) sebagai tambahan pada ID kod syarikat tempatannya (seperti 0001).
Kod syarikat yang disediakan untuk senario pengagihan ALE.
Apabila menghantar IDoc dengan data bersandar kod syarikat, kod syarikat digantikan dengan kod syarikat merentasi sistem dalam semua medan kod syarikat.
Apabila menerima jenis IDoc ini, penukaran balikan berlaku pada sistem sasaran.
Kod merentasi syarikat boleh menjadi maksimum panjang 6 aksara dan abjad angka.
Ralat Replikasi
Paparan ralat replikasi permintaan belian pusat.
Anda boleh memaparkan, menganalisis dan menyelesaikan ralat replikasi permintaan belian pusat.
Jika replikasi permintaan belian pusat dari sistem hub ke sistem bersambung menghasilkan ralat, permintaan belian pusat akan disimpan dalam status ditangguh dalam sistem bersambung.
Apabila anda jadualkan import seperti permintaan belian direplikasi dari sistem bersambung ke sistem hub, anda boleh memaparkan ralat replikasi berkaitan dengannya.
Setelah anda menganalisis semua ralat replikasi, anda boleh menyelesaikannya dalam sistem bersambung.
Permintaan belian pusat adalah yang dicipta dalam sistem hub.
Permintaan belian boleh dicipta dalam konteks senario berbeza, contohnya, permintaan pusat.
Varian Berkaitan
Senaraikan varian, strategi dan segmen global untuk segmen.
Lajur Varian Berkaitan menyenaraikan varian dalam segmen digunakan.
Dengan mengklik pada nombor dalam lajur Varian Berkaitan, anda juga boleh:
Papar strategi pengesahan untuk segmen diumpukkan.
Paparkan segmen global jika berkaitan.
Navigasikan pada aplikasi Konfigurasikan Varian BOP yang membolehkan anda memaparkan dan mengedit tetapan varian.
Ambil perhatian bahawa maklumat yang sama dipaparkan semasa anda menekan butang Tunjukkan Varian Berkaitan pada skrin Perihalan Segmen BOP.
Carian mengikut Julat Tarikh
Cari kontrak jualan dengan menapis julat tarikh.
Anda kini boleh menentukan julat tarikh dalam penapis Tarikh Dokumen dan menggunakannya untuk mencari semua kontrak jualan yang dihantar dan diterima dalam julat tarikh.
Anda mentakrif tempoh masa sebagai julat tarikh daripada 1 Jun 2019 hingga 30 Jun 2019 dalam penapis Tarikh Dokumen.
Hasil carian dalam senarai menunjukkan hanya kontrak jualan yang dihantar atau diterima antara 1 Jun 2019 hingga 30 Jun 2019.
Anda juga boleh menentukan julat tarikh dalam penapisDicipta pada dan menggunakannya untuk mencari semua kontrak jualan yang dicipta dalam julat tarikh.
Untuk melakukannya, tambah penapis Dicipta pada ke paparan anda dengan menyesuaikan penapis.
Simulasi Bahan Pelbagai Tahap
Di sini anda boleh membuat simulasi bagi bil bahan pelbagai tahap.
Paparan ini menunjukkan anda bil bahan pelbagai tahap dengan semua komponennya.
Anda boleh membuka pemeriksa untuk memaparkan semua isu.
Anda mempunyai pilihan berikut untuk menyelesaikan isu kapasiti:
Ubah Sumber Bekalan
Jika sumber bekalan alternatif wujud dan terdapat isu kapasiti dengan sumber bekalan sebenar, anda boleh menyemak dan menentukan perubahan sumber bekalan.
Prapengeluaran
Untuk mengurangkan beban berlebihan kapasiti, anda mungkin dapat mempercepatkan pengeluaran komponen bahan dengan menggunakan slot kosong untuk prapengeluaran yang dicadangkan oleh sistem.
Pengimportan
Import data yang anda pilih.
Anda tidak perlu semak data secara aktif sebelum mengimportnya.
Data disemak apabila anda memilih Import.
Rekod data tanpa ralat atau amaran diimport dengan segera.
Sekiranya terdapat amaran pada rekod, import terganggu untuk rekod ini dan anda boleh cadangkan sama ada anda mahu mengabaikan amaran dan meneruskan import, atau membatalkan import dan mengubah data.
Rekod dengan ralat tidak boleh diimport.
Sebab ralat telah diselesaikan dan data akan diimport semula.
Semasa import, setiap rekod data disemak secara individu, bermakna walaupun terdapat rekod data dengan ralat, namun begitu rekod data tanpa ralat masih diimport.
ID Konteks
Pilih konteks untuk transaksi undang-undang anda.
Konteks ialah tamplat yang menyediakan rangka syarat untuk pemprosesan transaksi undang-undang.
Konteks menentukan maklumat yang perlu atau harus disediakan dalam permintaan kandungan undang-undang dan proses yang digunakan ke transaksi undang-undang.
Anda boleh masukkan konteks secara manual, atau menggunakan bantuan nilai untuk mencari bagi konteks tertentu.
Konteks boleh pratakrif satu atau lebih yang berikut:
Set kategori yang mengelaskan kandungan undang-undang
Pihak terlibat (diperlukan dan pilihan)
Hubungan satu atau lebih transaksi undang-undang yang takrifkan, contohnya, hubungan anak induk
Objek berpaut (diperlukan dan pilihan) untuk maklumat yang dipautkan ke kandungan undang-undang diperlukan, seperti pesanan belian atau pautan luaran
Tarikh (diperlukan dan pilihan) mentakrifkan rangka masa, seperti tarikh mula dan akhir atau kesahan, atau tarikh pembaharuan.
Mesej Situasi In-App
Perihalan situasi perniagaan yang telah berlaku dalam aplikasi.
Di sini anda boleh memasukkan mesej situasi yang menerangkan situasi perniagaan kepada pengguna akhir.
Apabila tika situasi berdasarkan pada jenis situasi berlaku, sistem memaparkan mesej ini dalam aplikasi sepadan.
Dalam Perihalan Pendek, nama templat piawai dipaparkan mengikut lalai.
Anda boleh menulis ganti nama ini.
Dalam Butiran, anda boleh memasukkan maklumat terperinci yang membantu pengguna perniagaan bertindak balas dengan situasi.
Perihalan templat piawai dipaparkan mengikut lalai.
Anda boleh menulis ganti perihalan ini.
Dalam teks mesej, anda boleh memasukkan sehingga 15 pemboleh ubah.
Sebaik sahaja anda memasukkan tanda kurungan dakap ({), senarai semua pemboleh ubah tersedia untuk jenis situasi ini dipaparkan daripada bahagian yang anda boleh pilih pemboleh ubah yang diperlukan.
Maklumat mesej berikut adalah pilihan:
Dalam URL, anda boleh menambah URL untuk mendapatkan maklumat lanjut bagi pengguna perniagaan. Contohnya, perihalan tatacara untuk menyelesaikan situasi.
Dalam Teks URL untuk Paparan, anda boleh memasukkan perihalan URL.
Pratonton Mesej menunjukkan semua perubahan yang anda lakukan pada medan teks mesej situasi dalam masa nyata.
Laksanakan rancangan ujian/Laksana dengan Varian
Laksanakan rancangan ujian dengan atau tanpa varian rancangan ujian.
Anda boleh laksanakan rancangan ujian melalui dua kaedah:
Laksanakan:
Untuk laksanakan rancangan ujian tanpa sebarang varian rancangan ujian
Laksanakan dengan Varian:
Untuk laksanakan rancangan ujian dengan varian rancangan ujian
Pelaksanaan mungkin mengambil beberapa masa bergantung pada nombor pemprosesan ujian dalam giliran latar belakang.
Status Objek Pengusiaan Data
Menunjukkan status objek pengusiaan data dipilih.
Objek pengusiaan data boleh memiliki sebarang status ini:
Aktif - Menunjukkan bahawa objek pengusiaan data dipilih adalah aktif dan boleh digunakan dalam jalanan pengusiaan.
Tidak Aktif - Menunjukkan bahawa objek pengusiaan data dipilih adalah tidak aktif dan tidak boleh digunakan dalam jalanan pengusiaan.
Didayakan untuk Pengaktifan - Menunjukkan bahawa objek diaktifkan secara automatik semasa jalanan pengusiaan data berjadual seterusnya untuk objek ini.
Kritikal - Menunjukkan beberapa jadual digunakan dalam objek pengusiaan data telah terlebih 70% bagi aras pengisian.
Kumpulan Jujukan Kapasiti
Menyenaraikan kumpulan jujukan untuk peruntukan kapasiti dan nilainya.
Subskrin Kumpulan Jujukan Jualan menyenaraikan kumpulan jujukan untuk peruntukan kapasiti bagi jujukan peruntukan produk.
Anda boleh menggunakan kumpulan jujukan kapasiti sebagai sumber alternatif bagi peruntukan produk yang disemak selepas semakan ketersediaan produk telah dilaksanakan.
Pengesahan daripada semakan ketersediaan produk sebelumnya ialah permintaan (tarikh dan kuantiti) bagi semakan peruntukan produk terhadap kapasiti.
Jika kuantiti tersedia dalam kumpulan jujukan kapasiti tidak mencukupi untuk memenuhi keperluan, kuantiti tersedia dalam kumpulan jujukan kapasiti seterusnya juga dipertimbangkan.
Seperti kumpulan jujukan jualan, kumpulan jujukan kapasiti digunakan mengikut keutamaannya.
Sah dari/hingga
Memaparkan rangka masa yang sah untuk hierarki ini.
Sila ambil perhatian bahawa bukan semua hierarki memerlukan rangka masa kesahan.
Dalam kes ini, medan ini memaparkan N/A untuk menunjukkan yang rangka masa kesahan tidak dapat digunakan untuk jenis hierarki ini.
Contohnya, hierarki akaun G/L dan hierarki segmen tidak memerlukan rangka masa kesahan.
Kedua-dua jenis hierarki memaparkan N/A dalam medan ini.
Tambahan lagi, mana-mana hierarki yang anda cipta menggunakan aplikasi Uruskan Jenis Hierarki Tersuai tidak bersandarkan masa dan memaparkan N/A di sini.
Penyelenggaraan Maklumat Cash Pool
Selepas cash pool ditakrifkan dalam aplikasi Uruskan Cash Pool, anda boleh menyelenggara akaun bank dan maklumat berkaitan yang lain untuk cash pool dalam data induk akaun bank.
Untuk melakukan sedemikian, teruskan seperti berikut:
Dalam aplikasi Uruskan Akaun Bank, buka rekod akaun bank, dan kemudian pergi ke bahagian Cash Pool.
Tentukan yang berikut:
Jika akaun bank digunakan sebagai akaun pengepala bagi cash pool, dalam bahagian Sebagai Akaun Pengepala, tentukan cash pool.
Jika cash pool ialah cash pool fizikal, tentukan Kaedah Pembayaran.
Untuk melakukan sedemikian, selepas anda menentukan medan Nama Cash Pool, tekan Masukkan untuk mendayakan medan Kaedah Pembayaran untuk pengeditan.
Jika akaun bank digunakan sebagai subakaun bagi cash pool, dalam bahagian Sebagai Subakaun, tentukan maklumat cash pool.
Nilai berikut hanya berkaitan apabila cash pool ialah cash pool fizikal.
Baki sasaran
Amaun pindahan minimum
Kaedah pembayaran
Simpan perubahan anda.
Tetapan Pengguna
Takrifkan tetapan peribadi anda untuk pemberitahuan e-mel dan pengganti.
Anda boleh takrifkan tetapan peribadi anda untuk pemberitahuan e-mel dan pengganti.
Anda boleh pilih untuk tidak terima pemberitahuan apa-apa e-mel.
Dan anda boleh takrifkan satu atau lebih pengganti tugas penutupan kewangan anda semasa ketidakhadiran anda.
Pengganti akan diberitahu bagi pihak anda semasa ketidakhadiran anda.
Di bawah Tetapan Pengguna, pilih pilihan Tiada E-mel jika anda tidak ingin menerima apa-apa e-mel daripada perkhidmatan pemberitahuan penutupan kewangan.
Di bawah Pengganti Pengguna, masukkan nama pengguna bagi pengganti yang perlu bekerja pada tugas penutupan kewangan semasa ketidakhadiran anda.
Cipta Varian Baru
Cipta varian data baru untuk mengedit data tindakan.
Varian data ialah set data unik.
Anda boleh cipta satu atau lebih varian data pada aras langkah proses ujian.
Anda boleh edit atribut data tindakan berikut:
Nilai:
Pilih Pemboleh Ubah Sistem menggunakan bantuan nilai.
Pengikatan Data::
Pilih Pengikatan Data menggunakan bantuan nilai.
Anda harus gunakan tab Varian untuk uruskan varian data pada aras rancangan ujian.
Penentuan dan Pengesahan
Laksanakan logik tersuai ke objek perniagaan tersuai anda.
Selepas anda telah terbitkan objek perniagaan tersuai, anda boleh gunakan corak berikut untuk tambah logik tersuai ke objek perniagaan tersuai:
Selepas pengubahsuaian
Corak ini digunakan untuk kira semula data dengan segera selepas tika nod telah dicipta atau diedit dan kemudian disimpan.
Logik bagi corak ini menulis ganti nilai medan seperti rentetan atau tarikh teks.
Sebelum Simpan
Corak ini digunakan untuk sahkan kekonsistenan tika nod dalam fasa simpanan.
Logik bagi corak ini menyemak nilai medan untuk ketepatan dan papar mesej ralat jika nilai medan tidak betul.
Masukkan Pelarasan Sementara
Laraskan kos jualan diperakui atau hasil diperakui
Membenarkan anda untuk melaraskan kos jualan diperakui atau amaun hasil diperakui secara manual.
Pelarasan ditulis ganti oleh penilaian semula seterusnya, iaitu, dengan mana-mana yang berikut:
Fungsi Penilaian Semula dalam aplikasi ini
Jalanan pengecaman hasil dilaksanakan dengan aplikasi Jalankan Pengecaman Hasil - Projek
Fungsi penilaian semula menjanakan dokumen sumber.
RUC_CONF_FIN_CM_CINGACCOUNTSFORRECEIVING
Jejak akaun penjelasan membuka transaksi yang memerlukan transaksi tambahan untuk menghasilkan tatakerja perniagaan yang lengkap.
Apabila anda memindahkan wang dari satu akaun bank syarikat ke akaun lain, sistem tidak mengepos debit secara langsung ke akaun bank syarikat penerima.
Sebaliknya, ia mengepos debit ke akaun penjelasan yang diumpukkan ke akaun bank syarikat penerima secara sementara.
Entri kredit ofset dipos ke akaun penjelasan pratakrif lain dalam carta akaun anda.
Entri kredit ini dipos sebaik sahaja anda mencipta permintaan pembayaran untuk memindahkan wang ke akaun bank syarikat penerima.
Apabila amaun masuk muncul pada penayta bank daripada akaun bank syarikat penerima, penyata bank akhirnya memproses pengeposan debit ke akaun bank syarikat penerima dan kredit ke akaun penjelasan.
Pengeposan ini melengkapkan pindahan pada pihak penerima.
Anda boleh tentukan akaun penjelasan untuk pindahan bank masuk berdasarkan kod syarikat, bank syarikat, kaedah pembayaran, mata wang, dan akaun bank syarikat.
Jika anda tidak tentukan mata wang, akaun penjelasan digunakan untuk semua mata wang.
Latar Belakang untuk Baris Gilir Cetakan
Dalam persekitaran cloud, sistem bahagian belakang tidak mempunyai sambungan ke pencetak tempatan dalam rangkaian pelanggan (contohnya, tiada capaian rangkaian persendirian maya tersedia).
Untuk menentukan sambungan ini, baris gilir cetakan dalam sistem cloud perlu dicipta mewakili saluran output ke pencetak tempatan.
SAP Cloud Print Manager perlu dipasang dalam rangkaian pelanggan ke semakan yang biasa melalui sambungan ke sistem bahagian belakang sama ada dokumen baru dalam baris gilir cetakan.
Jika sedemikian, SAP Cloud Print Manager mendapatkan semula dokumen ini dan menghantarkannya ke pencetak yang dikonfigurasi secara setempat.
Secara alternatifnya, anda boleh cetak secara langsung dokumen PDF dalam aplikasi Selenggara Baris Gilir Cetakan dalam mod pratonton.
Untuk maklumat lanjut, lihat Panduan Pantas SAP Cloud Print Manager yang anda boleh panggil secara langsung dalam aplikasi dengan mengklik Bantuan.
Dokumen ini hanya tersedia jika anda telah memasang SAP Cloud Print Manager.
Anda boleh muat turun dan pasang SAP Cloud Print Manager daripada aplikasi Pasang Perisian Tambahan.
Pautan Berkaitan:Pasang Perisian Tambahan
Sumber Diminta
Sumber ini merupakan sumber diminta oleh pengurus projek.
Sumber ini adalah calon pilihan projek pengurus.
Pengurus projek boleh meminta sumber tertentu apabila menambah fungsi kepada pakej kerja.
Jika mereka melakukannya, organisasi penghantaran sumber yang diminta ditambah secara automatik kepada permintaan sumber.
Jika sumber telah diminta dan belum diperuntukkan, anda akan melihat pautan Umpukan Cepat dalam lajur Tindakan.
Pautan ini membolehkan anda untuk mencipta umpukan seperti yang diminta oleh pengurus projek.
Semakan Pemisahan Duti
Tandakan risiko capaian berpotensi
Semakan Pemisahan Duti membolehkan pengguna untuk menentukan risiko berpotensi yang berkaitan dengan fungsi perniagaan terancang mereka.
Perkhidmatan analisis capaian mempunyai set parameter pratakrif untuk risiko dan risiko capaian kritikal Pemisahan Duti (pengasingan duti) yang dihantar dengan SAP S/4 HANA Cloud secara lalai.
Ia menganalisis semua capaian yang berkaitan dengan fungsi perniagaan terhadap parameter seperti risiko, jenis risiko atau tahap risiko serta menanda sebarang risiko atau pelanggaran berpotensi.
Contohnya:
Capaian Keselamatan dan Konfigurasi Sistem akan ditanda sebagai risiko capaian kritikal berpotensi.
Anda kemudiannya akan menentukan sama ada ia sesuai untuk mengumpukkan capaian ini ke fungsi.
Fungsi dengan capaian untuk Penyelenggaraan Vendor dan Pengeposan Invois akan ditanda sebagai mempunyai risiko Pemisahan Duti kerana anda tidak mahu individu dengan keupayaan untuk meluluskan dan membayar vendor.
Maklumat daripada analisis capaian membantu anda mengelakkan risiko capaian berpotensi daripada memasuki sistem anda dan dengan mengenal pasti risiko, ia membolehkan anda untuk membuat keputusan terhadap capaian yang akan dimasukkan dalam fungsi perniagaan.
Untuk maklumat lanjut, cari Paparan Keseluruhan Produk:
Perkhidmatan Analisis Capaian dan Senario Penyepaduan:
SAP S/4 HANA Cloud dalam versi Perkhidmatan Analisis Capaian anda pada SAP Help Portal.
Tarikh Tamat Tempoh
Rekod memo tamat tempoh automatik apabila tiba tarikh tamat tempoh.
Anda boleh tetapkan tarikh tamat tempoh untuk rekod memo yang perlu tamat tempoh secara automatik.
Anda mencipta rekod memo untuk pembayaran keluar.
Anda tetapkan tarikh pembayaran sebagai tarikh tamat tempoh.
Selepas tarikh ini, rekod memo tamat tempoh secara automatik.
Status kemudiannya diubah dari aktif ke tidak aktif.
Laksanakan semula
Laksanakan Semula Rancangan Ujian
Anda boleh laksanakan semula rancangan ujian dalam satu kaedah berikut:
Laksanakan:
Digunakan untuk laksanakan semula rancangan ujian tanpa apa-apa varian rancangan ujian.
Laksanakan dengan varian:
Digunakan untuk laksanakan rancangan ujian dengan varian rancangan ujian.
Anda juga boleh laksanakan semula Pascanaik taraf Rancangan Ujian gagal sahaja.
Masa pelaksanaan mungkin panjang bergantung kepada bilangan proses ujian dalam giliran.
Tambah Blok Binaan
Tambah blok binaan tersuai
Dengan fungsi ini anda boleh menambah blok binaan tersuai ke item skop Penyelesaian Kandungan Pelanggan Tambahan.
Untuk menambah blok binaan:
Masukkan nama (ID) blok binaan baru dalam ruang nama pelanggan SAP (bermula dengan Z).
Masukkan perihalan.
Simpan.
Laksanakan semula
Laksanakan Semula Rancangan Ujian
Anda boleh laksanakan atau laksanakan semula rancangan ujian dalam satu kaedah berikut:
Laksanakan:
Digunakan untuk laksanakan rancangan ujian tanpa apa-apa varian rancangan ujian.
Laksanakan dengan varian:
Digunakan untuk laksanakan rancangan ujian dengan varian rancangan ujian
Masa pelaksanaan mungkin panjang bergantung kepada bilangan proses ujian dalam giliran.
Simpan sebagai Versi Baru
Gunakan fungsi ini untuk mencipta versi baru bagi konteks.
Anda gunakan fungsi ini untuk mencipta versi baru bagi konteks.
Versi baru bagi konteks hanya boleh dicipta jika ia diumpukkan sekurang-kurangnya satu transaksi undang-undang dan perubahan besar digunakan, seperti menambah kategori.
Jika anda pilih Simpan sebagai Versi Baru dan konteks belum lagi diumpukkan ke transaksi undang-undang, mesej ralat meminta anda untuk menggunakan Simpan.
Jika anda simpan versi baru, dialog meminta anda untuk tetapkan status versi baru.
Anda boleh tetapkan status ke sama ada Bersedia atau Aktif.
Jika anda tetapkan status ke Aktif, sistem tetapkan status bagi versi sebelumnya ke Digantikan dan sambungan antara dua versi ditunjukkan oleh Digantikan Oleh dan medan Versi Sebelumnya dalam data umum konteks.
Transaksi undang-undang menyimpan versi konteks yang diumpukkan pada asalnya.
Versi baru hanya boleh diumpukkan ke transaksi undang-undang baru.
Tindakan dan Maklumat
Anda boleh pilih tindakan berdasarkan nilai penimbal yang dicadangkan dan papar maklumat penting
Anda boleh pilih tindakan berdasarkan pada perkara yang anda mahu lakukan dengan cadangan penimbal.
Jika anda pilih Terima Pakai, nilai penimbal yang dicadangkan untuk produk digunakan dan nilai baru dipaparkan bagi setiap zon penimbal.
Carta mikro juga dikemas kini.
Jika anda pilih Abaikan, nilai penimbal yang dicadangkan untuk produk diabaikan.
Apabila penyiapan tindakan berjaya, produk tidak lagi dipaparkan dalam senarai anda.
Anda juga boleh memaparkan maklumat mengenai pelarasan permintaan atau zon yang digunakan, perubahan kepada umpukan profil atau faktor profil, dan pada kali terakhir cadangan penimbal diterima pakai atau diabaikan.
Status Jalanan Terakhir
Memaparkan status jalanan bagi jalanan pengusiaan data yang dipilih.
Berikut ialah status yang boleh dimiliki oleh jalanan pengusiaan data:
Gagal- Menunjukkan yang jalanan pengusiaan data telah gagal.
Anda boleh semak sama ada objek pengusiaan data diumpukkan adalah aktif.
Dalam Proses- Menunjukkan yang jalanan pengusiaan data sedang berjalan.
Berjaya- Menunjukkan yang jalanan pengusiaan data berjaya.
Tidak Dimulakan- Menunjukkan yang nilai ambang belum dicapai untuk objek pengusiaan data bagi kumpulan pengusiaan data dipilih.
Jika sedemikian, jalanan pengusiaan data tidak perlu dilaksanakan.
Masa Pendulu Nyahganding
Paparkan masa pendulu nyahganding
Paparkan masa pendulu nyahganding (DLT).
DLT adalah jumlah masa pendulu paling lama bagi produk yang tidak ditimbal dalam jujukan yang diketuai oleh produk (berkaitan DD) ditimbal dalam Bil Bahan, tambah sehingga masa pendulu kumulatif untuk produk yang ditimbal.
Masa pendulu semasa dan dicadangkan dipaparkan dalam hari.
Perubahan dalam masa pendulu nyahganding ialah peratusan yang berbeza antara masa pendulu nyahganding semasa dan dicadangkan.
Sekiranya anda tidak pernah menjana cadangan penimbal untuk produk yang telah anda pilih, kemas kini masa pendulu nyahganding (DLT) adalah wajib untuk penjanaan cadangan penimbal baru.
DLT dikira secara automatik, melainkan anda memilih untuk tidak mengiranya, dalam mana-mana kes cadangan penimbal untuk produk tersebut tidak akan dijanakan.
Papar Kerja
Tentukan kerja yang akan dipaparkan dalam senarai kerja
Anda boleh pilih satu daripada nilai berikut dari senarai juntai bawah untuk tentukan kerja yang akan dipaparkan dalam senarai kerja:
Kepunyaan saya sahaja
Senarai memaparkan kerja yang diumpukkan kepada nombor personel anda sahaja.
Pasukan saya sahaja
Senarai memaparkan kerja yang diumpukkan kepada pekerja lain bagi pusat kerja anda.
Kerja yang diumpukkan kepada anda tidak dipaparkan.
Kepunyaan saya dan pasukan saya
Senarai memaparkan semua kerja yang diumpukkan kepada pekerja lain bagi pusat kerja anda atau kepada anda.
Untuk diumpukkan dalam pasukan saya
Senarai memaparkan semua kerja bagi pusat kerja anda yang belum diumpukkan kepada pekerja.
Tunggakan untuk Dijelaskan
Kira tunggakan harian untuk dijelaskan.
Kira tunggakan harian untuk dijelaskan.
Jika anda memilih parameter ini, tunggakan harian dikira untuk item yang dijelaskan selepas tarikh rujukan bagi pengiraan tunggakan harian.
Item juga kemudiannya dimasukkan apabila item matang dan senarai yang diisih telah ditentukan.
Tunggakan harian tidak dikira untuk item yang dijelaskan sebelum tarikh rujukan pengiraan tunggakan harian.
Contohnya, jika parameter ini dipilih, item yang melebihi 20 hari pada 31 Januari tetapi dijelaskan pada 2 Februari akan disenaraikan sebagai item matang dalam dokumen surat-menyurat yang dicipta pada 3 Februari.
Jika parameter ini tidak dipilih, item tidak lagi dianggap sebagai lampau tempoh kerana ia dijelaskan sebelum 3 Februari.
Paksa Kemas Kini Pakar Koleksi
Aktifkan untuk menulis ganti pakar koleksi untuk semua pekongsi perniagaan dalam segmen koleksi yang dipilih.
Jika penunjuk ditetapkan:
Anda boleh menulis ganti pakar koleksi dalam segmen koleksi yang dipilih.
Anda boleh mengeluarkan pakar koleksi sedia ada daripada segmen koleksi yang dipilih dengan membiarkan medan Pakar Koleksi kosong.
Jika penunjuk tidak ditetapkan:
Pakar koleksi sedia ada terkumpul jika mungkin.
Jika pakar koleksi tidak diumpukkan kepada kumpulan koleksi, pakar koleksi dimulakan dalam kes ini.
Status Komunikasi
Menunjukkan jika komunikasi telah dibuat untuk item pemadanan.
Menunjukkan cara komunikasi dan kandungan telah dibuat untuk item yang sepadan.
Status komunikasi berikut tersedia:
Belum Dimulakan:
Tiada komunikasi lagi.
Nota Ditambah:
Nota am ditambah.
Pemberitahuan Dihantar:
Pemberitahuan telah dihantar kepada seseorang untuk penjelasan.
Penerima menerima pemberitahuan dalam bar pengepala bagi ikon launchpad SAP Fiori (ikon ).
Oleh sebab aktiviti komunikasi berada dalam status kronologi, hanya status komunikasi terkini ditunjukkan dalam senarai.
Walau bagaimanapun, anda boleh memaparkan sejarah komunikasi dengan memilih status.
Kad Pembayaran
Anda boleh selenggara data induk Kad Pembayaran
Anda boleh daftar, edit dan padam kad pembayaran.
Daftar Kad Baru
Klik tanda tambah untuk menambah kad baru.
Masukkan ID Kad dan butiran lain dan klik Daftar.
Kemudian, Hub Pembayaran sambung ke pembekal perkhidmatan pembayaran.
Pada halaman Daftar Kad Pembayaran, masukkan butiran kad seperti jenis kad, nombor dan kod sekuriti.
Klik Serah.
Sebaik sahaja disahkan, kad baru ditambah ke Rekod Induk Pelanggan.
Nombor Kad terlindung untuk tujuan sekuriti.
Edit Kad
Untuk edit data kad pembayaran sedia ada,
Pilih entri kad yang anda ingin untuk ubah suai dan klik Edit.
Buat perubahan dan Simpan data kad.
Anda hanya boleh edit medan.Perihalan, Bank Pengeluar, Kad Piawai, dan Penguncian Kad Pembayaran.
Padam Kad
Untuk memadam kad pembayaran sedia ada,
Pada tab Kad Pembayaran, pilih entri yang anda ingin padam.
Pilih butang Padam.
Petua untuk Berjaya
Gunakan maklumat ini untuk mencapai matlamat anda dalam : untuk selesaikan tugasan pembelajaran tepat pada masa dan mencari kursus pengayaan.
Matlamat utama anda adalah untuk menyelesaikan semua tugasan pembelajaran anda yang perlu mengikut tarikh akhir dan matlamat kedua anda adalah untuk tugaskan kursus pilihan anda sendiri yang menambah kemahiran anda serta pengetahuan untuk membantu anda dalam kerja semasa anda atau untuk memajukan kerjaya anda.
Untuk mencapai matlamat anda, gunakan petua ini:
Lihat mesej e-mel daripada mengenai perubahan dalam jubin Tugasan Pembelajaran anda.
Dalam jubin Tugasan Pembelajaran Saya, mulakan kursus dengan tarikh akhir terawal.
Lancarkan pembelajaran dalam talian dan mesyuarat dalam talian terus dari senarai tugasan.
Tetapkan Keutamaan E-mel Anda
Mengisih dan Menapis Tugasan anda
Petua ini membantu anda mengutamakan dan mencari tugasan pembelajaran dalam senarai tugasan anda dengan menggunakan Isih Mengikut dan Pilihan Tapis.
Apabila anda membuka senarai tugasan anda, ia diisih mengikut tarikh kerana anda harus mengutamakan tugasan dengan tarikh akhir terawal.
Pentadbir pembelajaran organisasi anda juga boleh menambah keutamaan kepada tugasan anda untuk menyampaikan kepentingannya.
Untuk mengisih mengikut keutamaan tugasan organisasi anda, pergi ke Halaman Utama Tugasan Pembelajaran Saya Isih Mengikut Keutamaan.
Untuk mencari tugasan pembelajaran dalam senarai tugasan anda, klik Halaman Utama Tugasan Pembelajaran Saya Tapis.
Gunakan pilihan penapisan untuk mencari tugasan dalam senarai anda.
Pendaftaran Untuk Item Pembelajaran
Topik ini menerangkan cara anda mendaftar untuk kursus.
Organisasi anda mungkin memerlukan anda mendaftar untuk kursus bagi mengehadkan atau meramalkan kehadiran.
Sebagai contoh, organisasi anda mungkin ingin anda mendaftar untuk kursus supaya pengajar mempunyai bahan yang cukup.
Untuk mendaftar kursus, pergi ke Halaman Utama Tugasan Pembelajaran Saya, cari kursus yang anda ingin daftar dan kemudian klik Daftar.
Halaman pendaftaran terbuka.
Jika andatelah mendaftar, kemudian anda boleh cari kursus yang anda daftar dan klik Papar Pendaftaran untuk membuka halaman pendaftaran.
Pada halaman pendaftaran:
Jika anda melihat pendaftaran semasa dalam Pendaftaran Semasa, kemudian anda telah didaftarkan.
Jika anda tidak melihat pendaftaran semasa, semak kursus tersedia dalam Tawaran Tersedia untuk mencari yang sesuai dengan jadual anda.
Klik Daftar Sekarang untuk mendaftarkannya.
Jika anda tidak menemui tawaran tersedia yang sesuai dengan jadual anda, anda boleh bertanya kepada organisasi anda untuk menambah kursus.
Pergi ke Minta Jadual, lengkapkan borang dan klik Minta
Sesetengah permintaan pendaftaran memerlukan kelulusan.
Mencari Peluang Pembelajaran
Gunakan maklumat ini untuk mencari peluang pembelajaran.
Peluang pembelajaran ialah mana-mana kursus, buku, video, atau bahan pembelajaran lain yang anda boleh cari dalam jubin Cari Pembelajaran.
Mencari pembelajaran yang membantu anda mencapai matlamat atau yang menjadikan kerja semasa anda lebih mudah.
Untuk mencari peluang pembelajaran:
Teks jenis dalam jubin Cari Pembelajaran dan klik Pergi.
Klik Layari semua kursus untuk membuka senarai boleh ditapis bagi semua peluang pembelajaran.
KlikLayari semua kursus untuk membuka senarai boleh ditapis dan kemudian klik Kalendar Kursus untuk melihat peluang pembelajaran dalam kalendar.
Meneroka Peluang Pembelajaran
Selepas anda mencari peluang pembelajaran, gunakan pembayang ini untuk meneroka peluang.
Anda mencari peluang pembelajaran dalam jubin Cari Pembelajaran.
Selepas anda mencari peluang pembelajaran, anda boleh menerokanya untuk mengetahui bagaimana ia boleh memberi kesan kepada perkembangan kerjaya anda atau tugas kerja semasa:
Klik tajuk untuk membaca perihalan peluang.
Mulakan kursus untuk pratonton kandungan (tersedia untuk beberapa kursus dalam talian).
Jika kursus menarik perhatian anda, kemudian anda boleh menambahnya ke senarai tugasan anda sendiri.
Dalam sesetengah kes, anda juga boleh menambahnya ke senarai tugasan pengguna lain.
Rekod Penyelia Bidang Kerja Pembelajaran
Penyelia boleh menggunakan maklumat untuk merekod penyelesaian kursus untuk pengguna.
Penyelia boleh merekod pembelajaran untuk pekerja mereka dalam tab Pekerja Saya.
Anda merekod pembelajaran apabila sistem tidak boleh melakukannya sendiri: sebagai contoh, apabila pekerja anda selesaikan acara luaran atau selesaikan kursus di dalam kelas.
Apabila anda klik Rekod Pembelajaran bestari rekod pembelajaran terbuka.
Data Audit
Apabila anda merekod peristiwa pembelajaran, sistem mengumpul data untuk jejak audit.
Apabila organisasi anda atau pekerja diaudit untuk sejarah pembelajaran, data yang anda masukkan boleh menjadi sebahagian daripada audit.
Rekod Penjadualan Kursus
Topik ini menerangkan kegunaan lalai dan disarankan data penyelesaian pembelajaran.
Data ini penting untuk mencipta jejakan audit pembelajaran pengguna anda.
Topik ini mengandungi lalai, penggunaan disarankan data penyelesaian untuk tujuan pengauditan.
Organisasi anda mungkin gunakan data secara berbeza.
Data Jadual Kursus untuk Audit
Nama Data
Permohonan Jejak Audit
Tarikh dan Masa Penyelesaian
Dalam laporan audit, tarikh dan masa penyelesaian adalah semasa pengguna telah selesai pembelajaran.
Semasa anda rekod pembelajaran untuk pengguna, tarikh dan masa penyelesaian mestilah sudah berlalu kerana pengguna harus mempunyai item yang lengkap sebelum anda rekod peristiwa
Jika sistem ketahui masa penyelesaian, ia mengisi tarikh dan masa untuk anda.
Zon Masa. Penyelesaian
Sistem menggunakan zon masa untuk tentukan tentang tarikh dan masa penyelesaian.
Pilih zon masa yang sepadan dengan penyelesaian pengguna.
Maklumat Pengajar
Nama atau ID pengajar mengenal pasti pengajar yang mengajar kursus.
Jika lebih daripada satu pengajar telah mengajar kursus, pilih pengajar utama.
Gred Lalai
Gred lalai ialah cara fleksibel untuk rekod prestasi pengguna dalam kursus.
Gunakan sistem organisasi anda untuk penggredan (huruf, peratusan, atau nombor, sebagai contoh).
Daftar/Keluarkan Bidang Kerja Pekerja
Topik ini menerangkan cara penyelia boleh mendaftar dan mengeluarkan pengguna daripada kursus.
Sebagai penyelia, anda paling kerap berinteraksi secara langsung dengan pasukan pekerja anda, dan anda lebih memahami apa-apa tawaran dijadualkan yang seseorang pekerja perlukan atau tidak perlukan.
Oleh itu, anda boleh menggunakan bestari Pendaftaran untuk menguruskan keperluan itu dengan mengeluarkan atau mendaftarkan pengguna untuk tawaran dijadualkan.
Anda hanya boleh mendaftarkan atau mengeluarkan pengguna daripada tawaran dijadualkan yang belum bermula.
Apabila anda mendaftar pengguna, anda boleh memasukkan ulasan mengenai mendaftar pengguna.
Sebagai contoh, anda mungkin ingin memberitahu pengajar mana-mana keperluan atau keadaan mengenai pengguna yang anda daftarkan.
Pentadbir boleh mencapai ulasan anda dengan memapar rekod tawaran dijadualkan, pengguna akhir tidak pernah melihat ulasan anda.
Kelulusan Bidang Kerja
Gunakan maklumat ini untuk mengurus proses kelulusan proses kelulusan piawai anda dalam Kelulusan bidang kerja.
Apabila anda menggunakan proses kelulusan piawai, setiap permintaan untuk latihan boleh diluluskan atau dinafikan.
Jika anda meminta kelulusan untuk latihan, gunakan kelulusan bidang kerja untuk memantau permintaan anda.
Jika anda meluluskan permintaan untuk latihan, gunakan kelulusan bidang kerja untuk membuat kelulusan atau menafikan permintaan.
Anda boleh memantau atau meluluskan jenis permintaan latihan yang berikut dalam Kelulusan bidang kerja:
Permintaan Luaran: kelulusan untuk menghadiri acara latihan luaran
Permintaan Dalaman: kelulusan untuk menghadiri acara latihan dalaman
Pengesahan E-Tandatangan (Tandatangan Elektronik):
Langkah kelulusan yang memerlukan anda memasukkan kod tandatangan anda
Laporan Pembelajaran Lalai
Laporan tersedia untuk anda boleh pelbagai bergantung pada konfigurasi sistem anda.
Laporan ini adalah tersedia mengikut lalai.
Apabila anda menjalankan laporan, sistem menyatukan maklumat daripada pelbagai bahagian ke dalam laporan tunggal, yang membenarkan anda untuk menjalankan analisis yang disasarkan data utama.
Jadual ini hanya mengandungi laporan pembelajaran, bukan laporan legasi.
Nama Laporan
Tujuan
Matlamat Aktif
Tujuan laporan Matlamat Aktif adalah untuk menunjukkan semua matlamat aktif.
Matlamat aktif ialah semua matlamat yang rancangan yang diluluskan oleh pengguna, termasuk mana-mana rancangan yang telah tamat tempoh.
Walaupun anda boleh menggunakan laporan Matlamat Aktif untuk pengguna tunggal dan rancangan tunggal yang diluluskan, anda dapat yang paling banyak daripada laporan Matlamat Aktif dengan menyatukan matlamat aktif daripada berbilang pengguna atau berbilang rancangan ke dalam laporan tunggal.
Anda boleh kumpulkan laporan mengikut nama matlamat atau mengikut nama pengguna.
Laporan menunjukkan nama matlamat, perihalan, jenis matlamat, tarikh sasaran, keutamaan, kategori, berat (laporan menunjukkan "N/A" untuk pembangunan atau matlamat peribadi), status dan peratusan terhadap sasaran.
Sebagai pengguna tanpa subordinat, anda boleh gunakan laporan Matlamat Aktif untuk menyatukan matlamat daripada rancangan yang diluluskan anda ke dalam laporan tunggal, memberikan anda laporan kemajuan untuk matlamat aktif dan aktiviti berkaitan.
Sebagai pengguna dengan subordinat, anda boleh gunakan Laporan Matlamat Aktif yang menunjukkan matlamat aktif untuk setiap rancangan yang diluluskan oleh subordinat.
Kerja Yang Sesuai
Anda boleh gunakan Kerja Yang Sesuai untuk melihat jawatan yang paling sesuai untuk pekerja anda dan untuk mengenal pasti subordinat yang berkelayakan, lebih kelayakan, atau kurang kelayakan untuk kerja semasa mereka atau untuk kerja yang mungkin dibuka tidak lama lagi.
Jika anda mengenal pasti pekerja yang lebih kelayakan untuk jawatan kerja semasa mereka, maka anda boleh naikkan pangkat mereka ke jawatan kerja lain yang lebih sesuai dengan kecekapan mereka.
Jika anda mengenal pasti pekerja yang lebih kelayakan untuk jawatan kerja semasa mereka, maka anda boleh naikkan pangkat mereka ke jawatan kerja lain yang lebih sesuai dengan kecekapan mereka.
Dalam laporan Kerja Yang Sesuai anda boleh mencapai tahap kelayakan pekerja untuk jawatan kerja dengan menggunakan jurang kecekapan terkumpul.
Jurang kecekapan terkumpul sama dengan jumlah semua jurang kecekapan (untuk kecekapan berkaitan dengan jawatan kerja) dibahagi dengan bilangan kecekapan berkaitan dengan jawatan kerja.
Jurang kecekapan terkumpul boleh jadi positif, sifar, atau negatif.
Pengguna mempunyai jurang kecekapan terkumpul positif jika dan hanya jika mereka mempunyai jurang kecekapan positif untuk setiap kecekapan berkaitan dengan jawatan kerja.
Secara umumnya, jurang kecekapan terkumpul mengenal pasti pengguna sebagai lebih kelayakan untuk jawatan kerja.
Pengguna mempunyai jurang kecekapan negatif apabila dia mempunyai sekurang-kurangnya satu penarafan kecekapan yang di bawah penarafan kecekapan.
Apabila pengguna mempunyai kedua-dua jurang kecekapan positif dan negatif, laporan itu mengubah jurang kecekapan positif kepada sifar supaya jurang kecekapan terkumpul masih lagi negatif.
Ini adalah, walaupun pengguna mungkin mempunyai kekuatan (jurang kecekapan positif) untuk kebanyakan kecekapan berkaitan dengan jawatan kerja, pengguna tidak memenuhi semua tahap keperluan kecekapan untuk jawatan kerja, oleh itu, laporan mesti menunjukkan jurang kecekapan negatif untuk jawatan kerja itu.
Secara umumnya, jurang kecekapan terkumpul mengenal pasti pengguna sebagai lebih kelayakan untuk jawatan kerja.
Bahagian rumusan laporan menunjukkan kekuatan (purata penarafan sejawat lebih besar daripada penarafan diri pengguna) untuk setiap pengguna sementara bahagian butiran laporan menyenaraikan jawatan kerja yang sesuai, jurang terkumpul dan kecekapan dengan jurang terbesar, termasuk nilai jurang (jurang sama dengan penarafan sejawat tolak penarafan pengguna).
Jika pengguna belum dinilaikan untuk kecekapan berkaitan dengan jawatan kerja, maka laporan mencari penarafan kecekapan sebagai sifar.
Penarafan sifar ke atas mana-mana kecekapan menyebabkan jurang kecekapan terbesar dan jurang kecekapan terkumpul terbesar.
Oleh itu, apabila anda mencapai laporan kerja yang sesuai dengan pengguna, pastikan untuk mengambil kira kecekapan tidak ditarafkan.
Perbandingan Penilaian Kecekapan
Anda boleh gunakan laporan Perbandingan Penilaian Kecekapan untuk membandingkan penarafan kecekapan untuk pengguna dengan purata organisasi dan purata syarikat.
Jika pengguna ditugaskan kecekapan, tetapi belum ditarafkan untuk kecekapan itu, maka laporan itu tidak termasuk pengguna yang untuk kecekapan itu.
Aliran Penilaian Kecekapan
Penyelia menggunakan laporan Aliran Penilaian Kecekapan untuk melihat jika penarafan kecekapan laporan langsung mereka telah meningkat atau menurun sepanjang masa.
Setiap pengguna boleh mempunyai sehingga lima penarafan kecekapan untuk setiap kecekapan.
Sebagai contoh, jika anda pilih 3 Bulan dari senarai Selang Aliran Sejarah, kemudian penarafan kecekapan pertama (paling kerap) muncul dalam lajur Penarafan Semasa, penarafan kecekapan kedua muncuk dalam lajur Penarafan Terakhir, dan penarafan kecekapan ketiga, keempat, dan kelima muncul dalam lajur Aliran Sejarah.
Status Kurikulum
Sebagai penyelia, anda boleh gunakan laporan Status Kurikulum untuk menyemak semula pengguna yang telah tertinggal di belakang untuk menyelesaikan kurikulum ditugaskan.
Penurunan Pekerja
Anda boleh gunakan laporan Penurunan Pekerja untuk menunjukkan pengguna yang mana penarafan penyelia telah jatuh dengan ketara daripada semakan sebelumnya kepada semakan terbanyak yang baru disiarkan (anda takrifkan penurunan yang ketara menggunakan Ambang Jurang).
Untuk dimasukkan ke dalam laporan, pengguna mesti mempunyai lebih daripada satu semakan semula dan penarafan penyelia yang paling kerap mesti lebih rendah daripada penarafan penyelia sebelumnya.
Jurang Penarafan Pekerja/Penyelia.
Anda boleh gunakan Jurang Penarafan Pekerja/Penyelia untuk menunjukkan pengguna yang penarafan sendiri telah secara ketaranya berbeza daripada penarafan penyelia (anda takrifkan ketara jurang menggunakan Ambang Jurang).
Jurang boleh jadi positif atau negatif: penyelia boleh mempunyai penarafan lebih tinggi atau lebih rendah daripada kedua-duanya.
Laporan menunjukkan semua jurang daripada semakan prestasi paling kerap.
Permintaan Item
Sebagai penyelia atau koordinator pembelajaran, anda boleh menggunakan laporan Permintaan Item untuk mengenal pasti item yang mungkin memerlukan tawaran dijadualkan tambahan untuk memenuhi permintaan dan keperluan semasa.
Status Item
Anda boleh jalankan laporan Status Item untuk menunjukkan tarikh penyelesaian dan status untuk item dalam sejarah pembelajaran.
Sejarah Pembelajaran
Sebagai penyelia, anda boleh menggunakan laporan Sejarah Pembelajaran untuk menyenaraikan semua item laporan langsung atau tidak langsung yang telah selesai.
Anda boleh menggunakan laporan ini untuk membandingkan setiap prestasi pengguna dan status mereka untuk item.
Jam Pembelajaran
Anda boleh jalankan laporan Jam Pembelajaran untuk memaparkan butiran untuk peristiwa dalam sejarah pembelajaran pengguna yang termasuk panjang kursus, jam kredit, jam CPE dan waktu hubungi.
Keperluan Pembelajaran
Anda boleh jalankan laporan Keperluan Pembelajaran untuk paparkan item ditugaskan yang kekal pada senarai tugasan pengguna.
Laporan ini boleh ditapiskan untuk menunjukkan hanya pembelajaran diperlukan.
Rancangan Pembelajaran
Anda boleh jalankan laporan Rancangan Pembelajaran untuk memaparkan semua item pengguna yang telah ditugaskan.
Laporan termasuk tarikh penyelesaian yang berkenaan, dan boleh ditapiskan untuk tunjukkan hanya keperluan pembelajaran atau tugasan diperlukan.
Tuisyen
Laporan Tuisyen memaparkan amaun pengguna dibayar untuk melancarkan, mendaftarkan, atau menyelesaikan item.
Maklumat Pengguna
Laporan Maklumat Pengguna menunjukkan maklumat asas tentang setiap pengguna.
Anda boleh gunakan laporan ini, sebagai contoh untuk menyelesaikan beberapa isu biasa, seperti memastikan yang pengguna mempunyai alamat emel apabila mereka kata yang mereka tidak menerima pemberitahuan emel.
Tugasan Pembelajaran dan Sejarah Pembelajaran
Tugasan pembelajaran anda ialah kursus yang anda perlu selesaikan dan sejarah pembelajaran anda ialah senarai kursus yang anda telah selesaikan.
Topik ini menerangkan dua senarai.
Senarai tugasan pembelajaran anda termasuk semua kerja yang anda perlu lakukan, termasuk item pembelajaran, penawaran dijadualkan, dan kurikulum.
Ia ialah tempat pusat untuk tugasan anda.
Sejarah pembelajaran anda ialah rekod kerja yang anda telah selesaikan.
Apabila anda menyiapkan kursus, ia beralih dari senarai tugasan pembelajaran ke senarai sejarah pembelajaran.
Menyelesaikan Penilaian Senarai Semak Tugas
Senarai semak tugas ialah jenis peperiksaan iaitu pemerhati memerhati peserta menyelesaikan tugas dan menanda langkah dalam senarai tugas
Topik ini menerangkan cara anda menyelesaikan senarai semak.
Mengenai Senarai Semak Tugas
Senarai semak tugas mengandungi semua tugas yang pengguna harus mampu selesaikan sebagai hasil pembelajaran kandungan item pembelajaran yang berjaya.
Sebagai pengguna, senarai semak tugas membenarkan anda untuk menunjukkan penguasaan anda bagi item dengan menunjukkan bahawa anda boleh selesaikan setiap tugas yang berkaitan dengan item.
Jika pentadbir anda membolehkan senarai semak tugas untuk item, maka sistem meletakkan item pada senarai tugasan anda dengan tindakan Minta Pemerhatian
Anda juga boleh meminta pemerhatian dengan memapar butiran item untuk item.
Pencalonan Pemerhati
Jika senarai semak tugas ditugaskan kepada anda, langkah pertama anda ialah mencalonkan pengguna lain untuk memerhati anda menyelesaikan tugas.
Kerja pemerhati ialah memerhati anda menyelesaikan tugas dan mengisi senarai semak yang menunjukkan anda menyelesaikan setiap langkah dalam tugas.
Untuk mencalonkan pengguna, klik Minta Pemerhati.
Anda boleh mencari dan menambah bilangan pemerhati tetapi hanya satu pemerhati boleh menyerahkan hasil.
Anda boleh teruskan menambah atau mengeluarkan pemerhati sehingga pemerhati menyerahkan senarai semak tugas anda dengan status penyelesaian.
Apabila anda menambah atau mengeluarkan pemerhati, sistem meletakkan item pada senarai tugasan pemerhati dengan tindakan Buka Pemerhatian
Pemerhati juga boleh melancarkan senarai semak tugas dari halaman butiran item.
Menyelesaikan Senarai Semak Tugas
Untuk menyelesaikan senarai semak tugas, buka senarai semak (klik Buka Pemerhatian).
Untuk setiap tugas dalam senarai, baca perihalan tugas dengan senyap dan semak status penyelesaian yang betul.
Jika anda memerhati individu menyelesaikan tugas, tandakan tugas yang selesai.
Jika tidak, tandakan ia tidak selesai.
Anda juga boleh menambah ulasan untuk setiap tugas individu atau untuk keseluruhan senarai semak tugas.
Apabila pemerhatian anda tamat, anda boleh merekod penyelesaian atau merekod kegagalan.
Dalam beberapa situasi, anda boleh mempunyai status tugas tidak betul tetapi.anda perlu klik Merekod Penyelesaian untuk keseluruhan senarai semak tugas.
Begitu juga, terdapat situasi anda mungkin mempunyai status tugas betul untuk semua tugas tetapi anda perlu klik Merekod Kegagalan untuk keseluruhan senarai semak tugas.
Syarikat atau penyelia anda perlu memberikan panduan mengenai piawai yang digunakan untuk menentukan penyelesaian atau kegagalan senarai semak tugas.
Pembelajaran Luar Talian
Terdapat dua cara untuk melihat kandungan apabila anda tidak bersambung ke internet: legasi Plateau Luar Talian dan Pembelajaran Bergerak.
Topik ini menerangkan perbezaan antara dua perkara tersebut.
Pembelajaran Bergerak Luar Talian
Pembelajaran Bergerak memuat turun tugasan pembelajaran ke peranti mudah alih anda, tempat yang anda boleh lihat kandungan (video, halaman web dan sebagainya).
Pentadbir pembelajaran anda boleh menyekat kandungan yang boleh dimuat turun ke Pembelajaran Bergerak.
Muat turun aplikasi mudah alih dari app store anda.
Legasi Plateau Luar Talian
Anda boleh muat turun penilaian kandungan pembelajaran dan legasi Plateau ke Plateau Luar Talian, iaitu aplikasi Windows.
Selepas anda muat turunnya, anda boleh putuskan sambungan dari rangkaian anda dan bekerja dengannya.
Disebabkan Plateau Luar Talian berfungsi apabila diputuskan sambungan, ia adalah ideal untuk pengguna yang mengembara bersama komputer riba atau yang mempunyai sambungan rangkaian yang perlahan atau yang memerlukan capaian ke Penilaian Plateau.
Plateau Luar Talian menjejaki objek kandungan yang anda selesaikan semasa anda dalam keadaan luar talian.
Apabila anda log semula ke dalam antara muka pengguna, sistem segerak dengan Plateau Luar Talian.
Sistem mengunci penilaian Plateau yang anda muat turun.
Jika anda cuba untuk muat turun penilaian semula, anda melihat amaran bahawa anda boleh kehilangan kerja anda.
Mendapat Kredit untuk Kursus
menawarkan anda lebih daripada satu cara untuk mendapatkan kredit.
Topik ini menerangkan cara sistem menilai kemajuan anda.
Seperti kemajuan anda melalui tugasan pembelajaran anda, sistem terhenti daripada masa ke masa untuk menilai kemajuan anda dalam matlamat pembelajaran anda dan ia menawarkan beberapa cara untuk mendapatkan kredit:
Beberapa kursus memberi kredit apabila anda mula dan selesaikannya.
Beberapa kursus memberikan kredit apabila anda lulus peperiksaan.
Beberapa kursus mempunyai cara alternatif menilai kemahiran dan pengetahuan anda.
Senarai semak tugas adalah jenis peperiksaan khas: pemerhati memerhati anda untuk menyelesaikan tugas dan menunjukkan bahawa anda telah menyelesaikan langkah dalam tugas dan anda telah berjaya.
Sesetengah pengguna seperti pentadbir, boleh memberikan kredit secara langsung melalui proses rekod pembelajaran
Pesanan Bidang Kerja Saya
Bidang kerja Pesanan Saya mengandungi arahan untuk latihan.
Guna petua ini untuk navigasi pesanan anda.
Pesanan adalah pembelian
Bidang kerja Pesanan Saya mengandungi sejarah pesanan dan pilihan anda untuk memesan lebih banyak latihan.
Sistem benarkan pilihan pembelian ini:
Kod akaun:
Guna kod akaun untuk caj latihan pembelian untuk akaun.
Kod akaun biasanya kepunyaan jabatan anda.
Tiket pesanan:
Tiket pesanan adalah baucer yang anda gunakan untuk latihan pembelian.
Kupon:
Kupon mengurangkan atau menyingkirkan kos latihan.
Pilihan dan Tetapan Bidang Kerja
Pilihan dan Tetapan bidang kerja uruskan keutamaan anda.
Guna maklumat ini untuk memahami perkara yang anda boleh kawal dalam bidang kerja.
Pergi ke Utama Pautan Pilihan dan Tetapan
Dalam bidang kerja, anda boleh kawal berikut:
Pilihan keselamatan: anda boleh tetapkan semula kata laluan anda atau soalan keselamatan anda.
Pilihan pemberitahuan: anda boleh tentukan apabila sistem harus menghantarkan mesej email (sebagai contohnya, apabila kursus ditambah ke tugasan anda).
Tetapan kawasan: anda boleh tetapkan zon waktu, mata wang, penempatan (bahasa), dan papar format anda.
Kaedah Kelulusan
Apabila anda memerlukan kelulusan untuk menghadiri kursus, guna topik ini untuk memahami kaedah kelulusan yang berbeza.
memberikan tiga proses kelulusan.
Dalam kebanyakan kes, organisasi anda menggunakan hanya satu atau dua proses.
Proses kelulusan diuruskan dari jubin Pautan
Proses kelulusan piawai:
Proses kelulusan piawai adalah yang paling biasa.
Organisasi anda mencipta proses kelulusan dengan satu atau lebih langkah.
Anda menguruskan kelulusan dalam ruang kerja Kelulusan.
Proses permintaan luaran:
Yang paling biasa digunakan oleh organisasi Persekutuan Amerika Syarikat, proses permintaan luaran menggunakan borang SF-182 persekutuan piawai untuk meminta latihan luaran.
Anda menguruskan permintaan luaran dalam ruang kerja Permintaan Luaran dan ruang kerja Kelulusan.
Proses perancang latihan:
Perancang latihan digunakan oleh organisasi yang merancang latihan mereka pada tempoh belanjawan seperti tahun fiskal dan yang mempunyai pendekatan latihan atas bawah.
Anda menguruskan kelulusan perancang latihan dalam ruang kerja Perancang Latihan.
Pautan Lain
Organisasi anda boleh menambah pautan pada jubin Pautan
Topik ini menerangkan sebab organisasi anda perlu menambah pautan
Pautan sangat boleh disesuaikan.
Sebagai contoh, syarikat anda mungkin menambah pautan pada intranet dalam jubin Pautan, atau ia mungkin mengeluarkan pautan Permintaan Luaran jika ia tidak menggunakan proses permintaan luaran.
Ia juga mungkin yang organisasi anda menggunakan produk legasi Plateau.
Prestasi Plateau dan Pampasan Plateau.
Jika anda menggunakan produk legasi, pautan anda sangat berbeza dari jubin Pautan.
Lihat bantuan flash legasi Plateau untuk bantuan dengan produk legasi.
Menggunakan Cadangan Tawaran Tersedia
Jubin Tawaran Tersedia mencadangkan kursus yang membantu anda memenuhi keperluan.
Topik ini membantu anda menggunakan jubin.
Jubin Tawaran Tersedia mencadangkan kursus akan datang yang membantu anda menyelesaikan sebahagian kurikulum atau menyelesaikan satu tugasan pada senarai Tugasan Pembelajaran Saya anda.
Kursus berdekatan lokasi anda dan dijadualkan bermula tidak lama lagi.
Anda boleh menemui jubin di dua tempat:
Dalam tab Halaman Utama untuk kursus yang membantu anda menyelesaikan tugasan pembelajaran anda secara umum.
Dalam halaman butiran kurikulum untuk kursus yang membantu anda menyelesaikan kurikulum.
Memaparkan Butiran Tugasan
Butiran tugasan boleh membantu anda menilai kepentingannya dan pratonton kursus.
Gunakan petua ini untuk memapar butiran.
Organisasi anda boleh memilih untuk memberikan butiran atau halaman hadapan untuk tugasan supaya anda tahu perkara yang dijangkakan daripada kursus.
Pergi ke Halaman Utama Tugasan Pembelajaran Saya dan kemudian klik tajuk kursus.
Banyak kursus dalam talian memasukkan gambaran keseluruhan pengenalan kandungan kursus, jadi anda boleh mulakan kursus untuk melihat apa-apa yang ia liputi.
Dalam tugasan pembelajaran anda, klik Mulakan Kursus.
Peranan Perancang Latihan
Guna maklumat ini untuk memahami cara anda padankan ke dalam proses perancang latihan.
Pengguna utama perancang latihan adalah pengurus latihan, individu yang bertanggungjawab untuk kelulusan belanjawan, tetapi semua tiga peranan mesti mempertimbangkan latihan yang perlu, dan kosnya melebihi tempoh masa perancangan.
Jika anda pengurus latihan, kerja anda adalah untuk mengekalkan rancangan latihan anda mengikut belanjawan.
Guna ruang kerja untuk mempertimbangkan permintaan latihan organisasi dan luluskan atau menafikan permintaan untuk kekal dalam belanjawan.
Jika anda ialah penyelia, kerja anda adalah untuk mempertimbangkan latihan yang diperlukan oleh pasukan anda dan serahkan permintaan dengan kosnya.
Jika anda ialah pekerja, kerja anda adalah untuk mempertimbangkan keperluan latihan anda sendiri dan serahkannya dengan kos kepada pengurus latihan.
Cara Permintaan Daripada Pengguna Dirumuskan ke Pengurus Latihan
Menugaskan Penyelia Alternatif
Gunakan topik untuk memahami cara dan apabila anda perlu tugaskan pengguna kepada penyelia alternatif.
Apabila pengguna bekerja untuk tempoh dilanjutkan pada projek yang memerlukan mereka melaporkan kepada pengurus atau penyelia berbeza, kemudian anda mungkin ingin pindahkan tanggungjawab untuk menyelesaikan tugas penyelia utama (sebagai contoh, menugaskan atau meluluskan item pembelajaran) kepada penyelia alternatif.
Apabila anda klik Urus Penyelia Alternatif, anda boleh kenal pasti pengguna lain sebagai penyelia alternatif dan tugaskan tanggungjawab utama kepada mereka.
Selepas anda menugaskan pengguna sebagai penyelia alternatif, sistem mengemas kini bidang Pekerja Saya bagi antara muka untuk penyelia alternatif itu dengan memasukkan pengguna untuk mereka yang sekarang mempunyai tanggungjawab untuk menyelesaikan tugas.
Penyelia alternatif kemudian boleh terus menyelesaikan tugas atau mengenal pasti penyelia alternatif untuk pengguna ini.
Dalam antara muka pengguna, penyelia utama dan alternatif boleh menugaskan apa-apa tanggungjawab untuk tugas yang penyelia alternatif itu boleh tugaskan semula tanggungjawab kepada penyelia utama, namun, penyelia alternatif dan utama yang dimasukkan oleh pentadbir.
Pengguna (penyelia utama dan alternatif) hanya boleh mengeluarkan penyelia alternatif yang mereka kenal pasti atau yang penyelia alternatifnya dikenal pasti.
Tambahan pula, penyelia alternatif tidak boleh mengeluarkan diri mereka dari senarai penyelia alternatif.
Pentadbir boleh mengeluarkan mana-mana penyelia alternatif.
Carian dalam Bidang Kerja Pembelajaran Ditugaskan
Apabila anda mencari dalam bidang kerja pembelajaran ditugaskan, carian sedikit berbeza daripada jubin Cari Pembelajaran.
Topik ini menerangkan cara carian berfungsi dalam bidang kerja pembelajaran ditugaskan.
Dalam bidang kerja pembelajaran ditugaskan, carian sistem tidak sensitif huruf: carian untuk "PENTADBIR", "Pentadbir", dan "pentadbir" memberikan hasil yang sama.
Apabila anda klik Cari, sistem mencari tajuk dan perihalan untuk kriteria carian anda.
Oleh itu, tajuk untuk sesetengah hasil carian tidak akan memenuhi kriteria carian anda.
Sebagai contoh, jika anda mencari "PENTADBIR" dan sistem menemui tajuk "Berkomunikasi Secara Efektif," kemudian perihalan untuk Berkomunikasi Secara Efektif mengandungi rentetan carian yang anda nyatakan (iaitu, ia mengandungi "PENTADBIR")
Jika anda memilih Frasa Tepat, kemudian sistem mengabaikan huruf besar dan mencari frasa tepat, termasuk ruang.
Sebagai contoh, jika anda memilih Frasa Tepat dan cari kata kunci "AN PE", kemudian hasil carian boleh mengandungi "Topik Pentadbiran Lanjutan" (kerana dua huruf terakhir "Lanjutan" dan dua huruf pertama "Pentadbiran" ialah "an pe").
Jika anda kosongkan Frasa Tepat, kemudian sistem mencari frasa tepat dan menggunakan mana-mana ruang dalam kata kunci secara berbeza.
Jika anda mempunyai berbilang kata kunci, kemudian sistem mencari setiap perkataan (seperti dikenal pasti mengikut ruang) dengan carian berasingan.
Hasil carian mesti mengandungi semua perkataan, tetapi kata kunci boleh dalam mana-mana susunan.
Sebagai contoh, jika anda kosongkan Frasa Tepat dan cari kata kunci "simul JUTAN", kemudian hasil carian boleh mengandungi "Simulasi Sokongan Pentadbiran Lanjutan" (kerana "simul" terkandung dalam "Simulasi" DAN "JUTAN" terkandung dalam "Lanjutan").
Jika anda memilih Cari Semua Bahasa, kemudian sistem memberikan hasil daripada mana-mana penempatan.
Untuk menghadkan hasil carian kepada penempatan yang dipilih anda sahaja, kemudian anda boleh kosongkan kotak semak Cari Semua Bahasa.
Mencari Kandungan Luaran
Papar bahagian ini jika anda ingin tahu mengenai kursus web.
Massive open online content (MOOC) termasuk kursus kepimpinan atau kemahiran bahasa pengaturcaraan.
Kandungan luaran tersedia daripada pekongsi.
Katalog kursus daripada pekongsi ini mesti diaktifkan dalam LMS oleh pentadbir untuk kandungan luaran boleh tersedia dalam katalog, dikumpulkan ke dalam sistem pembelajaran seperti kurikulum, atau ditugaskan secara terus ke pengguna oleh pentadbir atau penyelia.
Untuk mencapai kandungan luaran, pergi ke Utama Cari Pembelajaran Pelayar semua kursus Carian Katalog Kursus Web.
Daripada Kursus Web, anda boleh paparkan kandungan luaran tersedia, tambah kursus ke tugasan anda, atau hanya melancarkan kursus.
Selepas kursus kandungan luaran dilancarkan, klik pautan kursus yang membawa anda ke laman web pekongsi.
Perlu diingat:
Apabila anda lancarkan kursus kandungan luaran, anda lancarkan lamanpembekal untuk berinteraksi dengan kursus luar..
Anda perlu log log masuk dalam beberapa laman web kursus kandungan luaran sebelum mencapai kandungan luarannya.
Penyelesaian kursus adalah sama ada diselesaikan sendiri atau oleh perakuan yang ditentukan oleh organisasi.
Memilih Halaman Disetempatkan untuk Pengguna Tidak Disahkan
Semua halaman yang boleh dilihat oleh pengguna diterjemah ke dalam bahasa anda, berdasarkan pilihan anda dalamPilihan dan Tetapan, yang dibaca oleh sistem semasa anda log masuk.
Jika anda masih belum log masuk, namun, anda perlu memberitahu sistem bahasa anda.
Semasa mengkonfigurasi, anda boleh memilih penempatan untuk paparan halaman log masuk.
Senarai penempatan lalai ke penempatan pelayar jika ia sepadan dengan penempatan aktif, jika tidak ia ditetapkan ke penempatan lalai sistem.
Halaman disetempatkan termasuk:
Log masuk, Pendaftaran, Soalan dan Jawapan Keselamatan, Lupa Nama Pengguna dan Lupa Kata Laluan.
Jika anda ialah pengguna tapak (jika anda tidak perlu log masuk untuk melihat katalog pembelajaran dan kalendar tawaran anda, halaman anda juga akan diterjemah melalui senarai Penempatan.
Bidang Kerja QuickGuides Saya
Papar bahagian ini jika anda ingin tahu mengenai QuickGuides Saya.
Sesetengah pengguna boleh mencipta QuickGuides, iaitu arahan langkah demi langkah untuk mencipta secara cepat dengan telefon atau pelayar anda dan muat naik ke katalog pembelajaran untuk dilihat oleh orang lain.
Jika anda ialah pengguna yang mencipta QuickGuides, anda boleh cipta perihalan yang boleh cari dalam katalog dan dipaparkan apabila melancarkan panduan.
Sebagai contoh, jika QuickGuide anda berhak, "Panggilan Pemajuan daripada PC anda", perihalan anda boleh menjadi,"Ini menerangkan cara untuk majukan panggilan telefon pada telefon pejabat anda apabila anda perlu melihat sambungan."
Jika syarikat anda memberikan anda capaian ke QuickGuides, anda boleh tandakannya daripada hasil carian atau panduan yang dilancarkan.
Anda boleh capai penanda daripada halaman utama anda dalam jubinPenanda Buku.
Serahan Ke Perkilangan
Membenarkan anda menyerahkan bil bahan kejuruteraan kepada perkilangan.
Anda harus mempunyai fungsi jurutera pengeluaran () untuk menjalankan operasi ini.
Anda boleh menyerahkan bil bahan kejuruteraan seperti berikut:
Daripada aplikasi semasa (Selenggara Bil Bahan)
(atau)
Daripada aplikasi Serahan Bil Bahan Kejuruteraan.
Anda boleh menggunakan ciri ini jika item skop Serahan Struktur Produk Kejuruteraan diaktifkan.
Profil
Semak titik dalam profil.
Dengan profil 0full, anda dapatkan senarai log yang menunjukkan hasil pengesahan data berikut:
Data konfigurasi, seperti aras perancangan dan kumpulan perancangan.
Program mungkin menyemak aras perancangan digunakan di tempat lain, tetapi aras perancangan ini tidak wujud.
Data induk, seperti akaun bank dan akaun bank syarikat.
Program mungkin menyemak akaun bank syarikat digunakan di tempat lain, tetapi akaun bank syarikat ini tidak wujud.
Data transaksi, seperti data induk yang disimpan dalam One Exposure dari Operasi..
Program mungkin menyemak data induk akaun bank adalah tidak betul dalam One Exposure dari Operasi.
Muat Naik
Muat naik data perancangan untuk objek peruntukan produk.
Anda boleh gunakan butang Muat Naik untuk memuat naik fail CSV yang mengandungi data untuk gabungan nilai ciri dan tempoh masanya untuk objek peruntukan produk.
Jika anda mahu memuat naik data perancangan untuk objek peruntukan produk dalam format fail CSV, anda boleh:
Gunakan fungsi Muat Turun untuk mencipta dahulu fail CSV yang mengandungi pemformatan yang betul dan data perancangan peruntukan produk yang sedia ada.
Cipta gabungan nilai ciri baru (termasuk gabungan nilai ciri peruntukan kolektif).
Ubah data perancangan peruntukan produk yang dimuat turun (nilai ciri, kuantiti peruntukan).
Tambah tempoh dan kuantiti peruntukan untuk gabungan nilai ciri.
Keberkalaan bagi tempoh yang ditambah perlulah sama dengan fail CSV yang dimuat naik.
Muat naik data perancangan daripada fail CSV dan semak serta jika perlu, betulkan data yang dimuat naik dalam jadual Data Perancangan Peruntukan Produk.
Julat Tempoh
Tapis data yang dipaparkan kepada tempoh masa tertentu sahaja.
Tempoh masa ditakrifkan dalam medan Julat Tempoh menapis data dipaparkan secara berturutan untuk analisis dalam senarai Gabungan Nilai Ciri.
Senarai memaparkan gabungan nilai ciri yang mempunyai sekurang-kurangnya satu tempoh yang bersilang dengan julat tempoh.
Ambil perhatian bahawa anda boleh menggunakan pilihan Julat Tempoh pada skrin Gabungan Nilai Ciri untuk mentakrif tempoh masa berbeza bagi memaparkan data tempoh peruntukan produk daripada skrin Pantau Gabungan Nilai Ciri Peruntukan Produk yang dipilih.
Data dipaparkan untuk entri tempoh yang tarikh mula dan akhirnya bersilang dengan julat tempoh yang ditakrifkan.
Jika tiada julat tempoh yang ditakrifkan, tarikh mula pada pemilihan Julat Tempoh ditetapkan secara lalai kepada tarikh semasa.
Padam Data yang Dipantau
Padam data yang dipantau kepunyaan jenis situasi ini.
Anda boleh memadam data dipantau untuk jenis situasi ini dengan memilih satu daripada pilihan berikut:
Padam Semua Data yang Dipantau:
Pilihan ini memadam keseluruhan data yang dipantau kepunyaan jenis situasi ini.
Padam Data Dipantau Sebelum:
Pilihan ini hanya memadam data yang dipantau sebelum tarikh yang anda pilih untuk pilihan ini.
Ubah
Ubah baris gilir cetakan sedia ada.
Untuk ubah baris gilir cetakan, pilih kotak semak baris gilir cetakan masing-masing.
Anda boleh ubah perihalan, pengguna cetakan dan tempoh pengekalan bagi baris gilir cetakan yang dipilih.
Perhatian:
Jika anda ubah pengguna cetakan baris gilir, anda perlu sesuaikan perubahan dalam konfigurasi SAP Cloud Print Manager.
Jika tidak, anda tidak akan dapat mencetak item baris gilir cetakan.
Ikon Baharu dalam Bar Shell
Sila lihat ikon baharu pada bar pengepala.
Kami telah reka bentuk semula bar shell, gantikan ikon untuk pemberitahuan dan SAP CoPilot, serta menambah ikon limpahan baharu.
Ikon Halaman Utama dikeluarkan.
Anda boleh klik pada ikon SAP atau ikon jenama pelanggan untuk kembali ke halaman utama.
Terdapat ikon baharu di sebelah kanan bar pengepala untuk Menu Tindakan Pengguna yang menggantikan Me Area.
Untuk maklumat lanjut, lihat.
Tatacara Dunning
Ini ialah kod unik medan yang mentakrif tatacara dunning.
Tatacara dunning menentukan cara dunning pelanggan atau vendor.
Tatacara dunning tidak bergantung pada kod syarikat.
Tatacara dunning menentukan selang dunning, tempoh untuk penentuan tarikh akhir dan bilangan tahap dunning.
Untuk mentakrif tatacara dunning, pengguna perlu mentakrif yang berikut:
Bilangan tahap dunning
Kekerapan dunning
Had Amaun
Teks untuk notis dunning
Unit Organisasi Rujukan
Anda boleh gunakan unit organisasi rujukan untuk mendapatkan maklumat lanjutan mengenai item ini.
Apabila dokumen perakaunan diposkan, aplikasi penghantaran juga memindahkan pengenal pasti unik yang terdiri daripada kod objek dan jenis objek.
Kod objek terdiri daripada nombor dokumen rujukan dan unit organisasi rujukan.
Unit organisasi rujukan ialah medan teknikal yang digunakan untuk dapatan semula jadual.
Ia membandingkan kod yang terkandung dalam pengepala dokumen kecuali nombor dokumen rujukan.
Contohnya, untuk tempoh pengeposan FI, nombor dokumen, kod syarikat, dan tahun fiskal boleh menjadi kod dalam pengepala dokumen.
Untuk pengeposan ini, unit organisasi rujukan membandingkan kod syarikat dan tahun fiskal.
Untuk dokumen pengebilan, pengepala dokumen mungkin tidak mengandungi kod kecuali nombor rujukan.
Dalam kes ini, unit organisasi rujukan dibiarkan kosong.
Individu untuk Dihubungi
Membolehkan anda menyelenggarakan atau memaparkan data bagi individu untuk dihubungi pada pembekal.
Anda boleh memasukkan atau memaparkan data bagi individu untuk dihubungi pada pembekal, iaitu pengenal pasti atau nama Jurujual, nombor Telefon jurujual, dan data rujukan bagi individu untuk dihubungi.
Dalam medan Jurujual, anda boleh memasukkan teks bebas sehingga 30 aksara.
Sebagai rujukan, anda boleh memasukkan akronim sehingga 12 aksara bagi mengenal pasti individu bertanggungjawab untuk pesanan belian dalam syarikat pembekal anda (Rujukan Anda) dan syarikat anda sendiri (Rujukan Kami).
Anda boleh gunakan data yang diselenggara bagi individu untuk dihubungi sebagai penapis untuk senarai pesanan belian yang dipaparkan dalam senarai objek aplikasi Uruskan Pesanan Belian.
Data bagi individu untuk dihubungi disimpan dengan pesanan belian, bukan data induk pembekal.
Ciptaan Data pMRP
Cipta rancangan rujukan anda untuk simulasi anda.
Dalam aplikasi ini, anda boleh mencipta data rujukan yang digunakan untuk simulasi.
Data rujukan memudahkan data MRP untuk membina persekitaran bagi simulasi anda tanpa menjejaskan data operasi anda.
Satu set data rujukan yang ditakrifkan adalah rancangan rujukan.
Anda boleh menjadualkan ciptaan pelbagai simulasi dengan data rujukan yang berbeza, contohnya, anda boleh simulasikan perancangan untuk loji yang berbeza.
Berdasarkan data rujukan yang anda pilih di sini, anda boleh menyalin rancangan simulasi untuk mencipta pelbagai simulasi dengan rancangan rujukan yang sama untuk membandingkannya dalam aplikasi Proses Simulasi pMRP.
Versi Aktif
Tunjukkan versi PIR aktif atau tidak.
Secara lalai, versi aktif sahaja yang dipaparkan.
Gunakan penapis untuk memaparkan versi tidak aktif.
Untuk mengubah versi kepada aktif atau tidak aktif, teruskan seperti berikut:
Pilih versi PIR dan klik Edit.
Gunakan suis Ya/ Tidak untuk mengubah versi masing-masing kepada aktif atau tidak aktif.
Klik Simpan.
Penundaan dan Rancangan Ansuran
Anda boleh tunda pembayaran atau aturkan rancangan ansuran sekiranya pekongsi perniagaan tidak boleh mematuhi kewajipan pembayarannya.
Anda boleh mengira faedah untuk rancangan ansuran.
Jika penundaan telah dipersetujui, tarikh penundaan dicatatkan dalam item terbuka sebagai tambahan pada tarikh akhir.
Tarikh penundaan telah memberi kesan pada sistem yang tidak dunning atau mengutip pembayaran dengan syarat tempoh penundaan yang dipersetujui sah.
Sebaik sahaja tarikh penundaan telah berlalu tanpa pembayaran dibuat, item terbuka dunning dan kutipan bank dilaksanakan sekali lagi.
Jika pembayaran mengikut ansuran telah dipersetujui, anda mencipta rancangan ansuran untuk amaun belum terima asal.
Ansuran individu dan tarikh akhirnya ditentukan dalam rancangan ansuran.
Anda boleh mengenakan caj sebagai tambahan bagi tawaran rancangan ansuran.
Untuk mengelakkan tarikh akhir jatuh pada hujung minggu atau pada cuti umum, anda boleh merujuk kalendar kilang apabila menentukan tarikh tersebut.
Jalanan dunning dan jalanan pembayaran mengambil kira ansuran individu dalam rancangan ansuran dan bukannya belum terima yang asal.
Anda boleh memadamkan ansuran yang masih belum dibayar dan mengubah amaun ansuran (pembayaran balik dan faedah) atau tarikh akhir.
Anda boleh menambah ansuran ke rancangan ansuran aktif.
Jumlah ansuran dalam rancangan ansuran mestilah sentiasa sepadan dengan jumlah belum terima asal yang dimasukkan dalam rancangan ansuran.
Dengan syarat rancangan ansuran yang aktif dalam paparan baki akaun dan rancangan ansuran, anda boleh memanggil belum terima dalam ansuran.
Nombor dokumen bagi rancangan ansuran direkodkan dalam belum terima asal.
Ini membolehkan pautan antara belum terima asal dan rancangan ansuran untuk dijamin.
Apabila ansuran dibayar, pembayaran secara automatik diagihkan di antara belum terima sumber.
Apabila ansuran terakhir rancangan ansuran dibayar, kedua-dua rancangan ansuran dan belum terima asal akan dijelaskan melalui jalanan pembayaran apabila pembayaran masuk diposkan.
Ansuran boleh dibayar sebahagiannya.
Sekiranya perjanjian untuk pembayaran secara ansuran dibatalkan, anda boleh menyahaktifkan rancangan ansuran secara manual.
Ia bermaksud belum terima asal menjadi aktif semula.
Sistem mengeluarkan pautan antara belum terima asal dan rancangan ansuran.
Rancangan ansuran yang dinyahaktifkan tidak boleh diaktifkan semula dan anda juga tidak lagi boleh mengumpukkan pembayaran ke rancangan ansuran.
Dengan tetapan Penyesuaian yang sesuai untuk kategori rancangan ansuran, anda boleh mengemas kini kepercayaan kredit bagi pekongsi perniagaan yang terlibat apabila anda mencipta rancangan ansuran.
Melalui konfigurasi yang sesuai daripada sebab penyahaktifan, anda boleh membalikkan entri kepercayaan kredit sekali lagi.
Paparan Perubahan Umpukan
Lihat cara umpukan sumber telah diubah dari semasa ke semasa.
Apabila umpukan dicipta, diubah atau dipadam, tindakan ini direkodkan secara automatik.
Klik pautan untuk buka senarai perubahan umpukan bagi tiga bulan lepas.
Anda boleh gunakan penapis untuk kecilkan atau lanjutkan senarai.
Jika pengurus projek memadam fungsi atau mengubah tarikh untuk pakej kerja dalam aplikasi pengurusan projek, umpukan atau segmen umpukan terjejas dengan perubahan inni akan dipadam secara automatik.
Anda akan melihat entri untuk perubahan ini dalam senarai perubahan umpukan tetapi anda tidak akan melihat apa-apa nilai dalam medan yang berkaitan dengan pakej kerja atau fungsi.
Aktiviti Tika
Bahagian yang menunjukkan semua tika situasi yang dipilih untuk pemantauan.
Anda mempunyai beberapa pilihan untuk memaparkan aktiviti tika yang aplikasinya dipaparkan mengikut entri yang dibuat dalam bahagian penapis:
Gabungan grafik dan berjadual memaparkan data
Paparan grafik sahaja
Paparan berjadual sahaja
Jika anda menggunakan paparan gabungan, apa-apa pemilihan yang anda buat dalam grafik juga ditunjukkan dalam paparan jadual.
Anda juga boleh memilih antara paparan grafik yang berbeza.
Varian Susut Nilai
Takrifkan jenis susut nilai amaun dipos atau amaun dirancang.
Susut Nilai aset dirancang dan dipos dalam jenis berbeza.
Pilih varian susut nilai ke laporan dipos dan amaun dirancang untuk satu daripada jenis susut nilai berikut:
Susut Nilai Biasa:
Pengurangan nilai disebabkan oleh susut nilai pada aset melebihi usia guna dijangka.
Susut Nilai Tidak Dirancang:
Pembetulan nilai tidak dirancang (disebabkan oleh kemalangan) menyebabkan pengurangan dalam nilai aset yang muncul untuk kekal.
Susut Nilai Khas:
Pembetulan nilai khas untuk sebab cukai yang dibenarkan dalam tambahan ke susut nilai biasa.
Pindahan Balikkan:
Pengeposan keuntungan (hasil daripada jualan aset) untuk aset penggantian juga dipanggil simpanan tersembunyi atau simpanan tidak didedahkan.
Mengikut undang-undang cukai dalam negara tertentu, keuntungan daripada jualan aset mengurangkan kos perolehan dan pengeluaran aset baru yang diperlukan.
Keuntungan dianggap sebagai pelarasan nilai pada sampingan liabiliti ke ofset kos perolehan dan pengeluaran.
Butiran Aplikasi Konfigurasi (Halaman Entri)
Lihat log aktiviti konfigurasi dan mulakan aplikasi konfigurasi
Dengan aplikasi ini, anda mendapat maklumat tentang aplikasi konfigurasi layan diri dan anda boleh paparkan log aktiviti konfigurasi.
Aplikasi memainkan pesanan bagi halaman entri ke aplikasi kkonfigurasi layan diri.
Ia juga menawarkan anda fungsi berikut:
Mulakan aplikasi konfigurasi layan diri.
Tambahkan nota (dengan status) berkenaan dengan aktiviti konfigurasi anda.
Sahkan bahawa anda telah menyemak tetapan.
Muat turun fail PDF yang mengandungi maklumat (perihalan) pada aplikasi konfigurasi layan diri dan sejarah aktiviti konfigurasi.
Edit Kod Arahan
Dayakan anda untuk mengedit kod arahan bagi pembayaran individu.
Dengan fungsi ini, anda boleh mengedit kod arahan untuk pembayaran individu dalam kelompok.
Anda boleh memilih dan mengedit pelbagai item pada masa yang sama tetapi hanya jika item terpilih mempunyai negara bank dan kaedah pembayaran yang sama.
Kod arahan memberi maklumat mengenai cara pembayaran perlu dilaksanakan.
Kod ini biasanya berkaitan dengan cara caj bank diselesaikan, tetapi juga memberi kesan segera pada pembayaran.
Kod arahan ditentukan dalam penyesuaian, dan negara bank dan kaedah pembayaran akan menentukan kod arahan yang tersedia.
Jangka Masa Penghantaran
Carta mikro memaparkan status proses penerimaan barangan dan perbandingan bagi masa berbeza.
Carta mikro memaparkan status proses penerimaan barangan dan perbandingan bagi masa berbeza: ia menunjukkan status hari ini berbanding dengan tarikh penghantaran ramalan bagi item bahan, contohnya, apabila tarikh sebenar melangkaui tarikh penghantaran ramalan, bar akan muncul dalam warna merah.
Carta mikro memaparkan maklumat berikut secara terperinci:
Sebenar:
Tarikh hari ini (tarikh sistem) atau nilai medan Hari sejak Tarikh Pengeposan
Sasaran:
Tarikh apabila pesanan belian (PO) dicipta adalah pada permulaan bar
Ramalan:
Masa dalam hari dari penciptaan pesanan belian ke tarikh sama ada yang diramalkan atau tarikh penghantaran terancang
Bahan Pukal
Menunjukkan capaian langsung ke komponen bahan pada pusat kerja.
Anda boleh memasukkan penunjuk bahan pukal dalam rekod induk bahan dan item bil bahan.
Jika bahan ditakrifkan sebagai bahan pukal, keperluan bersandar untuk bahan ini tidak berkaitan dengan MRP.
MRP untuk bahan pukal adalah berdasarkan penggunaan.
Penunjuk dalam rekod induk bahan
Anda boleh takrifkan bahan sebagai bahan pukal dalam data MRP bagi rekod induk bahan.
Jika anda menetapkan penunjuk bahan pukal dalam rekod induk bahan, sistem menetapkan bahan pukal dalam penunjuk induk bahan pada bil bahan.
Penunjuk dalam bil bahan
Penunjuk ini hanya disokong untuk item yang berkaitan dengan penyelenggaraan pengeluaran atau loji ataupun kedua-duanya.
Item tidak boleh berkaitan dengan pengekosan.
Anda tidak boleh memasukkan lokasi simpanan pengeluaran untuk bahan pukal.
Penunjuk dalam induk bahan menggantikan penunjuk dalam item bil bahan.
Penunjuk dalam item bil bahan memberitahu anda sama ada bahan yang ditakrifkan sebagai bahan pukal dalam induk bahan.
Jika bahan sentiasa digunakan sebagai bahan pukal, tetapkan penunjuk bahan pukal dalam rekod induk bahan.
Jika bahan hanya kadang-kadang digunakan sebagai bahan pukal, tetapkan penunjuk bahan pukal dalam item bil bahan
Jika bil bahan hanya diperuntukkan untuk satu loji, anda akan melihat nilai lalai daripada rekod induk bahan dalam loji ini apabila anda menciptanya.
Statistik Lanjutan
Tunjukkan ketersediaan statistik lanjutan yang dilog bagi setiap objek penghijrahan.
Untuk menyediakan statistik lanjutan, pilih Statistik dari lajur Statistik Lanjutan.
Dalam kotak dialog Statistik, pilih Pilih Kategori dan serlahkan semua kotak semakan bersebelahan dengan kategori yang diperlukan untuk pecahan.
Kemudian, Simpan perubahan anda.
Apabila statistik tersedia, kotak dialog yang sama memaparkannya untuk semua kategori yang dipilih.
Pemilihan kategori membawa anda ke senarai paparan keseluruhan rekod masing-masing untuk kategori ini.
Dapatkan maklumat lanjut pada ciri Statistik Lanjutan dalam bantuan produk.
Bahan Kredit / Debit
Laraskan nilai inventori
Membolehkan anda untuk melaraskan nilai inventori bahan.
Masukkan tarikh pengeposan dan teks pengepala bagi dokumen bahan.
Bagi semua jenis mata wang, tentukan amaun penilaian semula dan kuantiti rujukan untuk kos yang akan dipos.
Bergantung pada kawalan harga, amaun penilaian semula dipos ke akaun perbezaan harga dan/atau ke akaun stok bahan.
Bagi harga piawai bahan (kawalan harga S), amaun penilaian semula diposkan ke akaun perbezaan harga.
Harga piawai bahan tidak berubah.
Bagi perubahan harga purata bahan (kawalan harga V), amaun penilaian semula diposkan ke akaun stok bahan melainkan liputan stok tidak mencukupi.
Jika liputan stok tidak mencukupi, hanya bahagian stok tersedia diposkan ke akaun stok; bakinya diposkan ke akaun perbezaan harga.
Contoh bagi Perubahan Harga Purata
Bahan dengan kawalan harga V mempunyai kuantiti asas 100 unit dan kuantiti inventori 50 unit.
Nilai inventori ialah 500 EUR.
Jika anda masukkan pelarasan 100 EUR, 50 EUR diposkan ke akaun stok bahan dan 50 EUR diposkan ke akaun perbezaan harga.
Cipta ID Aplikasi Fiori
Penciptaan, Pengeditan dan Pemadaman ID Fiori
Lajur ini memaparkan sama ada pautan bagi mencipta ID fiori untuk SAC yang dipilih atau pautan untuk ID Fiori (jika sudah dicipta).
Pautan Cipta ID Fiori membenarkan anda untuk memasukkan butiran berkaitan dan menyimpan serta menerbitkan jubin untuk katalog.
Apabila menerbitkan jubin, ID Fiori dijanakan dan dipaparkan sebagai pautan bagi laporan SAC.
Untuk pautan ID Fiori yang sedia ada, anda boleh mengedit butiran atau memadam laporan SAC.
Jubin akan dipadamkan hanya jika jubin tidak diterbitkan ke katalog.
Sekiranya jubin diterbitkan ke katalog, maka anda mesti mengeluarkan, membatalkan dan memadamkan katalog dari aplikasi Sambungan Katalog Tersuai dan kemudian memadamkan jubin.
Statistik Lanjutan
Aplikasi ini kini menawarkan pengelogan statistik lanjutan setiap objek penghijrahan.
Dalam lajur Statistik Lanjutan, pilih Statistik untuk menunjukkan kotak dialog Statistik.
Pilih Pilih Kategori dan serlahkan semua kotak semakan bersebelahan dengan kategori yang diperlukan untuk pecahan.
Kemudian, Simpan perubahan anda.
Kotak dialog kini memaparkan statistik bagi semua kategori yang dipilih.
Pemilihan kategori akan membawa anda ke senarai paparan keseluruhan rekod masing-masing untuk kategori ini.
Dapatkan maklumat lanjut pada ciri Statistik Lanjutan dalam bantuan produk.
Pesanan untuk Pengeposan
Menunjukkan masa sebenar WIP berkaitan dengan pesanan yang masih mempunyai kos yang diposkan dan perlu diselesaikan sebagai WIP.
Menunjukkan masa sebenar Kerja dalam Proses berkaitan dengan pesanan yang masih mempunyai kos yang diposkan dan perlu diselesaikan sebagai WIP.
Sokong pengeposan pesanan tunggal dan pengeposan pesanan berbilang dengan penjadualan kerja.
Anda boleh menyemak jika semua pesanan sedia untuk pengeposan sebelum diposkan.
Hasil akan ditunjukkan dalam status simulasi akhir.
Pesanan yang berjaya diposkan tidak akan ditunjukkan dalam tab ini lagi - anda boleh memaparkannya dalam tab Pesanan Diposkan.
Gunakan Parameter Dinamik
Mendedahkan penapis dan parameter nilai tunggal sebagai parameter URL.
Pilih kota semak ini untuk takrifkan semua penapis dan parameter nilai tunggal dari konteks juga didedahkan sebagai parameter URL.
Dalam kes ini, setiap sifat konteks yang mempunyai nilai tunggal sahaja didedahkan sebagai pasangan kod nilai dalam URL.
Ini termasuklah set penapis global dalam bar penapis, pemilihan dalam langkah analisis dan penapis serta parameter diserahkan pada APF dari aplikasi lain.
Ini adalah berguna, contohnya, jika sasaran navigasi tidak boleh menggunakan konteks dari status aplikasi atau jika niat sasaran navigasi mempunyai parameter wajib yang harus disediakan sebagai parameter URL.
Parameter Dinamik berlaku dalam URL bagi aplikasi yang dipanggil.
Oleh itu, aspek perlindungan dan privasi data perlu dipertimbangkan.
Dengan lalai, kotak semak ini tidak dipilih.
Dalam kes ini, konteks aplikasi diserahkan ke sasaran navigasi menggunakan status aplikasi.
Kod Rujukan
Masukkan maklumat tambahan yang anda perlu untuk pemprosesan berikutan.
Dalam medan Kod Rujukan, anda boleh memasukkan butiran pelanggan/pembekal untuk transaksi perakaunan.
Masukkan butiran pelanggan/pembekal yang anda perlu untuk pemprosesan berikutan mengikut peraturan syarikat individu anda.
Entri ini kemudian digunakan sebagai maklumat tambahan untuk tujuan berikut:
Untuk penghubungan dengan pelanggan/pembekal
Sebagai kriteria carian untuk item dalam akaun pelanggan/pembekal
Entri yang mungkin boleh dilakukan seperti berikut:
Nombor cawangan pelanggan/pembekal
Nombor transaksi dalam transaksi kontroversial diuruskan pada pelanggan/pembekal
Hantar Semula
Hantar semula salinan dokumen pengebilan kepada pelanggan anda.
Pilih invois yang anda ingin hantar semula kepada pelanggan anda dan pilih Hantar Semula.
Status penghubung mesti ditetapkan kepada selesai sebelum anda boleh hantarnya semula.
Untuk menghantar semula penghubung:
Pilih dokumen pengebilan untuk dihantar semula dan pilih Hantar Semula.
Dokumen pengebilan baru muncul dalam senarai Butiran Output.
Pilih dokumen pengebilan baru, pastikan dokumen pengebilan asal tidak dipilih.
Pilih Hantar Output untuk menghantar penghubung sekali lagi.
Tarikh Rujukan
Pilih dan papar data induk bersandarkan masa.
Anda boleh menggunakan tarikh rujukan untuk memilih dan memaparkan data induk bersandarkan masa.
Contohnya, penetapan bulan semasa memilih data induk sah dalam rangka masa termasuk tarikh rujukan.
Anda juga boleh menguji hierarki dan laporan menggunakan tarikh rujukan masa hadapan.
Contohnya, anda mungkin mempunyai pengaturan semula terancang yang berkuat kuasa 1 Januari tahun seterusnya.
Pemilihan tarikh rujukan selepas 1 Januari membolehkan anda untuk melihat pratoton dan menguji kesahan hierarki dalam laporan anda bagi rangka masa itu.
Ia menghasilkan laporan dan hierarki yang sah dari 1 Januari tahun berikutnya.
Disalin
Senaraikan item dimuat naik yang mempunyai ID yang sama dengan item sedia ada dalam sistem sasaran.
Senaraikan peraturan, kaedah dan pemilihan yang dimuat naik dari hamparan dan mempunyai ID yang sama dengan yang sedia ada dalam sistem semasa anda.
Item sedia ada mungkin mempunyai status Aktif, Draf atau Tidak Aktif.
Oleh itu, anda perlu membandingkan pendua dan menentukan sama ada anda ingin langkau item dimuat naik atau importnya supaya item sedia ada ditulis ganti.
Jika anda pilih untuk mengimport juga item pendua, hanya versi draf bagi item sedia ada ditulis ganti kerana semua item yang diimport mempunyai status awalan Draf.
Walau bagaimanapun, tindakan Pengaktifan Besar-besaran berikutan boleh mengaktifkan item diimport ini dan menulis ganti peraturan, kaedah atau pemilihan sedia ada.
Jadualkan Jalanan Pemusnahan Data untuk Fail Pengarkiban
Anda boleh pilih sumber tamat tempoh yang akan dijadualkan untuk pemadaman.
Untuk menjadualkan jalanan pemusnahan data:
Pilih objek ILM dan papar lebih butiran seperti Sumber Tamat Tempoh yang dimiliki objek ILM dengan Tarikh Lupus dan Tarikh Pemusnahan Wajib.
Pilih sumber tamat tempoh yang anda ingin padam secara kekal dan klik Jadualkan.
Tetingkap timbul dipaparkan yang meminta pengesahan pemadaman.
Jika anda mengesahkan pemadaman, sumber tamat tempoh dijadualkan untuk jalanan pemusnahan data.
Apabila jadual seterusnya dijalankan dalam tujuh hari seterusnya, semua sumber tamat tempoh yang ditanda untuk pemadaman akan dimusahkan secara kekal.
Akaun Kontrak
Dengan spesifikasi dalam rekod induk akaun kontrak, anda boleh mengawal tatakerja perniagaan anda dan hubungan perniagaan dengan pelanggan anda.
Akaun kontrak menentukan struktur yang digunakan oleh sistem. Contohnya, mengeposkan data untuk kontrak atau menyelesaikan item kontrak untuk perjanjian yang sama digunakan.
Setiap rekod induk akaun kontrak terdiri daripada data umum yang digunakan untuk semua pekongsi perniagaan yang diumpukkan ke akaun kontrak.
Data ini termasuk kategori akaun kontrak, nombor akaun dari sistem legasi dan nama akaun kontrak.
Dengan cara lain, rekod induk dari data pekongsi perniagaan tertentu bagi setiap pekongsi perniagaan dalam akaun kontrak boleh ditetapkan secara berbeza.
Anda mengumpukkan setiap akaun kontrak ke kategori akaun kontrak apabila ia dicipta.
Kategori akaun kontrak menentukan atribut teknikal akaun kontrak dan secara tidak langsung memastikan ciptaan rekod induk.
Berikut menentukan kategori akaun kontrak. Contohnya, medan yang muncul apabila anda mencipta akaun kontrak.
Anda boleh mengumpukkan lebih daripada satu akaun kontrak kepada pekongsi perniagaan yang diberikan.
Demikian juga, akaun kontrak tunggal boleh diumpukkan lebih daripada seorang pekongsi perniagaan.
Dalam akaun kontrak, anda mentakrifkan tatacara pekongsi perniagaan tertentu yang digunakan oleh sistem untuk mengeposkan dan memproses item dokumen dari akaun yang berkaitan.
Dengan cara ini, anda membuat spesifikasi untuk pembayaran dan dunning.
Anda juga mentakrifkan penerima dan penerima alternatif untuk surat-menyurat.
Semua transaksi yang berkaitan dengan akaun kontrak mencapai data dari rekod induk akaun kontrak (seperti pembayaran dan dunning).
Beberapa transaksi mengubah data dalam rekod induk akaun kontrak.
Sistem melaksanakan pulangan. Contohnya, secara automatik menetapkan sekatan pembayaran dalam akaun kontrak.
Sistem melaksanakan akaun kontrak dengan pengurusan item terbuka.
Setiap pengeposan pekongsi perniagaan yang berkaitan diumpukkan kepada seorang pekongsi perniagaan dan satu akaun kontrak.
Tahap Log Proses
Menunjukkan status log untuk proses.
Berikut ialah nilai yang mungkin wujud bagi medan ini:
01 – Tiada Pengelongan
02 – Pengelongan Piawai
03 – Pengelongan Lanjutan
Guna:
Jika anda pilih tahap log sebagai Tiada Pengelongan, sistem tidak menjalankan sebarang pengelongan untuk takrifan proses.
Jika anda pilih tahap log sebagai Pengelongan Piawai, sistem menjalankan pengelongan untuk takrifan proses.
Jika anda pilih tahap log sebagai Pengelongan Lanjutan, sistem membenarkan anda untuk konfigurasikan pengelongan bagi proses pada tahap objek perniagaan.
Wajib
Menunjukkan jika pelanggan mesti sahkan konfigurasi.
Ia menunjukkan jika pelanggan mesti sahkan konfigurasi. Pengesahan selasai dalam fasa Terealisasi dan semua item wajib mestilah disahkan sebelum pelanggan boleh teruskan ke fasa Mengatur Kedudukan.
Nilai mungkin dan perkara yang mereka maksudkan:
Wajib bermaksud bahawa konfigurasi mestilah diselenggara dan disahkan dalam fasa Praset and Terealisasi.
Disyorkan bermaksud walaupun tidak diperlukan, ia disarankan untuk semak konfigurasi.
Pilihan bermaksud konfigurasi mungkin berkaitan dengan beberapa tetapi bukan semua pelanggan.
Semua Slot
Tapis paparan slot masa yang berbeza dalam jadual jujukan.
Anda boleh pilih mana-mana pilihan berikut:
Semua Slot- Paparkan semua slot masa tersedia untuk pusat kerja yang termasuk slot dengan pesanan yang diserahkan.
Slot dengan Kapasiti Mencukupi- Paparkan slot masa yang mempunyai kapasiti mencukupi untuk menampung operasi pesanan.
Slot dengan Kapasiti Pertindihan- Paparkan slot masa konflik bagi operasi pesanan berbilang yang telah diserahkan.
Anda boleh batalkan peruntukan dan serahkan satu daripada pesanan ke slot yang berbeza.
Menggunakan pusat keuntungan dan segmen dalam Papar Penyata Kewangan
Untuk memaparkan angka untuk segmen dan pusat keuntungan dalam hierarki, teruskan seperti berikut:
Dalam aplikasi, klik Penapis.
Dalam dialog Penapis, dalam bahagian Medan Khas, klik Lebih Penapis.
Dalam dialog Pilih Penapis, pilih Termasuk Segmen dan Termasuk Pusat Keuntungan.
Pilih Simpan untuk menyimpan tetapan anda sebagai varian atau Pergi untuk menyimpan tetapan anda bagi bahagian semasa.
Pilih Tetapan, pilih Segmen dan Pusat Keuntungan, dan klik OK.
Gabungan segmen dan pusat keuntungan ditunjukkan sebagai aras terendah untuk hierarki.
Navigasi ke Analisis Hutang dan Pelaburan
Navigasi ke aplikasi Analisis Hutang dan Pelaburan kini disokong.
Anda kini boleh navigasi ke aplikasi Analisis Hutang dan Pelaburan untuk semak butiran hutang dan pelaburan tertunggak.
Navigasi tersedia dari kad berikut:
Jumlah Amaun Hutang mengikut Tarikh Rujukan
Jumlah Amaun Pelaburan mengikut Tarikh Rujukan
Hutang/Pelaburan mengikut Kategori Faedah
Hutang/Pelaburan mengikut Kadar Faedah Rujukan
Jenis Mata Wang
Papar catatan jurnal dalam mata wang khusus.
Pilih mata wang untuk catatan jurnal.
Semua catatan jurnal akan dipaparkan dalam mata wang yang anda pilih.
Mata wang tersedia termasuk:
Mata Wang Kod Syarikat – Mata wang yang ditakrifkan dalam tetapan kod syarikat anda.
Mata Wang Baki Transaksi – Mata wang akaun G/L bagi catatan jurnal diposkan.
Mata Wang Transaksi – Mata wang bagi transaksi perniagaan asal yang terhasil dalam catatan jurnal.
Mata Wang Global – Mata wang telah dikonfigurasikan untuk bahagian pengawalan.
Bahan Tahap Teratas
Tunjukkan penggunaan kapasiti bagi bahan tahap teratas pusat kerja.
Anda boleh melihat sumbangan setiap bahan tahap teratas terhadap penggunaan kapasiti pusat kerja.
Jika terdapat isu kapasiti, anda boleh mempercepatkan masa permintaan kapasiti.
Semak jika ia akan mengurangkan isu kapasiti dan klik Anjakkan Permintaan Tahap Teratas.
Kemudian semak jika cadangan boleh diterima.
Dari bahan tahap teratas, anda boleh navigasi ke Simulasi Bahan Berbilang Tahap, paparan bil bahan berstruktur dan buat simulasi pada tahap komponen bahan.
Contohnya, anda boleh mengubah sumber bekalan atau menghasilkan komponen terlebih dahulu.
Teks Sudut
Taks dipaparkan dalam empat sudut bagi imej kecil langkah.
Taks dipaparkan dalam empat sudut bagi imej kecil langkah dalam paparan laluan analisis.
Semuanya ialah pilihan.
Teks sudut yang dimasukkan pada aras langkah digunakan sebagai lalai untuk teks sudut pada masa jalanan selagi tiada teks diselenggarakan pada aras perwakilan untuk sudut tertentu.
Ia juga digunakan untuk isian awal medan teks sudut pada aras perwakilan.
Semasa anda mengubah teks sudut tertentu pada aras langkah, perubahan ini digambarkan dalam perwakilan dan pada masa jalanan sahaja jika medan yang sepadan belum lagi diedit pada aras perwakilan.
Dinyahaktifkan/Boleh Diarkib
Aset yang telah dikeluarkan dari portfolio aset anda.
Aset dinyahaktifkan dan tarikh penyahaktifan disimpan apabila aset dikeluarkan dari portfolio aset syarikat anda.
Hal ini mungkin berlaku dalam salah satu dari beberapa cara, contohnya, dengan sekerap atau dijual.
Tidak kira sama ada hasil atau bukan hasil dijanakan oleh pembuangan aset dari portfolio, dari perspektif perakaunan, ia direkodkan sebagai penyahaktifan.
Aset mungkin tidak aktif dan dinyahaktifkan pada masa yang sama.
Sekiranya aset tetap sekerap atau dijual, sistem secara automatik mengumpukkan tarikh penyahaktifan kepada aset sebagai hasil daripada pengeposan penyahaktifan.
Secara lalai, aset yang dinyahaktifkan kekal dalam pangkalan data, tetapi adalah mungkin untuk memadamkan aset yang dinyahaktifkan tanpa pengeposan dan juga untuk mengarkibkan aset yang telah dinyahaktifkan selama lebih dari satu tahun.
Jangka Masa Penghantaran
Carta jangka masa penghantaran memaparkan status proses penerimaan barangan dan perbandingan bagi masa berbeza.
Carta jangka masa penghantaran memaparkan status proses penerimaan barangan dan perbandingan bagi masa berbeza: ia menunjukkan status hari ini berbanding dengan tarikh penghantaran ramalan bagi item bahan, contohnya, apabila masa transit melepasi tarikh penghantaran diramalkan, bar akan muncul dalam warna merah.
Carta jangka masa penghantaran memaparkan maklumat berikut secara terperinci:
Hari dalam Transit:
Tarikh hari ini (tarikh sistem) atau nilai medan Hari sejak Tarikh Pengeposan
Jangka Masa Penghantaran Ramalan:
Masa dalam hari dari penciptaan pesanan belian ke tarikh sama ada yang diramalkan atau tarikh penghantaran terancang
Perbezaan daripada yang Diumpukkan
Item kecairan yang berbeza daripada yang diumpukkan secara manual.
Anda mempunyai dua pilihan untuk medan ini.
Jika anda memilih ya, item kecairan yang berbeza akan dipaparkan.
Jika anda memilih tidak, item kecairan yang sama akan dipaparkan.
Jika tiada pilihan, semua item kecairan dipaparkan tanpa mengira perbezaan.
Secara lalai, Ya dipilih untuk medan ini, iaitu aliran tunai bagi item kecairan sebenar yang berbeza daripada dicadangkan oleh perkhidmatan pembelajaran mesin dipaparkan.
Masukkan Pelarasan Sementara
Selaraskan kos diperakui bagi jualan atau hasil diperakui
Benarkan anda untuk selaraskan kos diperakui bagi jualan atau amaun hasil diperakui secara manual.
Pelarasan adalah tulis ganti oleh penilaian semula, ini ialah, dengan sama ada berikut:
Fungsi Penilaian Semula dalam aplikasi ini
Jalanan pengecaman penilaian semula berkala dilaksanakan dengan aplikasi Jalankan Pengecaman Penilaian Semula - Pesanan Jualan
Fungsi penilaian semula janakan dokumen sumber
Status Jalanan Pengusiaan Data
Menunjukkan status jalanan pengusiaan data.
Berikut ialah status yang boleh dimiliki oleh jalanan pengusiaan data:
Jalanan Gagal - Menunjukkan yang jalanan pengusiaan data terakhir gagal.
Anda boleh semak sama ada objek pengusiaan data diumpukkan adalah aktif.
Jalanan Berjaya - Menunjukkan yang jalanan pengusiaan data terakhir berjaya.
Jalanan dalam Proses - Menunjukkan yang jalanan pengusiaan data terakhir dalam proses.
Jalanan tidak Dimulakan - Menunjukkan yang nilai ambang belum dicapai untuk objek pengagihan data bagi kumpulan pengusiaan data dipilih.
Dalam kes ini, jalanan pengagihan data tidak perlu dilaksanakan.
Pos Isu Barangan
Mencipta keluaran barangan semasa barangan bergerak keluar dari loji selepas penghantaran.
Semasa anda mengepos keluaran barangan untuk penghantaran keluar, fungsi berikut dijalankan pada asas dokumen keluaran barangan:
1.
Stok bahan gudang dikurangkan melalui kuantiti penghantaran
2.
Perubahan nilai dipos ke akaun kunci kira-kira, dalam perakaunan inventori
3.
Keperluan dikurangkan melalui kuantiti penghantaran
4.
Pengeposan keluaran barangan direkod secara automatik dalam aliran dokumen
Kumpulan Paparan
Untuk memaparkan subjumlah dua bahagian.
Kumpulan paparan terdiri daripada dua bahagian, biasanya bahagian unit utama dan bahagian unit pekongsi.
Setiap bahagian merumuskan jumlah subdataset.
Kumpulan paparan boleh digunakan untuk memaparkan subjumlah dalam paparan keseluruhan penyelarasan dan laporan butiran baki.
Contohnya, anda boleh mentakrifkan kumpulan paparan yang mempunyai dua bahagian:
Akaun belum bayar (AP) daripada unit utama (syarikat) dan akaun belum terima (AR) daripada unit pekongsi (syarikat pekongsi perdagangan).
Tetapan Pemberitahuan
Dalam bahagian ini, anda boleh menetapkan keutamaan anda untuk pemberitahuan.
Launchpad memaparkan pemberitahuan yang berkaitan dengan fungsi perniagaan anda seperti meninggalkan permintaan atau pesanan jualan.
Biasanya, terdapat perbezaan jenis pemberitahuan yang tersedia. Contohnya, pemberitahuan dalam launchpad, pemberitahuan mudah alih atau e-mel.
Anda boleh memperibadikan pelbagai keutamaan yang berkaitan dengan pemberitahuan yang anda ingin terima, dan cara serta lokasi ia dipaparkan.
Beberapa keutamaan pemberitahuan yang anda tetapkan menjejaskan semua jenis pemberitahuan, manakala yang lain adalah khusus untuk jenis pemberitahuan.
Untuk maklumat lanjut, lihat.
Kod Syarikat Global
Medan ini digunakan untuk tujuan berikut:
Kod syarikat yang terlibat dalam entri dokumen untuk sistem SAP luaran (ICT) sebagai penghantar atau penerima.
Jenis kod syarikat ini mesti mempunyai ID kod syarikat merentasi sistem (seperti EUROPA) sebagai tambahan pada ID kod syarikat tempatannya (seperti 0001).
Kod syarikat yang disediakan untuk senario pengagihan ALE.
Apabila menghantar IDoc dengan data bersandar kod syarikat, kod syarikat digantikan dengan kod syarikat merentasi sistem dalam semua medan kod syarikat.
Apabila menerima jenis IDoc ini, penukaran balikan berlaku pada sistem sasaran.
Kod merentasi syarikat boleh menjadi maksimum panjang 6 aksara dan abjad angka.
Gabung
Gabung dua Koleksi Perisian untuk menyelesaikan kebersandaran.
Untuk menyelesaikan kebersandaran koleksi perisian yang telah dieksport sebelum ini, anda boleh menggabungkan kedua-dua koleksi seperti contoh penggunaan berikut:
Sebaik sahaja koleksi perisian telah dieksport, item terkandung tidak boleh dikeluarkan atau ditambah ke koleksi perisian berbeza.
Koleksi Perisian B, Versi 3, mengandungi CustomBusinessObject_test
Koleksi Perisian A, Versi 2, mengandungi CustomBusinessObject_test
Semakan menunjukkan CustomBusinessObject_test telah diedit sejak eksport terakhir dan kini bersandar pada CustomCodeList_Test.
Perkara ini bermaksud, koleksi perisian B tidak boleh dieksport lagi kerana kedua-dua item mesti dieksport dalam koleksi perisian yang sama.
Oleh kerana kedua-dua koleksi perisian telah dieksport, pengeluaran CustomCodeList_Test dari Koleksi Perisian A dan penambahannya ke koleksi perisian B adalah tidak mungkin.
Untuk menyelesaikan kebersandaran, anda pilih Koleksi Perisian B dan klik Gabung.
Koleksi perisian B kini digabungkan dengan koleksi perisian A:
Koleksi Perisian A, Versi 3, mengandungi CustomCodeList_Test + CustomBusinessObject_test
Koleksi Perisian B, Digabungkan
Koleksi perisian B dilabelkan sebagai “Digabungkan” dan kini dalam mod baca sahaja.
Koleksi perisian B tidak boleh diedit lagi.
Jika anda tidak memerlukan sejarah versi koleksi perisian B, anda boleh memadamnya dari senarai.
Jenis Pengeposan
Jenis pengeposan (item baris) untuk dimasukkan.
Anda boleh pilih jenis pengeposan (item baris) yang anda ingin paparkan:
Semua – Semua pengeposan.
Sebenar – Hanya pengeposan tidak diperakui yang menunjukkan kos sebenar disimpulkan melalui operasi perniagaan seperti invois, cukai, dan lain-lain.
Diperakui – Hanya pengeposan yang ditentukan sebagai diperakui menggunakan model pengecaman hasil berasaskan acara.
Untuk mengetahui lebih lanjut mengenai pengecaman hasil berasaskan acara, lihat.
Stok Pembukaan
Pilih cara stok permulaan harus dikira untuk mempertimbangkannya bagi simulasi.
Penunjuk ini menentukan cara stok pembukaan yang akan dikira.
0 =
Tiada pembukaan stok
Perancangan simulasi tidak bermula dengan stok pembukaan.
1 =
Stok keselamatan sebagai stok permulaan
Sistem membaca stok keselamatan yang dimasukkan dalam rekod induk bahan.
2 =
Stok loji pada masa pindahan (tarikh semasa)
Sistem membaca stok loji semasa yang sah pada masa penjadualan.
3 =
Stok loji pada tarikh mula rujukan
Stok loji diunjurkan boleh dikira daripada stok semasa- atau situasi keperluan untuk tarikh mula objek rujukan.
Dikeluarkan
Item senarai yang telah dikeluarkan daripada giliran penghantaran.
Alih Keluar mengandungi senarai item yang diposkan dalam sistem SAP S/4HANA Cloud tetapi tidak berjaya dihantar kepada pekongsi dan kemudiannya dikeluarkan daripada giliran.
Anda boleh navigasi dari sini Uruskan entri Jurnal atauPenghantaran Maklumat Cukai untuk maklumat lanjut mengenai item.
Setelah anda navigasikan ke halaman Maklumat Cukai Dihantar untuk item, anda boleh hantar semula giliran.
Untuk dokumen balikan, anda juga boleh menunjukkan tiada pemprosesan lanjutan diperlukan untuk dokumen balikan dalam medan Nota.
Memilih item dan kemudian memilih Tiada Pemprosesan Diperlukan membolehkan anda untuk mengesahkan status dokumen balikan.
Sistem kemudiannya mengemas kini secara automatik senarai Dialih Keluar mengalihkan dokumen balikan ke Sejarah Proses dan membolehkan anda untuk fokus pada item yang memerlukan pemprosesan lanjutan.
Tambah Pembilang, Ukuran Terhad/Dikira/Ditukar
Pilihan ini membolehkan anda untuk mentakrifkan ukuran terhad, dikira atau ditukar dalam sumber data yang sepadan.
Ukuran Terhad:
Gunakan Ukuran terhad untuk mentakrif medan yang ditapis berdasarkan syarat tertentu.
Dengan menggunakan ukuran terhad untuk medan, anda janakan set hasil untuk analisis perbandingan data.
Ukuran Dikira:
Gunakan Ukuran Dikira untuk menukar daripada satu unit ukuran kepada yang lain.
Pilih “Edit” untuk mentakrif logik penukaran.
Editor memberikan anda elemen, pengendali dan fungsi analisis pratakrif untuk mentakrif ungkapan.
Ukuran Ditukar:
Gunakan Ukuran Ditukar untuk menukar unit atau ukuran mata wang daripada satu nilai kepada yang lain.
Pembilang:
Gunakan untuk mendapatkan kiraan berbeza bagi gabungan dimensi.
Senarai dimensi mungkin berbeza berdasarkan sumber data yang diperoleh.
Jenis Perolehan
Anda boleh menggunakannya untuk menapis produk anda berdasarkan jenis perolehan mereka
Anda boleh menggunakannya untuk menapis produk anda berdasarkan jenis perolehan mereka.
Dengan Penambahan Semula Didorong oleh Permintaan, jenis perolehan untuk produk adalah
dihasilkan sendiri Buat
dihasilkan dari sumber luaran Beli
dipindahkan menerusi STO Pindahan
Jika jenis perolehan untuk produk tidak diselenggarakan, ia akan muncul sebagai Hilang.
Unit Organisasi
Papar dan edit butiran unit organisasi.
Anak tetingkap ini menunjukkan butiran unit organisasi dipilih dalam struktur organisasi bahagian kiri.
Data berikut dipaparkan untuk unit organisasi (jika dapat dikenakan):
Unit khusus negara tanggungan
Hubungan dengan unit lain
Aplikasi konfigurasi (aktiviti) yang berkaitan dengan unit semasa.
Dari butiran unit organisasi, anda boleh menggunakan fungsi pengeditan berikut:
Cipta unit organisasi baru berdasarkan entiti semasa
Tambah unit organisasi tanggungan
Tambah hubungan dengan unit organisasi lain.
NOTA
Jika anda telah tambah unit atau hubungan, anda boleh lihat status perubahan anda dalam bahagian mesej di bahagian bawah anak tetingkap.
Tahun dan Tempoh Fiskal
Hanya menjejaskan data yang ditunjukkan dalam kad yang berpaut dengan baki aset.
Penapis Tempoh Fiskal dan Tahun Fiskal hanya menjejaskan data yang ditunjukkan dalam kad berikut:
Baki Aset
Baki Aset - Paparan Carta
Nilai Susut Nilai Aset
Aset dalam Pembinaan
Susut Nilai untuk Diposkan
Asal Aset
Data untuk kad lain adalah untuk tempoh fiskal semasa atau dipilih dalam kad itu sendiri.
Ubah Harga Masa Depan dengan Rujukan
Ubah harga masa depan berdasarkan jenis harga
Membolehkan anda mempunyai harga bahan masa depan berubah secara automatik berdasarkan jenis harga terpilih seperti harga terancang masa depan atau harga piawai.
Anda boleh melakukan perubahan pada permulaan tempoh seterusnya bagi tempoh semasa atau pada tarikh tertentu.
Apabila titik masa tertentu dicapai, harga masa depan diubah kepada jenis harga terpilih dalam semua mata wang dan penilaian dalam data lejar bahan serta dalam mata wang kod syarikat dalam induk bahan.
Faktor Tambahan
Bagi mengambil kira perubahan harga yang dijangka, anda boleh masukkan faktor tambahan untuk digunakan dalam harga masa depan baru.
Contohnya, untuk meningkatkan harga masa depan yang baru sehingga 10%, masukkan 1.1.
Kad Baharu Swap IR mengikut Tarikh Rujukan (Amaun Nominal dalam Mata Wang Paparan)
Aplikasi Paparan Keseluruhan Kadar Faedah menyediakan kad baharu untuk swap IR.
Berdasarkan kad ini, anda boleh melihat jumlah amaun nominal untuk Sisian Keluar dan Sisian Masuk bagi swap IR dipilih pada tarikh rujukan yang dimasukkan dalam mata wang paparan.
Anda melihat bar yang mewakili amaun nominal bagi swap IR untuk setiap mata wang transaksi pada carta bar yang dipaparkan,
Tip alatan tersedia untuk setiap bar yang anda boleh melihat amaun nominal.
Dengan mengklik pada carta bar, anda boleh navigasikan ke aplikasi pemprosesan kolektif untuk derivatif IR. iaitu anda mendapat senarai swap IR dipilih.
Anda boleh paparkan data transaksi kewangan bagi swap IR atau proses swap IR.
Ia juga boleh untuk mencipta swap IR baharu daripada aplikasi pemprosesan kolektif.
Prasyarat Aliran Kerja
Anda boleh takrifkan satu atau lebih prasyarat yang perlu dipenuhi sebelum aliran kerja permintaan memo kredit boleh diproses.
Takrifkan satu atau lebih prasyarat yang perlu dipenuhi sebelum aliran kerja permintaan memo kredit boleh diproses.
Jika satu daripada prasyarat tidak dipenuhi, aliran kerja tidak akan dimulakan.
Permintaan memo kredit disekat:
Permintaan memo kredit yang kini disekat ialah prasyarat wajib.
Nilai bersih lebih besar daripada:
Permintaan memo kredit melebihi amaun praktakrif yang boleh disediakan sebagai prasyarat tambahan.
Prapengeluaran
Pilih baris dan klik di sini untuk melihat masa yang dibolehkan untuk prapengeluaran bahan.
Untuk mengurangkan beban berlebihan kapasiti, anda mungkin dapat mempercepatkan masa pengeluaran komponen bahan dengan menggunakan slot kosong untuk prapengeluaran yang dicadangkan oleh sistem.
Teruskan seperti berikut:
Pilih baris komponen dengan keluaran.
Klik Prapengeluaran.
Semak slot yang tersedia untuk perancangan prapengeluaran.
Sistem mencadangkan pengagihan kapasiti.
Tentukan sama ada ia boleh diterima.
Klik Terima Pakai Cadangan jika anda bersetuju dengan pengagihan yang dicadangkan atau masukkan pengagihan berbeza.
Klik Gunakan.
Dokumen Sumber
Medan ini telah dinamakan semula daripada Dokumen Rujukan kepada Dokumen Sumber.
Medan Dinamakan Semula
Medan ini telah dinamakan semula daripada Dokumen Rujukan kepada Dokumen Sumber untuk meningkatkan kejelasan.
Fungsinya kekal sama:
Ia memaparkan bilangan dokumen sumber.
Nombor ini mengenal pasti secara unik dokumen sumber dalam sistem logik sumber iaitu asal bagi data pengebilan luaran dalam permintaan dokumen pengebilan luaran (EBDR) anda.
Jika EBDR dicipta dengan memuat naik data daripada hamparan, medan ini mengandungi nilai yang terkandung dalam baris hamparan yang berkaitan.
Uruskan Subpasukan
Umpukkan subpasukan
Untuk umpukkan atau batalkan subpasukan untuk pasukan dipilih, pilih Uruskan Subpasukan kemudian gunakan butang togol YA atau TIDAK daripada senarai Umpukkan Subpasukan.
Senarai termasuk subpasukan yang:
Kepunyaan kategori yang sama sebagai pasukan induk
Bukan kepunyaan hierarki lain
Terdapat nilai takrifan tanggungjawab yang sepadan dengan pasukan induk.
Untuk mengelakkan umpukan semula subpasukan sedia ada, pasukan anak subpasukan disembunyikan daripada paparan selepas subpasukan diumpukkan ke pasukan induk.
Apabila anda batalkan subpasukan, pasukan anak ditunjukkan dalam paparan.
Keutamaan
Takrifkan pesanan keperluan isihan.
Dalam subbahagian Keutamaan anda boleh letakkan atribut isihan ke dalam jujukan, sama ada dengan memasukkan atribut isihan secara manual (entri mungkin kemudian dicadangkan oleh aplikasi) atau, secara alternatif, dengan memilih atribut dalam Pilih:
Dialog Atribut Isihan.
Anda boleh gunakan fungsi isihan piawai ke pesanan atribut dan gunakan Menaik dan Menurun untuk umpukan arah isihan.
Butang piawai tersedia untuk tindakan berikut:
Menambah atribut isihan
Keluarkan atribut isihan dipilih
Menggerakkan atribut isihan yang dipilih ke atas atau ke bawah
Menggerakkan atribut isihan yang dipilih ke atas atau ke bawah
Butang tertentu adalah aktif untuk tindakan di atas sahaja apabila sekurang-kurangnya satu atribut isihan dipilih dan tindakan yang sepadan boleh dijalankan.
Untuk paparan keseluruhan atribut isihan tersedia, lihat.
Kriteria Pemilihan
Takrifkan asas untuk keperluan penapis.
Anda boleh gunakan medan Kriteria Pemilihan untuk takrifkan cara anda mahu tapis senarai keperluan segmen yang anda konfigurasikan.
Kriteria pemilihan dikonfigurasikan menggunakan penyata syarat dalam Penapis Keperluan.
Nilai dicadangkan untuk syarat akan muncul semasa anda menaip dan segmen disimpan sebagai versi draf sebaik sahaja kursor anda meninggalkan medan teks.
Contohnya:
Dengan memasukkan Bahan, cadangan yang muncul pada aplikasi ialah Bahan Dokumen ATP.
Dengan memasukkan ialah, cadangan yang akan muncul pada aplikasi ialah ialah sama dengan.
Dengan memasukkan Loji, cadangan yang akan muncul pada aplikasi ialah Loji Dokumen ATP.
Pastikan anda menggunakan nilai data kurungan apabila mencipta penapis, contohnya, 'ATP01'.
Untuk menapis keperluan untuk bahan ATP01 dalam loji 0001, anda boleh konfigurasikan syarat anda seperti berikut:
Bahan Dokumen ATP sama dengan 'ATP01' dan Loji Dokumen ATP sama dengan '0001'.
UI dan Laporan
UI dan laporan boleh perluas untuk konteks perniagaan dipilih.
Sebagai tambahan kepada butiran, anda boleh navigasikan ke aplikasi sepadan daripada:
Nama UI - navigasi ke SAP Fiori Apps Reference Library.
Ini adalah tempat yang anda boleh cari butiran mengenai aplikasi Fiori
Medan Tersuai Ditambah - navigasikan ke aplikasi Medan dan Logik Tersuai.
Ini adalah tempat yang anda boleh cipta atau papar butiran mengenai medan tersuai
Tarikh Sah
Memaparkan rangka masa yang sah untuk hierarki ini.
Sila ambil perhatian bahawa bukan semua hierarki memerlukan rangka masa kesahan.
Dalam kes ini, medan ini memaparkan N/A untuk menunjukkan yang rangka masa kesahan tidak dapat digunakan untuk jenis hierarki ini.
Contohnya, hierarki akaun G/L dan hierarki segmen tidak memerlukan rangka masa kesahan.
Kedua-dua jenis hierarki memaparkan N/A dalam medan ini.
Tambahan lagi, mana-mana hierarki yang anda cipta menggunakan aplikasi Uruskan Jenis Hierarki Tersuai tidak bersandarkan masa dan memaparkan N/A di sini.
Versi Aktif Berbilang
Anda boleh cipta dan selenggara versi aktif berbilang bagi hierarki anda.
Anda boleh cipta versi aktif berbilang bagi hierarki anda.
Setiap hierarki aktif harus mempunyai rangka masa kesahan diskret dan tidak boleh bertindih dengan rangka masa kesahan hierarki aktif yang lain.
Mempunyai versi aktif berbilang membantu untuk merancang pengaturan semula pada masa hadapan atau untuk tujuan pelaporan.
Contohnya, jika prinsip perakauan berubah, anda boleh mendapatkan hierarki yang sah di bawah kedua-dua set peraturan.
Versi aktif berbilang juga membuatkan ianya mudah, contohnya, untuk jalankan laporan perbandingan dan untuk sediakan laporan kewangan luaran.
Maklumat Kualiti
Prestasi versi model dinilai menggunakan dua penunjuk utama.
Prestasi versi model dinilai menggunakan dua penunjuk utama: kuasa ramalan dan keyakinan ramalan.
Kuasa ramalan ialah penunjuk kualiti versi model.
Keyakinan ramalan ialah penunjuk keteguhan versi model.
Dua nilai digabungkan ke dalam penarafan bintang kualiti.
Simbol bintang dinilai 1 hingga 5.
(Satu - lima bintang, lima bintang menunjukkan kualiti terbaik).
Aplikasi Model Ramalan menilai kualiti versi model dari segi keyakinan ramalan dan kuasa ramalannya.
Penunjuk kualiti ini membantu menentukan sama ada versi model digunakan atau tidak untuk membuat ramalan.
Simulasi Rancangan Kapasiti
Memberi paparan keseluruhan mengenai situasi kapasiti pusat kerja kepada anda.
Dalam Simulasi Rancangan Kapasiti, kapasiti pusat kerja dipaparkan dalam tempoh masa yang ditetapkan (baldi).
Anda boleh papar semua bahan tahap teratas bagi pusat kerja.
Keluaran kapasiti diserlahkan dengan warna merah.
Klik sel berwarna merah dan gunakan pemeriksa untuk memberitahu dan menyelesaikan keluaran kapasiti.
Anda boleh memilih untuk meningkatkan kapasiti tersedia.
Semak perkongsian dalam penggunaan setiap bahan sebelum mengubah kapasiti tersedia dan lihat jika situasi kapasiti bertambah baik.
Permintaan Sumber
Terdapat permintaan sumber yang anda bertanggungjawab.
Jadual ini menunjukkan permintaan sumber yang anda bertanggungjawab dan untuk kriteria penapis yang digunakan.
Permintaan sumber sepadan dengan fungsi yang perlu kakitangan untuk pakej kerja dalam projek pelanggan atau projek dalaman.
Anda bertanggungjawab untuk permintaan sumber yang diumpukkan ke salah satu organisasi perkhidmatan.
Pratetap tempoh, bergantung pada kad daripada aplikasi yang anda lancarkan.
Anda boleh ubah tempoh masa dan kriteria penapis lain dalam bar penapis.
Untuk tunjukkan maklumat lanjut dalam jadual, tambah lajur tambahan menggunakan ikor gerigis.
Untuk papar maklumat lebih terperinci untuk permintaan sumber khusus, klik pada baris jadual berkaitan.
OData
Garis panduan baru semasa menggunakan paparan CDS tersuai dalam senario OData.
Jika anda menggunakan paparan CDS tersuai dalam perkhidmatan OData, pastikan anda mengikut garis panduan berikut:
Paparan CDS tersuai tidak boleh mempunyai kebersandaran kepada mana-mana paparan CDS induk.
Paparan CDS tersuai tidak boleh digunakan sebagai sumber data untuk paparan CDS tersuai lain.
Paparan CDS tersuai tidak boleh mempunyai kebersandaran kepada mana-mana paparan CDS belum dihantar yang disediakan oleh SAP.
Paparan CDS tersuai tidak boleh diubah jika ia adalah sebahagian daripada perkhidmatan OData yang digunakan dalam senario komunikasi aktif.
Pesanan untuk Penyelesaian
Paparkan pesanan yang disahkan yang belum lagi disiapkan secara teknikal atau untuk perniagaan
Pada kad Pesanan untuk Penyelesaian, anda boleh menganalisis dan memantau pesanan penyelenggaraan disahkan untuk mana-mana tarikh akhir dengan memilih tempoh rujukan tetapi ia secara teknikalnya belum lagi selesai.
Jika anda mahu paparkan semua pesanan disahkan dalam senarai dan selesaikannya, klik pada kad.
Senarai paparkan, contohnya, data individu untuk dihubungi bagi individu yang bertanggungjawab.
Anda boleh paparkan objek teknikal yang telah diumpukkan dan cabangkan ke pemprosesan pesanan.
Anda juga boleh pilih pesanan secara langsung dalam senarai dan selesaikan ia secara teknikal atau untuk perniagaan dengan memilih status yang sesuai dalam bar alat butang tekan bagi jadual.
Jika anda klik pada bahagian sebelah kanan, anda boleh melihat pesanan penyelenggaraan yang disahkan dengan maklumat yang lebih penting dipaparkan pada kad dalam karusel.
Di sni anda boleh melihat, contohnya, sama ada terdapat pesanan belian tertunggak, perkhidmatan tertunggak atau tempahan tertunggak untuk pesanan.
Daripada kad untuk pesanan individu dalam karusel, anda juga boleh cabangkan ke pemprosesan bagi pesanan yang sesuai atau selesai pesanan langsung secara teknikal.
Peraturan Penomboran Akaun
Menunjukkan struktur Akaun Lejar Am berbilang aras di China.
Peraturan penomboran ialah struktur asas untuk akaun Lejar Am berbilang aras.
Nombor menentukan panjang setiap aras akaun.
Setiap aras dipisahkan oleh pemisah lalai -.
Bilangan aras akaun G/L dalam jadual di bawah dikira oleh sistem sewajarnya.
Contohnya, untuk syarikat dengan peraturan nombor akaun 4-2-2, akaun Aras 1 mengandungi 4 digit, akaun Aras 2 mengandungi 6 digit dan akaun Aras 3 mengandungi 8 digit.
Akaun 10010101 ialah akaun aras 3.
Padanan Automatik
Untuk menjalankan padanan berdasarkan peraturan dalam kaedah pemadanan semasa.
Pilih butang untuk menjalankan padanan automatik bagi unit utama dan unit pekongsi yang ditentukan berdasarkan kaedah.
Semasa jalanan pemadanan, butang Umpukan, Komunikasi, dan Padanan Automatik berwarna kelabu.
Berikut adalah untuk mengelakkan aktiviti serentak pada set data yang sama dan untuk mengelakkan apa-apa ketakkonsistenan data.
Setelah selesai pemadanan, butang didayakan sekali lagi dan data disegar semula.
Untuk mana-mana umpukan sedia ada yang mempunyai kotak semak kod sebab Resolusi sementara dipilih, batalkan umpukan jalanan pemadanan dan mentaksahkan nombor umpukan, membaca dan memadankan semula data terkini daripada sumber data yang berkaitan, menyegarkan semula status pemprosesan dan memicukan apa-apa tindakan susulan yang diperlukan mengikut kod sebab.
Walau bagaimanapun, jika umpukan masih dalam proses pelarasan atau aliran kerja kelulusan automatik, jalanan padanan automatik melangkauinya.
Pesanan Pemprosesan
Jujukan dalam mana-mana syarat yang dilaksanakan.
Ini ialah tempat yang anda boleh takrifkan jujukan dalam mana-mana syarat yang dilaksanakan.
Syarat yang lebih bergranul (dengan lebih penapis) sentiasa perlu dilaksanakan sebelum syarat yang ditakrifkan lebih meluas yang berfungsi sebagai gantian.
Oleh itu, anda hanya boleh mencipta satu syarat yang tidak mempunyai apa-apa penapis.
Syarat ini perlu menjadi terakhir dalam senarai.
Sebagai nombor syarat 1 dalam jujukan syarat, anda takrifkan loji A dalam negara B untuk memicu tika situasi.
Sebagai syarat 2, anda takrifkan loji B dari negara B.
Sebagai syarat 3, anda tidak takrifkan loji tetapi negara B.
Kawalan Pemeriksaan
Kenal pasti dalam rekod maklumat kualiti sama ada lot pemeriksaan dicipta.
Tetapan berikut tersedia:
Pemeriksaan Aktif Jika Pembekal Tidak Diperakui
Lot pemeriksaan dicipta jika tetapan dalam induk bahan memerlukannya dan jika tiada fungsi kawalan utama lain.
Tiada Pemeriksaan
Tiada lot pemeriksaan dicipta walaupun induk bahan memerlukan pemeriksaan.
Pemeriksaan Aktif Tanpa Mengambil Kira Perakuan Pembekal
Lot pemeriksaan sentiasa dicipta.
Bahan dengan Sumber Tidak Sah
Tunjukkan jumlah bilangan bahan dengan sumber bekalan tidak sah.
Anda boleh melihat jika bahan mempunyai sumber bekalan tidak sah dan bilangan bahannya.
Anda boleh menyemak bahan yang tiada sumber bekalan yang sah dalam paparan Simulasi Rancangan Permintaan dan Simulasi Bahan Berbilang Tahap.
Klik isu.
Kemudian semak Isu di bawah kategori isu Tiada Sumber Sah dan lihat butiran lanjut mengenai bahan khusus yang tiada sumber bekalan yang sah.
Contohnya, anda boleh melihat minggu atau bulan yang ketiadaan sumber bekalan dan tidak berjaya menjalankan perolehan.
Sejarah Proses
Sejarah Proses menunjukkan kepada anda status pemprosesan semasa bagi item anda.
Contohnya, item ditanda Dihantar Semula telah dipegang sebelumnya di bawah Dialih Keluar, kemudian dibetulkan dan berjaya dihantar semula.
Lajur Status Proses juga mengesahkan bahawa item balikan telah diproses.
Item ini ditanda dengan status proses Dibalikkan.
Memilih Hantar ID Rekod atau anak panah pada akhir baris item membawa anda ke halaman Maklumat Cukai Dihantar.
Log Aktiviti memaparkan sejarah pemprosesan lengkap termasuk tarikh item yang telah diproses, oleh mana-mana individu dan status untuk setiap langkah dalam sejarah proses tersebut.
Penunjuk Peruntukan Bahan
Penunjuk yang mengenal pasti item bil bahan yang disediakan oleh pelanggan atau oleh vendor.
Dalam ledakan bil bahan, anda menggunakan penunjuk ini untuk mengehadkan item dipilih.
Terdapat dua jenis peruntukan bahan:
Bahan yang disediakan oleh vendor
Bahan yang disediakan oleh pelanggan
Anda menggunakan penunjuk peruntukan bahan (MPI) untuk mengenal pasti jenis subkontrak bahagian.
Penunjuk berikut disediakan:
Bahan kerja semula untuk subkontraktor (nilai S dalam sistem SAP piawai)
Bahan kerja semula daripada subkontraktor (nilai X dalam sistem SAP piawai)
Penghantaran seterusnya (nilai F dalam sistem SAP piawai)
Jika anda tidak memasukkan maklumat dalam medan ini, komponen disediakan kepada subkontraktor sebagai bahan boleh digunakan (nilai asal dalam sistem SAP piawai).
Pengeposan Cukai dalam Kontrak Akaun Belum Terima dan Belum Bayar
Dalam Kontrak Akaun Belum Terima dan Belum Bayar, sistem secara automatik menentukan amaun cukai berdasarkan perbelanjaan dan item hasil.
Dalam aplikasi Uruskan Penyelesaian Anda di bawah Konfigurasikan Penyelesaian Anda, anda mentakrifkan akaun yang sistem harus poskan amaun cukai di bawah Kewangan Perakaunan Kontrak Pengeposan dan Dokumen Takrifkan Akaun untuk Cukai Jualan / Belian.
Jika anda mengeposkan dokumen dalam Kontrak Akaun Belum Terima dan Belum Bayar secara manual, anda juga boleh pilih untuk memasukkan amaun asas cukai secara manual.
Dalam kedua-dua kes, sistem menyemak amaun cukai pada aras dokumen dan mengeposkan amaun cukai ke akaun cukai.
Untuk pengeposan dan pengurangan diskaun, sistem membetulkan cukai secara automatik.
Anda membuat tetapan yang diperlukan untuk pengeposan automatik bagi cukai dalam langkah konfigurasi Takrifkan Akaun untuk Cukai Jualan / Belian.
Penentuan Amaun Cukai
Sistem mengira amaun asas untuk menentukan amaun cukai.
Komponen amaun asas bergantung pada negara.
Sistem mengawal penentuan automatik bagi amaun cukai menggunakan kod cukai.
Dalam aplikasi Uruskan Penyelesaian Anda di bawah Konfigurasikan Penyelesaian Anda, anda takrifkan kod cukai di bawah Kewangan Pelaporan Berkanun Cukai Takrifkan Kod Cukai untuk Jualan dan Belian.
Sistem mencadangkan kategori cukai apabila anda mentakrifkan kod cukai.
Kategori cukai termasuk cukai yang berkaitan untuk negara yang diberi atau kumpulan negara seperti cukai output di Jerman atau cukai jualan di Amerika Syarikat.
Kategori cukai juga menentukan cara amaun cukai dikira dan diposkan.
Sistem menentukan kategori cukai menggunakan kod negara yang anda masukkan ketika mentakrifkan kod cukai.
Akaun Cukai
Dalam data induk bagi akaun G/L, anda boleh menentukan jika akaun ialah akaun cukai dan jenis cukai yang boleh diposkan ke akaun menggunakan aplikasi Uruskan Data Induk Akaun G/L.
Untuk semua akaun G/L lain, anda boleh menentukan jenis cukai dalam rekod induk atau menentukan akaun tersebut tidak berkaitan untuk cukai.
Anda juga boleh membezakan akaun cukai mengikut kod cukai.
Oleh sebab pulangan lanjutan untuk cukai ke atas jualan/belian dijanakan daripada dokumen, akaun cukai menggunakan kod cukai tidak perlu dibezakan.
Ia bermaksud dalam rekod induk akaun G/L, anda sebagai pihak lain boleh menentukan sama ada akaun hanya boleh diposkan dengan kod cukai tertentu.
Bagi pihak lain, anda boleh menggunakan penentuan akaun (langkah konfigurasi takrifkan akaun untuk cukai jualan / belian) untuk mentakrifkan sama ada akaun cukai lain diposkan bagi setiap kod transaksi.
Akaun G/L bagi Setiap Kod Cukai
Carta Akaun
Carta Akaun Jerman
Transaksi/Kod Akaun
Cukai Output
Penentuan Akaun Menggunakan Kod Transaksi
Kod Transaksi
Akaun G/L
Penilaian Semula
Kira semula nilai untuk elemen.
Kira semula nilai jika anda mengubah kos terancang misalnya.
Anda boleh simulasikan penilaian semula sebelum pengeposan.
Nilai yang dikira semula diserlahkan dengan warna.
Ambil perhatian bahawa dengan hanya mengubah kod dirancang tidak menjejaskan nilai pengecaman hasil.
Anda perlu memicu kemas kini dengan fungsi ini.
Simulasi Rancangan Permintaan
Menunjukkan kuantiti permintaan setiap baldi.
Simulasi Rancangan Permintaan memaparkan jadual dengan semua keperluan kebersandaran dirancang untuk bahan tertentu setiap baldi (bulan atau minggu).
Untuk mengubah kuantiti permintaan, klik sel lajur yang menunjukkan kuantiti permintaan rancangan simulasi.
Sel berwarna merah menunjukkan keluaran kapasiti.
Klik sel tersebut untuk melihat butiran lanjut mengenai keluaran.
Kuantiti Dipaparkan
Rujukan/ Simulasi
Anda boleh paparkan kuantiti rujukan dan kuantiti simulasi secara bersebelahan.
Kuantiti dipaparkan setiap bulan atau minggu.
Kuantiti permintaan berdasarkan rancangan rujukan ditunjukkan di sebelah kiri dan kuantiti simulasi di sebelah kanan.
Anda boleh ubah kuantiti simulasi.
Simulasi Sahaja
Anda hanya boleh memaparkan kuantiti simulasi yang boleh anda ubah.
Delta Rujukan dan Simulasi
Anda hanya boleh memaparkan delta kuantiti permintaan berdasarkan rancangan rujukan dalam perbandingan dengan kuantiti permintaan yang berubah bagi rancangan simulasi anda.
Fokus paparan Simulasi Rancangan Permintaan terletak pada kuantiti permintaan manakala fokus paparan Simulasi Rancangan Kapasiti terletak pada kapasiti pusat kerja.
Semak kedua-dua paparan fokus untuk mendapatkan keputusan yang tepat.
Ujian Proses Anda
Cipta dan sesuaikan rancangan ujian untuk menguji tatakerja perniagaan anda.
Capai aplikasi ujian untuk menyemak ketepatan tatakerja perniagaan yang telah diaktifkan dan dikonfigurasikan menggunakan aplikasi Urus Proses Ujian Anda.
Anda boleh jalankan aktiviti berikut:
Cipta rancangan ujian
Jalankan rancangan ujian
Sesuaikan data ujian
Kaitan Sah Kuasa
Gunakan medan ini untuk mencari kategori yang berkaitan sah kuasa.
Anda boleh mencari kategori yang ditanda sebagai kaitan sah kuasa.
Untuk kategori ini, semakan sah kuasa menentukan sama ada pengguna dibenarkan untuk papar, ubah, cipta, dan / atau kemas kini kategori masing-masing.
Kategori tanpa bendera Kaitan Sah Kuasa adalah diabaikan dalam semakan sah kuasa ini.
Untuk melihat konteks atau transaksi undang-undang, pengguna perlu mempunyai sah kuasa untuk semua kategori yang ditakrifkan untuk konteks atau transaksi undang-undang.
Jika, contohnya, transaksi undang-undang diumpukkan kategori “Rahsia Penting”, “ERP” dan “Bahagian Jualan”, tetapi pengguna hanya dibenarkan untuk “Rahsia Penting” dan “ERP” dan bukan untuk “Bahagian Jualan”, individu tersebut tidak akan dapat melihat transaksi undang-undang.
Uruskan Tag
Tambah atau padam tag ke paparan CDS dipilih
Anda guna medan ini untuk tambah atau padam tag ke paparan CDS dipilih.
Pilih paparan, kemudian klik butang Uruskan Tag dan tambah tag.
Anda juga boleh taip huruf pertama atau beberapa huruf tag yang ditambah.
Tag yang sepadan dengan kriteria akan dipaparkan.
Tag berbilang boleh ditambah kepada tag dipilih.
Bilangan tag bagi paparan yang berkaitan dipaparkan sebagai pautan.
Klik pautan untuk urus tag.
Perkadaran untuk Keselamatan
Kelas
Hasil perkadaran kredit untuk kelas perkadaran.
Menunjukkan hasil bagi perkadaran untuk kelas keselamatan yang dikemukakan oleh agensi perkadaran kredit.
Anda perlu paparkan kelas keselamatan dengan perkadaran kredit yang baik.
Anda kemudiannya memilih agensi perkadaran, contohnya Moody's.
Kemudian anda memilih perkadaran, contohnya AAA.
Kemudian anda boleh melihat kelas keselamatan dengan perkadaran Moody's AAA
Pilihan
Membuat pilihan tindakan untuk status pelaksanaan rancangan ujian menggunakan butang togol.
Anda boleh membuat pilihan tindakan menggunakan butang togol.
Tindakan pilihan bermaksud yang ia dilaksanakan tetapi status pelaksanaannya tidak akan memberi kesan kepada status proses ujian dan status pelaksanaan rancangan ujian.
Contohnya, jika terdapat 10 tindakan dalam langkah proses dan tindakan ke 5 adalah tindakan pilihan.
Semasa pelaksanaan ujian, jika tindakan ke 5 gagal, tindakan ke 6 akan dilaksanakan.
Jika semua tindakan berikutan lulus, status langkah proses menjadi Berjaya dan oleh sebab itu, status rancangan ujian menjadi Berjaya.
Balikkan
Balikkan catatan jurnal.
Balikkan catatan jurnal yang terpilih.
Anda juga boleh memilih pelbagai catatan jurnal dan balikkan semuanya secara serentak.
Anda biasanya poskan pembalikan dalam tempoh yang sama dengan catatan jurnal asal.
Jika tempoh itu ditutup, masukkan tarikh pengeposan yang berada dalam tempoh terbuka.
Hanya catatan jurnal dicipta dalam Perakaunan Kewangan boleh dibalikkan.
Anda tidak boleh balikkan catatan jurnal dengan dokumen sumber (seperti keluaran barangan atau invois pelanggan) kerana catatan jurnal asal di luar Perakaunan Kewangan.
Jika anda memilih campuran entri dengan dan tanpa dokumen sumber, hanya entri tanpa dokumen sumber dibalikkan.
Butang Balikkan berwarna kelabu jika anda hanya memilih catatan jurnal dengan dokumen sumber.
Membalikkan Urus Niaga Antara Syarikat
Urus niaga antara syarikat sentiasa melibatkan dua atau lebih catatan jurnal.
Jika anda mahu pastikan semua catatan jurnal untuk urus niaga antara syarikat dibalikkan, pilih Proses Urus Niaga Antara Syarikat Sepenuhnya.
Proses ini membalikkan semua catatan jurnal yang terlibat dalam urus niaga antara syarikat walaupun anda tidak memilih semua entri.
Jika anda tidak memilih Proses Urus Niaga Antara Syarikat Sepenuhnya, hanya catatan jurnal yang anda pilih dibalikkan.
Simpan
Gunakan fungsi ini untuk simpan perubahan anda.
Anda gunakan fungsi ini untuk simpan perubahan yang telah anda lakukan tanpa mencipta versi baru konteks.
Menyimpan perubahan hanya mungkin dalam kes ini:
Jika konteks tidak lagi diumpukkan ke transaksi undang-undang.
Jika anda hanya lakukan perubahan kecil ke konteks yang telah digunakan dalam transaksi undang-undang, seperti mengubah tarikh akhir konteks.
Jika anda cuba gunakan Simpan untuk perubahan kecil, sistem keluarkan mesej ralat yang memaklumkan bahawa anda tidak boleh simpan kerana draf tidak konsisten.
Tetingkap ralat di sudut bawah kiri mesej ralat berikut dikeluarkan:
Konteks mempunyai perubahan penting; simpan sebagai versi baru.
Pemilik
Gunakan medan ini untuk carian tanggungjawab individu untuk konteks.
Anda gunakan medan ini untuk carian tanggungjawab individu untuk konteks.
Per lalai, pengguna yang mencipta konteks merupakan pemilik bagi konteks.
Walau bagaimanapun, hal ini boleh diubah pada bila-bila masa kepada pengguna yang sebenarnya bertanggungjawab untuk konteks daripada kandungan masing-masing.
Pemilik konteks, walau bagaimanapun, adalah bukan keperluan individu yang selenggara konteks dalam sistem.
Anda boleh masukkan nama secara langsung, atau gunakan bantuan nilai untuk pilih pengguna.
Muat naik
Selepas menyelenggara nilai kod dalam templat, anda boleh muat naiknya ke aplikasi.
Selepas menyelenggara nilai dalam templat, anda boleh muat naik perubahan anda.
Pastikan anda simpan templat dalam CSV UTF-8
Tiada nilai akan ditulis ganti, nilai hanya akan ditambah ke dalam senarai.
Jika anda telah menyelenggara terjemahan, selenggara bahasa terjemahan dengan mengklik Terjemahan Pilih Bahasa.
Anda boleh pilih semua bahasa yang anda telah selenggara dalam fail csv atau terjemahkan secara langsung dalam aplikasi.
Nama Aplikasi Baru
Aplikasi ini telah dinamakan semula kepada Uruskan Permintaan Dokumen Pengebilan.
Aplikasi ini telah dinamakan semula daripada Uruskan Permintaan Dokumen Pengebilan Luaran kepada Uruskan Permintaan Dokumen Pengebilan untuk membolehkan sambungan konsep permintaan dokumen pengebilan (BDR) yang akan datang.
Fungsinya kekal sama:
Ia memaparkan paparan keseluruhan butiran BDR.
Dalam keluaran semasa, permintaan dokumen pengebilan luaran (EBDR) merupakan jenis permintaan dokumen pengebilan (BDR) yang mungkin.
Oleh itu, halaman objek hanya boleh memaparkan EBDR buat masa ini.
Keserasian Keluaran
Lajur menunjukkan keserasian keluaran untuk proses ujian tersuai.
Semasa pengeditan sebarang proses ujian tersuai, anda boleh sahkan Keserasian Keluaran untuk sebarang langkah proses tersuai dengan klik pada ikon.
Sistem akan mencadangkan status berdasarkan pada perubahan dalam aplikasi UI.
Sistem akan mencadangkan salah satu daripada penunjuk Akan Disahkan oleh Pengguna, Tidak Serasi, Serasi.Apabila terdapat perubahan yang ketara dalam Aplikasi yang digunakan oleh langkah proses ujian Tersuai, ianya akan memberi kesan kepada pelaksanaan, oleh itu ianya ditunjukkan sebagai Tidak serasi atau Akan disahkan oleh Pengguna.
Anda perlu sesuaikan proses ujian tersuai bagi setiap perubahan dalam Aplikasi mengikut SAP.
Anda juga perlu tanda status keserasian keluaran dengan Telah Disahkan oleh Pengguna.
Sifat
Dimensi penelusuran, ukuran, dan maklumat lain digunakan dalam langkah.
Dimensi juntai bawah, ukuran, dan maklumat lain, contohnya, mata wang, digunakan dalam langkah.
Pastikan anda hanya memilih sifat yang akan dipaparkan dalam perwakilan.
Untuk langkah hierarki, masukkan sifat bukan hierarki.
Berikut ialah sifat yang dipaparkan dalam lajur selepas lajur pertama dalam jadual.
Pastikan anda hanya masukkan yang berikut sebagai sifat bukan hierarki:
Ukuran
Teks sifat hierarki
Sifat yang mempunyai nilai yang sama merentasi keseluruhan hierarki, contohnya mata wang pelaporan
Jangan gunakan sifat penelusuran yang lain selain daripada sifat hierarki kerana jadual pepohon tidak boleh kendalikan kriteria penelusuran tambahan.
Aktiviti Pengguna
Pilih jika ingin jejaki aktiviti dan aplikasi terbaru yang digunakan atau kosongkan sejarah anda.
Tentukan sama ada anda ingin menjejaki aktiviti pengguna anda.
Tetapkan Jejak aktiviti terbaru saya dan aplikasi yang kerap digunakan kepada TIDAK untuk memberhentikan penjejakan aktiviti pengguna.
Kemudian, entri Aktiviti Terkini dan Kerap Digunakan dikeluarkan daripada menu tindakan pengguna.
Klik Kosongkan untuk memadam aktiviti pengguna anda.
Jika Jejak aktiviti terbaru saya dan aplikasi yang kerap digunakan ditetapkan kepada YA, senarai Aktiviti Terbaru dan Kerap Digunakan dikosongkan tetapi sistem terus menjejaki aktiviti anda dan memaparkan item baharu dalam senarai aktiviti pengguna.
Untuk maklumat lanjut, lihat dan
Kelulusan Diperlukan
Medan ini menentukan sama ada rekod data dikeluarkan untuk profil entri data ini ialah subjek untuk tatacara kelulusan sebelum dipindahkan ke aplikasi sasaran.
Anda boleh memilih daripada pilihan berikut:
Tanpa tatacara kelulusan:
Data direkod dengan profil entri data bukan subjek ke tatacara kelulusan.
Data untuk dibuat tersedia bagi pindahan ke aplikasi sasaran secara langsung selepas menyimpan atau keluarkan.
Dengan tatacara kelulusan:
Semua masa bekerja direkod dengan profil entri data ialah subjek ke tatacara kelulusan.
Kunci Pengeposan Kos Sekunder
Kunci pusat kos untuk pengeposan kos sekunder.
Apabila pilihan ini didayakan, tiada kos sekunder boleh diposkan untuk pusat kos.
Pilihan ini mengunci pusat kos terhadap kos sekunder debit pengeposan.
Walau bagaimanapun, kos sekunder dikreditkan masih boleh diposkan.
Tetapan lalai untuk pilihan ini adalah berdasarkan pada tetapan Kategori Pusat Kos.
Kos sekunder digunakan untuk peruntukan kos dalaman dalam Pengawalan.
Berikut tidak menjejaskan data dalam Perakaunan Kewangan.
Kawalan Julat Tarikh - Contoh
Anda ingin pilih julat tarikh dari 1 Oktober hingga 15 Oktober.
Anda pilih Julat Tarikh daripada senarai juntai bawah dalam medan pertama, kllik simbol kalendar dalam medan kedua dan pilih tarikh (1 Oktober, 15 Oktober) daripada kalendar untuk mentakrifkan julat tarikh untuk item baris.
Anda ingin lihat semua item baris sejak 1 Jun.
Anda pilih Dari dalam medan pertama dan pilih 1 Jun daripada kalendar dalam medan kedua.
Anda ingin lihat semua item baris dengan tarikh dalam sepuluh hari terakhir.
Anda pilih Hari X Terakhir daripada senarai juntai bawah dalam medan pertama dan masukkan 10 ke dalam medan kedua.
Ubah Kapasiti Tersedia
Dalam timbul ini, anda boleh pilih tempoh masa yang berbeza dan mengubah kapasiti sedia ada pusat kerja.
Dalam Tempoh untuk Ditunjukkan, pilih tempoh masa yang dikehendaki.
Semak lajur Penggunaan Kapasiti Dicadangkan (dalam peratus) dengan teliti.
Jika anda setuju dengan cadangan, hanya klik Terima Pakai Cadangan, kemudian klik Guna.
Pastikan perubahan penggunaan kapasiti boleh diterima.
Anda boleh memilih untuk meningkatkan kapasiti tersedia berbeza ke peratusan yang dicadangkan.
Untuk melakukannya, masukkan penggunaan kapasiti yang disasarkan dalam medan Penggunaan Kapasiti Baharu (dalam Peratus) dan klik Guna.
Dalam medan Tempoh untuk Paparkan, anda boleh pilih tempoh berbilang untuk semak jika terdapat baki kapasiti yang anda boleh gunakan.
Selepas Ubah Suai
Gunakan corak ini untuk kira semula data selepas pengubahsuaian.
Corak ini digunakan untuk kira semula data dengan segera selepas tika nod telah dicipta atau diedit dan kemudian disimpan.
Logik bagi corak ini menulis ganti nilai medan seperti rentetan atau tarikh teks.
Jika tika nod telah dipadam, corak ini digunakan untuk memaklumkan nod bersandar bagi pemadaman dan picu pengiraan semula mereka.
Sampel kes penggunaan:
Anda mahu kira subnod yang terkandungi di bawah nod punca bagi objek perniagaan tersuai atau anda mahu simpan individu yang terakhir ubah suai objek perniagaan tersuai.
RUC_CONF_SUP_CATMAN_CONFIG_EVAL_EMAIL
Anda mulakan proses penilaian pembekal dengan meminta maklumat daripada penilai.
Untuk lakukan ini, anda hantar e-mel ke penilai anda.
Dalam aplikasi konfigurasi ini, anda harus tentukan pengguna yang dipaparkan sebagai penghantar e-mel ini.
Jika teks jemputan e-mel telah ditentukan dalam template penilaian, teks ini digunakan dalam e-mel untuk penilai.
Jika tiada teks jemputan e-mel dalam template penilaian, sama ada templat e-mel lalai disediakan oleh SAP digunakan.
Dalam aplikasi konfigurasi ini, anda boleh gantikan template disediakan oleh SAP dengan templat anda sendiri.
Pemeriksa
Tunjukkan isu untuk permintaan tahap teratas.
Pemeriksa mengesan keluaran kapasiti setiap permintaan teratas dan memaparkannya dengan sel berwarna merah.
Pilih sel berwarna merah satu per satu untuk melihat semua keluaran kapasiti yang berkaitan dengan permintaan tahap teratas.
Daripada permintaan tahap teratas anda boleh klik Simulasi Bahan Pelbagai Tahap untuk navigasi paparan berstruktur bagi bil bahan dan membuat simulasi pada tahap komponen, contohnya mengubah sumber bekalan atau mempunyai komponen prapengeluaran.
Beban Berlebihan Kapasiti
Isu boleh dikaitkan dengan permintaan tahap teratas yang dipilih tetapi ia juga boleh disebabkan oleh permintaan tahap teratas lain.
Semak isu dengan teliti dan siasat perkara yang menyebabkan beban berlebihan kapasiti.
Untuk setiap bahan tahap teratas, pemeriksa menunjukkan Kongsi dalam Kapasiti Digunakan, iaitu jumlah bilangan permintaan tahap teratas yang menyumbang kepada beban berlebihan kapasiti.
Klik Simulasi Rancangan Kapasiti untuk lihat dan edit kapasiti pusat kerja yang sepadan.
Tarikh Tamat Asas Berkaitan
Tentukan tarikh tamat bagi pesanan yang berkaitan dengan tarikh semasa.
Tarikh tamat asas ialah masa tamat yang dirancang bagi pesanan.
Anda boleh membuat tetapan untuk menentukan tarikh tamat asas yang berkaitan dengan tarikh semasa.
Anda boleh masukkan nilai negatif untuk menentukan masa dalam masa lampau.
Kemudian, tarikh tamat dikira ke belakang dalam hari kalendar.
Mengikut lalai, -30 hari telah ditetapkan.
Dalam gabungan dengan entri untuk Status 1, pesanan, yang sepadan dengan status ini pada tarikh yang ditentukan, akan ditetapkan kepada ditutup.
Jika zon waktu ditetapkan dalam Takrifkan Corak Perulangan berbeza daripada zon waktu yang digunakan oleh pelayan anda, sistem akan mengira semula tarikh tamat asas yang berkaitan berdasarkan pada zon waktu pelayan.
Perubahan Profil
Anda boleh profil ini untuk menapis produk anda berdasarkan perubahan dalam umpukan profil atau faktor profil.
Anda boleh menggunakannya untuk menapis produk anda berdasarkan perubahan dalam profil.
Anda boleh pilih satu daripada pilihan berikut:
Tiada Perubahan - paparkan produk dengan tiada perubahan sama ada umpukan profilnya atau faktor profilnya
Umpukan Profil - paparkan produk untuk mana-mana penunjuk pemboleh ubah, penunjuk masa pendulu, atau jenis perolehan yang diubah
Faktor Profil - paparkan produk untuk mana-mana faktor pemboleh ubah, faktor masa pendulu, atau kuantiti pesanan minimum yang diubah
Rekod Diimport
Bilangan rekod pembayaran yang berjaya diimport.
Klik atau tap bilangan rekod yang berjaya diimport dan pilih aplikasi untuk diproses.
Bergantung pada jenis rekod yang anda import, aplikasi tersedia untuk anda mungkin termasuk:
Urus Penyata Bank – pilih aplikasi ini untuk semak semula penyata bank diimport dan item barisnya.
Urus Kelompok Kotak Kunci – pilih aplikasi ini untuk semakan semula kelompok kotak kunci diimport dan semak kandungannya.
Proseskan Semula Itme Penyata Bank – pilih aplikasi ini untuk proses semula item penyata bank yang tidak diumpukkan secara automatik.
Tiada rekod telah diimport, pilihan ini tidak tersedia.
Semakan Pendua untuk Rekod Induk
Semakan untuk pendua berpotensi bagi rekod induk
Semakan pendua pada titik penciptaan data induk membenarkan pengguna untuk menemui mana-mana pendua berpotensi sudah sedia ada dalam sistem.
Jika pendua berpotensi dicadangkan oleh sistem, pengguna mempunyai pilihan sama ada membatalkan penciptaan tika baru atau meneruskannya sekiranya ia memutuskan rekod baru bukan sebenarnya menyalin data.
Dengan mengklik butang Semak, aplikasi menjalankan semakan fungsian pada rekod dan memaparkan ralat sekiranya ada.
Contohnya, sekiranya anda tidak menyelenggarakan medan Perihalan untuk rekod draf, aplikasi akan menjanakan mesej ralat dan akan menghentikan pemprosesan selanjutnya sehingga ralat diselesaikan.
Jika semakan fungsional selesai tanpa ralat, aplikasi akan menunjukkan senarai pendua berpotensi yang wujud untuk rekod draf semasa.
Dalam kotak dialog yang dibuka, butiran asas rekod draf semasa ditunjukkan terlebih dahulu, diikuti dengan senarai rekod pendua berpotensi teratas yang sepadan dengan rekod draf semasa.
Janakan Semula Hierarki
Anda kini boleh menjanakan semula pelbagai hierarki sekaligus.
Ciri baru ini membenarkan anda mengemas kini pelbagai hierarki secara serentak apabila terdapat perubahan data induk anda.
Jika pusat kos baru ditambah, contohnya, anda boleh menjana semula semua hierarki yang dipengaruhi oleh perubahan data induk pada satu masa, bukannya secara tunggal.
Contohnya, jika anda memilih untuk menjana semula hierarki yang sah dari "hari ini atau sebelum", maka tarikh rujukan data induk adalah hari ini.
Tindakan ini memilih semua pusat kos yang sah pada hari ini dan membenarkan anda untuk menjanakan semula hierarki yang mengandungi pusat kos menggunakan data induk anda yang dikemas kini.
Jika hierarki akan sah pada tarikh yang akan datang, maka anda boleh memilih untuk semua pusat kos menggunakan tarikh "sah dari”.
Harga Jualan Berbeza
Harga jualan berbeza bagi barangan dan perkhidmatan
Amaun ini ialah harga jualan berbeza bagi barangan atau perkhidmatan didarabkan dengan kuantiti.
Untuk urus niaga berdasarkan projek, harga jualan berbeza dimasukkan oleh pengurus projek.
Untuk proses jual daripada stok, harga jualan berbeza kebiasaannya berdasarkan syarat yang disimpan dalam tatacara harga pesanan.
Nilai syarat dikira secara automatik semasa pesanan dicipta.
Walau bagaimanapun, jika tiada rekod induk syarat wujud, amaun haruslah dimasukkan secara manual dalam pesanan.
Amaun tidak boleh menjadi sifar
Kesan Perakaunan
Tunjukkan catatan jurnal yang berkaitan dengan transaksi pengecaman hasil.
Catatan jurnal boleh dipaparkan sebagai akaun T atau jadual.
Dalam paparan akaun T, catatan jurnal dipaparkan dalam borang surat T dengan entri debit dan kredit ditunjukkan di kedua-dua sisi T. Untuk mengetahui lebih lanjut mengenai paparan akaun T, lihat.
Jika penapis Gunakan Baki Pembukaan ditetapkan kepada Ya, baris pertama akaun T menunjukkan baki pembukaan akaun sebelum pengeposan sementara baris akhir menunjukkan baki penutupannya selepas pengeposan.
Baki Pembukaan - Baki entri akaun sebelum pengeposan dokumen yang dipilih.
Baki pembukaan sama dengan baki penutupan yang dibawa ke hadapan daripada pengeposan dokumen sebelumnya.
Baki Penutupan - Baki akaun selepas pengeposan dokumen yang dipilih.
Baki penutupan ialah jumlah baki pembukaan sebelum pengeposan dokumen dan semua entri ke akaun dengan dokumen yang dipilih.
Baki pembukaan dan penutupan dikira berdasarkan pada tempoh perakaunan yang ditentukan dalam penapis Julat Dokumen.
Tahap Pengisian
Menunjukkan tahap pengisian semasa jadual.
Anda boleh memaparkan tahap pengisian jadual.
Tahap pengisian mempunyai penunjuk berikut:
Tahap pengisian maksimum untuk jadual ialah 100% (2 bilion).
Tahap pengisian untuk jadual ialah 15% (300 juta).
Pengusiaan dicadangkan pada tahap pengisian ini.
Tahap pengisian kritikal untuk jadual ialah 75% (1.5 bilion).
Pengusiaan mesti dijalankan pada tahap pengisian.
Kitaran Hayat
Takrifkan klausa pembaharuan dan penamatan untuk transaksi undang-undang.
Aspek ini mempunyai dua subaspek:
Pembaharuan dan Penamatan:
Anda boleh mentakrifkan klausa pembaharuan dan penamatan untuk transaksi undang-undang.
Jika klausa ini telah pratakrif dalam konteks, anda masih boleh ubah suai nilai di sini kecuali jenis pembaharuan atau penamatan.
Semua Tarikh:
Anda boleh melihat semua tarikh yang dijanakan secara automatik apabila klausa pembaharuan atau penamatan ditakrifkan dalam transaksi undang-undang atau pratakrif dalam konteks.
Tapis mengikut Status Jalanan Terakhir
Tapis mengikut status jalanan terakhir.
Anda boleh tapis mengikut Status Jalanan Terakhir.
Anda boleh tapis mengikut:
Semua - Menunjukkan semua jalanan pengusiaan data.
Gagal- Menunjukkan yang jalanan pengusiaan data terakhir telah gagal.
Anda boleh semak sama ada objek pengusiaan data diumpukkan adalah aktif.
Dalam Proses- Menunjukkan yang jalanan pengusiaan data sedang berjalan.
Berjaya- Menunjukkan yang jalanan pengusiaan data terakhir berjaya.
Tidak Dimulakan- Menunjukkan yang nilai ambang belum dicapai untuk objek pengusiaan data bagi kumpulan pengusiaan data dipilih.
Perkara ini bermaksud yang jalanan pengusiaan data tidak perlu dilaksanakan.
Jenis Bank dalam Rantaian Bank
Takrifkan jenis bank yang diumpukkan ke bank perantara.
Terdapat beberapa jenis bank yang anda boleh umpukkan ke bank perantara anda apabila mencipta rantaian bank.
Setiap bank diumpukkan dengan nombor:
Bank surat-menyurat penghantar
Bank perantara
Bank surat-menyurat penerima
Bank syarikat luaran (digunakan untuk pembayaran tunai dalaman sahaja)
Paksa Kemas Kini Pakar Koleksi
Tulis ganti pakar koleksi untuk semua pekongsi perniagaan setiap segmen.
Jika penunjuk ditetapkan:
Anda boleh menulis ganti pakar koleksi dalam segmen koleksi yang dipilih.
Anda boleh mengeluarkan pakar koleksi sedia ada daripada segmen koleksi yang dipilih dengan membiarkan medan Pakar Koleksi kosong.
Jika penunjuk tidak ditetapkan:
Pakar koleksi sedia ada terkumpul jika mungkin.
Jika pakar koleksi tidak diumpukkan kepada kumpulan koleksi, pakar koleksi dimulakan dalam kes ini.
Tiada Pemprosesan Diperlukan
Alihkan item yang tidak memerlukan pemprosesan dari Dialih Keluar ke Sejarah Proses.
Item yang Dialih Keluar sama ada boleh dibetulkan dan dihantar semula atau dibalikkan.
Untuk dokumen yang tidak boleh dibetulkan atau dihantar semula, dokumen balikan mestilah diserahkan kepada sistem pekongsi.
Dalam kes ini, kedua-dua dokumen muncul di bawah Dialih Keluar.
Contohnya, anda menyerahkan item 001, tetapi amaun cukai tidak betul.
Hasilnya, anda perlu menyerahkan item 002 kepada sistem pekongsi anda untuk item balikan 001.
Kedua-dua item ini tersenarai di bawah Dialih Keluar.
Dialih Keluar ialah tempat pegangan sementara untuk item yang anda perlu edit atau hantar semula.
Walau bagaimanapun, anda tidak boleh edit atau hantar semula dokumen balikan.
Jika tiada memprosesan lanjutan diperlukan, seperti kes dokumen balikan, anda boleh pilih Tiada Pemprosesan Diperlukan.
Setelah anda menyesahkan bahawa anda ingin tanda item dalam soalan seperti Dibalikkan, ia dialih keluar dari Dialih Keluar dan ke dalam Sejarah Proses.
Oleh itu, anda ketahui bajawa anda tidak perlu untuk selenggara item dan boleh fokus pada item lain dalam Dialih Keluar yang boleh diedit dan dihantar semula
Sila ambil perhatian bahawa status ini hanya menetapkan item yang telah disemak dan ditentukan dan ia tidak boleh diedit atau diserahkan semula.
Dialog Penciptaan Diubah
Dialog untuk mencipta fungsi perniagaan telah diubah.
Apabila anda mencipta fungsi perniagaan baharu, anda akan menyedari perubahan berikut:
Data pentadbiran sistem telah dialihkan ke bahagian atas dialog.
ID fungsi perniagaan telah dialihkan ke atas perihalan.
Fungsi perniagaan anda akan berada dalam status Draf selagi anda tidak menyimpan fungsi perniagaan.
Setelah anda menyimpan fungsi perniagaan, ia akan diaktifkan dan ditetapkan kepada status Aktif sewajarnya.
Jika anda meninggalkan dialog tanpa menyimpan fungsi perniagaan, fungsi perniagaan yang baru dicipta akan tersedia pada paparan keseluruhan fungsi perniagaan dalam status Draf.
Butang Selenggara Sekatan telah dialihkan ke bahagian atas dialog.
API
Boleh perluas, APIs (ODATA dan SOAP) dikeluarkan dibolehkan untuk konteks perniagaan dipilih.
Tab API termasuk yang berikut:
Maklumat untuk meminta API baru
Navigasi ke API Hub untuk butiran mengenai API dipilih
Butiran (ID Senario, Aturan Komunikasi) mengenai senario penyepaduan untuk menggunakan API
Navigasi ke aplikasi Aturan Komunikasi untuk butiran mengenai penyepaduan
Subnombor Aset
Kenal pasti aset tetap apabila digabungkan dengan nombor utama aset.
Nombor ini bersama-sama dengan nombor aset utama yang mengenal pasti secara unik aset tetap dalam Perakaunan Aset.
Dengan menggunakan subnombor aset, anda boleh:
Membekalkan pengurusan berasingan bagi perolehan kemudian untuk aset.
Mewakili aset tetap kompleks dengan bahagian komponennya.
Berbeza dengan nombor aset utama, subnombor aset mesti berangka.
RUC_CONF_LOG_F1329
Kos penghantaran tidak terancang ialah kos yang tidak dirancang dalam pesanan belian dan tidak dimasukkan dalam sistem sehingga invois diterima.
Anda boleh tentukan cara sistem mengepos kos penghantaran tidak terancang dalam Pengesahan Invois Logistik.
Terdapat dua pilihan:
Kos penghantaran tidak terancang diagihkan antara item invois individu dalam perkadaran amaun item yang diinvoiskan setakat itu dan amaun item dalam invois semasa.
Amaun ditentukan ditambah ke dalam amaun item masing-masing.
Amaun ditentukan dipos dalam baris berasingan untuk setiap item.
Kos penghantaran tidak terancang dipos dalam baris berasingan pada akaun lejar am berasingan.
Dalam kes ini, anda mesti masukkan kod cukai tertentu untuk pengeposan pada aras kod syarikat.
Penguraian Nilai Pasaran
Kiraan penguraian nilai pasaran ii diperlukan
Anda gunakan penunjuk untuk mengira penguraian nilai pasaran (titik, hadapan, CCBS, dan komponen lain) untuk urus niaga kewangan dipilih yang diumpukkan sebagai instrumen perlindungan nilai dalam hubungan perlindungan nilai ditentukan (P-HA) yang dicipta semasa Proses Penentuan Diautomatikkan.
Pengiraan dibuat untuk instrumen perlindungan nilai dan juga untuk derivatif andaian penghubung.
Apabila urus niaga kewangan adalah sebahagian lebih daripada satu hubungan perlindungan nilai, pengiraan dibuat secara berasingan bagi setiap hubungan perlindungan nilai.
Pengiraan sentiasa dibuat untuk amaun nominal bagi urus niaga kewangan.
Nilai berkadar berkaitan untuk hubungan perlindungan nilai tertentu adalah dikira dalam perakaunan lindung nilai.
Anda boleh sekat pengiraan dengan memilih bahagian penilaian tertentu
Medan Tersedia
Papar medan yang tersedia untuk pelaksanaan peningkatan.
Medan tersedia bagi pelaksanaan peningkatan anda diterangkan melalui parameter yang anda boleh lihat dalam mod ujian.
Prameter ini dipratakrifkan melalui pilihan peningkatan sepadan.
Jika anda mencipta medan untuk antara muka yang sama dengan pelaksanaan peningkatan anda, anda juga boleh meningkatkan medan ini dalam pelaksanaan peningkatan.
Dalam mod draf, anda boleh menguji pelaksanaan peningkatan mengikut senario perniagaan anda dengan medan tersedia.
Masukkan nilai ujian untuk medan dan jalankan pelaksanaan peningkatan anda.
Aplikasi menyediakan anda dengan hasil ujian.
Bahan Pukal
Komponen bahan yang anda mempunyai capaian langsung pada pusat kerja (bahan longgar seperti gris atau pencuci).
Anda boleh memasukkan penunjuk bahan pukal dalam rekod induk bahan dan item bil bahan.
Jika bahan ditakrifkan sebagai bahan pukal, keperluan bersandar untuk bahan ini tidak berkaitan dengan MRP.
MRP untuk bahan pukal adalah berdasarkan penggunaan.
Penunjuk dalam rekod induk bahan
Anda boleh takrifkan bahan sebagai bahan pukal dalam data MRP bagi rekod induk bahan.
Jika anda menetapkan penunjuk bahan pukal dalam rekod induk bahan, sistem menetapkan bahan pukal dalam penunjuk induk bahan pada bil bahan.
Penunjuk dalam bil bahan
Penunjuk ini hanya disokong untuk item yang berkaitan dengan penyelenggaraan pengeluaran atau loji ataupun kedua-duanya.
Item tidak boleh berkaitan dengan pengekosan.
Anda tidak boleh memasukkan lokasi simpanan pengeluaran untuk bahan pukal.
Penunjuk dalam induk bahan menggantikan penunjuk dalam item bil bahan.
Penunjuk dalam item bil bahan memberitahu anda sama ada bahan yang ditakrifkan sebagai bahan pukal dalam induk bahan.
Jika bahan sentiasa digunakan sebagai bahan pukal, tetapkan penunjuk bahan pukal dalam rekod induk bahan.
Jika bahan hanya kadang-kadang digunakan sebagai bahan pukal, tetapkan penunjuk bahan pukal dalam item bil bahan
Jika bil bahan hanya diperuntukkan untuk satu loji, anda akan melihat nilai lalai daripada rekod induk bahan dalam loji ini apabila anda menciptanya.
RUC_CONF_FIN_CO_AUTOACCTASSGMT
Anda boleh tentukan umpukan akaun pusat kos automatik di aras kod syarikat.
Jika perlu, anda boleh bezakan pada aras bahagian penilaian untuk membenarkan kegranulan yang lebih besar.
Apabila anda mencipta pengeposan untuk akaun itu, sistem mencadangkan objek berkaitan perakaunan kos yang sepadan.
Anda boleh gunakan umpukan akaun automatik untuk yang berikut:
Memindahkan perbezaan harga yang dipos dalam pembelian sebagai hasil harga berbeza semasa penerimaan invois
Menilai semula stok bahan
Memindahkan perbezaan inventori
E-mel
Hantar penghubung sebagai lampiran e-mel.
Untuk menghantar dokumen penghubung sebagai lampiran e-mel:
Pilih E-mel.
Jenis alamat e-mel bagi penerima.
Anda boleh menambah beberapa penerima.
Tambah subjek atau biarkannya begitu sahaja.
Pilih templat e-mel yang sepadan dengan jenis penghubung yang anda pilih.
Contohnya, jika anda memilih Senarai Item Terbuka, gunakan Cipta Penghubung:
Templat e-mel Senarai Item Terbuka.
Templat ini menjana mesej e-mel yang mengingatkan penerima mengenai item terbuka untuk akaun mereka.
Semak semula mesej e-mel.
Klik Hantar untuk menghantar e-mel.
Dokumen penghubung dilampirkan pada e-mel sebagai fail PDF.
Uruskan Subpasukan
Umpukan subpasukan
Untuk umpukan atau batalkan umpukan subkumpulan untuk pasukan dipilih, pilih Uruskan Subpasukan kemudian gunakan butang togol YA atau TIDAK daripada senarai Umpukan Subpasukan.
Senarai termasuk subkumpulan:
Kepunyaan kategori yang sama sebagai pasukan induk
Bukan kepunyaan hierarki lain
Terdapat nilai takrifan tanggungjawab yang sepadan dengan induk walaupun bilangan takrifan tanggungjawab mungkin sama atau tidak.
Untuk mengelakkan umpukan semula subpasukan sedia ada, pasukan anak subpasukan disembunyikan daripada paparan selepas subpasukan diumpukkan ke pasukan induk.
Apabila anda nyahaktifkan subpasukan, pasukan anak ditunjukkan dalam paparan.
Laraskan Item
Buat pelarasan berasaskan masa untuk jumlah item.
Untuk mengubah amaun item yang tamat tempoh pada tarikh tertentu, pilih item anda, kemudian cipta pelarasan dengan memilih Laraskan Masa.
Masukkan amaun yang berbeza (sama ada amaun positif atau negatif) dan sebab pelarasan, kemudian simpan.
Ianya mencipta item pelarasan.
Amaun yang dibilkan ialah jumlah amaun item utama dan apa-apa amaun item penyesuaian yang berkaitan.
Anda boleh mencipta lebih daripada satu pelarasan untuk item rancangan pengebilan, tetapi anda tidak boleh mencipta pelarasan untuk item pelarasan.
Pesanan Belian Tidak Diluluskan
Paparkan pesanan belian yang belum lagi diluluskan untuk bahan bukan stok
Kad paparkan bilangan pesanan belian yang belum lagi diluluskan untuk bahan bukan stok yang diperlukan sebagai alat ganti dalam pesanan penyelenggaraan.
Bahan bukan stok diperlukan untuk kerja penyelenggaraan dalam tempoh rujukan yang telah anda pilih.
Pesanan belian yang belum lagi dikeluarkan dipilih sama ada dengan menggunakan tarikh keperluan atau tarikh mula diperlukan.
Jika bahan bukan stok diminta semasa pesanan penyelenggaraan diproses, tarikh keperluan bahan yang telah dimasukkan dalam simpanan akan digunakan sebagai pemilihan.
Jika bahan dipesan secara langsung dan diumpukkan kepada pesanan penyelenggaraan, tarikh mula pesanan yang diperlukan akan digunakan sebagai pemilihan.
Jika anda ingin paparkan semua pesanan belian yang belum lagi diluluskan dengan itemnya dalam senarai, klik pada kad.
Dalam senarai, anda boleh cabangkan ke pesanan belian, data butiran untuk bahan dan pesanan penyelenggaraan, atau paparkan data individu untuk dihubungi bagi pembekal.
Jika anda klik pada bahagian sebelah kanan kad, anda boleh melihat pesanan belian terbuka dengan maklumat yang lebih penting dipaparkan pada kad dalam karusel.
Pada kad untuk pesanan belian individu dalam karusel, anda juga boleh cabangkan ke pesanan penyelenggaraan atau pesanan belian dan paparkannya.
Ubah Harga Inventori
Ubah harga untuk penilaian inventori
Membolehkan anda mengubah harga yang digunakan untuk menilai kuantiti bahan dalam inventori.
Perubahan harga berkuat kuasa pada tarikh pengeposan tertentu.
Masukkan tarikh pengeposan dan teks pengepala untuk dokumen bahan.
Masukkan harga baru untuk semua jenis mata wang.
Jika anda mengubah harga dalam mata wang kod syarikat, anda boleh melaraskan harga dalam mata wang lain mengikut kod syarikatnya dengan mengklik Tukar.
Butiran Tika (Paparan Carta)
Bahagian yang menunjukkan semua tika situasi yang dipilih untuk pemantauan.
Anda mempunyai beberapa pilihan untuk memaparkan aktiviti tika yang aplikasinya dipaparkan mengikut entri yang dibuat dalam bahagian penapis:
Gabungan grafik dan berjadual memaparkan data
Paparan grafik sahaja
Paparan berjadual sahaja
Jika anda menggunakan paparan gabungan, apa-apa pemilihan yang anda buat dalam grafik juga ditunjukkan dalam paparan jadual.
Anda juga boleh memilih antara paparan grafik yang berbeza.
Teks Sudut
Taks dipaparkan dalam empat sudut bagi imej kecil langkah.
Taks dipaparkan dalam empat sudut bagi imej kecil langkah dalam paparan laluan analisis.
Semuanya ialah pilihan.
Medan diisi awal dengan teks yang dimasukkan pada aras langkah, jika berkaitan.
Semasa teks dimasukkan atau diubah pada aras perwakilan, teks ini mengutamakan teks yang sepadan dimasukkan pada aras langkah dan dipaparkan pada masa jalanan.
Semasa anda mengubah semula teks yang sama pada aras langkah, perubahan tidak disalin ke perwakilan dan juga tidak dilihat pada masa jalanan.
Ini hanya digunakan pada perwakilan bagi perubahan yang dibuat pada aras perwakilan.
Pengisihan
Takrifkan sifat yang digunakan ke carta sebagai kriteria isihan.
Takrifkan sifat yang digunakan ke permintaan data dan berikutnya ke carta sebagai kriteria isihan.
Anda juga boleh tentukan arah isihan (menaik atau menurun) untuk stiap sifat.
Jika anda tidak tentukan medan isihan, data dipaparkan dalam pesanan yang dibekalkan oleh perkhidmatan OData.
Jika kriteria pengisihan telah ditakrifkan pada bahagian Pengurangan Data bagi konfigurasi langkah, ia disalin ke perwakilan dan tidak boleh diubah di sini.
Tidak semua perwakilan penyokong isihan yang lebih daripada satu sifat untuk keluasan penuh.
Tarikh Tamat Asas Berkaitan
Tentukan Tarikh Tamat Asas Berkaitan bagi pesanan yang berkaitan dengan tarikh semasa.
Tarikh tamat asas ialah masa tamat dirancang bagi pesanan. Anda boleh membuat tetapan untuk menentukan tarikh tamat asas yang berkaitan dengan tarikh semasa.
Anda boleh masukkan nilai negatif untuk menentukan masa dalam masa lampau.
Kemudian, tarikh tamat dikira ke belakang dalam beberapa hari.
Mengikut lalai, -5 hari telah ditetapkan.
Dalam gabungan dengan entri untuk Status 1 = (CNF) bagi pesanan yang telah disahkan (CNF) lima hari lalu, pesanan yang sepadan dengan kriteria ini akan ditetapkan kepada selesai secara teknikal.
